// Generated by scripts/generate-desktop-protocol.mjs. Do not edit by hand.
import type * as Model from "../models";
import type { WindowChromeMode } from "../workbench/window-chrome";

export const DESKTOP_PROTOCOL_VERSION = 1 as const;

export interface DesktopCommandMap {
  window_chrome_mode: { args: Record<string, never>; result: WindowChromeMode };
  initial_repository: { args: Record<string, never>; result: string | null };
  open_project: { args: { path: string; }; result: Model.OpenedProject };
  read_tracked_changes: { args: { repositoryRoot: string; }; result: Model.TrackedChangeScan };
  open_repository_window: { args: { path: string; }; result: string };
  read_history_page: { args: { repositoryRoot: string; query: Model.HistoryQuery; offset: number; limit: number; }; result: Model.HistoryPage };
  scan_untracked: { args: { repositoryRoot: string; scanId: string; }; result: Model.UntrackedScan };
  cancel_untracked_scan: { args: { scanId: string; }; result: void };
  read_diff: { args: { repositoryRoot: string; path: string; staged: boolean; }; result: Model.DiffResult };
  read_local_diff: { args: { repositoryRoot: string; selected: Model.FileChange; expandedUnchanged: boolean; }; result: Model.DiffResult };
  read_image_file: { args: { repositoryRoot: string; repositoryId: string; path: string; }; result: Model.ImagePreview };
  read_local_image_diff: { args: { repositoryRoot: string; selected: Model.FileChange; }; result: Model.ImageDiffPreview };
  list_project_files: { args: { repositoryRoot: string; }; result: Model.ProjectFileList };
  search_workspace_text: { args: { repositoryRoot: string; requestId: string; query: string; options: Model.WorkspaceTextSearchOptions; }; result: Model.WorkspaceTextSearchReport };
  cancel_workspace_text_search: { args: { repositoryRoot: string; requestId: string; }; result: void };
  preview_workspace_replacement: { args: { repositoryRoot: string; planId: string; query: string; replacement: string; options: Model.WorkspaceTextSearchOptions; }; result: Model.WorkspaceReplacementPreview };
  apply_workspace_replacement: { args: { repositoryRoot: string; planId: string; selectedPaths: Array<string>; }; result: Model.ReplacementApplyResult };
  cancel_workspace_replacement: { args: { repositoryRoot: string; operationId: string; }; result: void };
  list_workspace_replacement_recoveries: { args: { repositoryRoot: string; }; result: Array<Model.ReplacementRecoverySummary> };
  rollback_workspace_replacement: { args: { repositoryRoot: string; recoveryId: string; }; result: Model.ReplacementApplyResult };
  finalize_workspace_replacement: { args: { repositoryRoot: string; recoveryId: string; }; result: void };
  read_text_file: { args: { repositoryRoot: string; repositoryId: string; path: string; }; result: Model.TextFileSnapshot };
  save_text_file: { args: { repositoryRoot: string; repositoryId: string; path: string; expectedRevision: string; content: string; utf8Bom: boolean; requestId: string; }; result: Model.SaveTextFileResult };
  read_commit_details: { args: { repositoryRoot: string; repositoryId: string; commitOid: string; }; result: Model.CommitDetails };
  read_commit_diff: { args: { repositoryRoot: string; repositoryId: string; commitOid: string; path: string; originalPath: string | null; expandedUnchanged: boolean; }; result: Model.CommitDiffResult };
  read_commit_image_diff: { args: { repositoryRoot: string; repositoryId: string; commitOid: string; path: string; originalPath: string | null; }; result: Model.ImageDiffPreview };
  stage_paths: { args: { repositoryRoot: string; paths: Array<string>; }; result: Model.RepositoryMutationOutcome };
  unstage_paths: { args: { repositoryRoot: string; paths: Array<string>; }; result: Model.RepositoryMutationOutcome };
  commit_changes: { args: { repositoryRoot: string; message: string; selected: Array<Model.FileChange>; }; result: Model.CommitSelectedResult };
  revert_changes: { args: { repositoryRoot: string; selected: Array<Model.FileChange>; }; result: Model.RepositoryMutationOutcome };
  switch_branch: { args: { repositoryRoot: string; targetFullName: string; }; result: Model.RepositoryMutationOutcome };
  create_branch: { args: { repositoryRoot: string; name: string; }; result: Model.RepositoryMutationOutcome };
  fetch_remote: { args: { repositoryRoot: string; remote: string; operationId: string; }; result: Model.RepositoryMutationOutcome };
  read_push_preview: { args: { repositoryRoot: string; remote: string; tagMode: Model.PushTagMode; offset: number; pageSize: number; }; result: Model.PushPreview };
  read_push_file_commit: { args: { repositoryRoot: string; remote: string; tagMode: Model.PushTagMode; previewToken: string; path: string; }; result: Model.CommitDetails | null };
  pull_current: { args: { repositoryRoot: string; operationId: string; }; result: Model.RepositoryMutationOutcome };
  push_current: { args: { repositoryRoot: string; remote: string; mode: Model.PushMode; tagMode: Model.PushTagMode; previewToken: string; operationId: string; }; result: Model.RepositoryMutationOutcome };
  cancel_remote_operation: { args: { repositoryRoot: string; operationId: string; }; result: void };
}

export type DesktopCommandName = keyof DesktopCommandMap;

export const DESKTOP_RESULT_VALIDATORS: {
  readonly [Command in DesktopCommandName]: string;
} = {
  window_chrome_mode: "windowChromeMode",
  initial_repository: "nullableString",
  open_project: "openedProject",
  read_tracked_changes: "trackedChangeScan",
  open_repository_window: "string",
  read_history_page: "historyPage",
  scan_untracked: "untrackedScan",
  cancel_untracked_scan: "void",
  read_diff: "diffResult",
  read_local_diff: "diffResult",
  read_image_file: "imagePreview",
  read_local_image_diff: "imageDiffPreview",
  list_project_files: "projectFileList",
  search_workspace_text: "workspaceTextSearchReport",
  cancel_workspace_text_search: "void",
  preview_workspace_replacement: "workspaceReplacementPreview",
  apply_workspace_replacement: "replacementApplyResult",
  cancel_workspace_replacement: "void",
  list_workspace_replacement_recoveries: "replacementRecoveryList",
  rollback_workspace_replacement: "replacementApplyResult",
  finalize_workspace_replacement: "void",
  read_text_file: "textFileSnapshot",
  save_text_file: "saveTextFileResult",
  read_commit_details: "commitDetails",
  read_commit_diff: "commitDiffResult",
  read_commit_image_diff: "imageDiffPreview",
  stage_paths: "repositoryMutationOutcome",
  unstage_paths: "repositoryMutationOutcome",
  commit_changes: "commitSelectedResult",
  revert_changes: "repositoryMutationOutcome",
  switch_branch: "repositoryMutationOutcome",
  create_branch: "repositoryMutationOutcome",
  fetch_remote: "repositoryMutationOutcome",
  read_push_preview: "pushPreview",
  read_push_file_commit: "nullableCommitDetails",
  pull_current: "repositoryMutationOutcome",
  push_current: "repositoryMutationOutcome",
  cancel_remote_operation: "void",
};

