// Generated by scripts/generate-desktop-protocol.mjs. Do not edit by hand.
import type * as Model from "../models";
import type { WindowChromeMode } from "../workbench/window-chrome";

export const DESKTOP_PROTOCOL_VERSION = 1 as const;

export interface DesktopCommandMap {
  window_chrome_mode: { args: Record<string, never>; result: WindowChromeMode };
  initial_repository: { args: Record<string, never>; result: string | null };
  existing_project_directories: { args: { paths: Array<string>; }; result: Array<string> };
  open_project: { args: { path: string; }; result: Model.OpenedProject };
  read_project_snapshot: { args: { path: string; }; result: Model.OpenedProject };
  focus_existing_project_window: { args: { path: string; }; result: Model.ProjectWindowMatch };
  read_repository_slices: { args: { repositoryRoot: string; slices: Array<Model.RepositoryStateSlice>; }; result: Model.RepositorySliceProject };
  start_workspace_watch: { args: { workspaceRoot: string; generation: number; openDocumentPaths: Array<string>; }; result: Model.WorkspaceWatchStatus };
  stop_workspace_watch: { args: Record<string, never>; result: void };
  start_terminal: { args: { workspaceRoot: string; cols: number; rows: number; }; result: Model.TerminalStarted };
  write_terminal: { args: { sessionId: string; dataBase64: string; }; result: void };
  resize_terminal: { args: { sessionId: string; cols: number; rows: number; }; result: void };
  close_terminal: { args: { sessionId: string; }; result: boolean };
  read_tracked_changes: { args: { repositoryRoot: string; }; result: Model.TrackedChangeScan };
  open_repository_window: { args: { path: string; }; result: Model.ProjectWindowOpenResult };
  read_history_page: { args: { repositoryRoot: string; query: Model.HistoryQuery; offset: number; limit: number; }; result: Model.HistoryPage };
  scan_untracked: { args: { repositoryRoot: string; scanId: string; }; result: Model.UntrackedScan };
  cancel_untracked_scan: { args: { scanId: string; }; result: void };
  read_diff: { args: { repositoryRoot: string; path: string; staged: boolean; }; result: Model.DiffResult };
  read_local_diff: { args: { repositoryRoot: string; selected: Model.FileChange; expandedUnchanged: boolean; }; result: Model.DiffResult };
  read_image_file: { args: { repositoryRoot: string; repositoryId: string; path: string; }; result: Model.ImagePreview };
  read_local_image_diff: { args: { repositoryRoot: string; selected: Model.FileChange; }; result: Model.ImageDiffPreview };
  list_project_files: { args: { repositoryRoot: string; }; result: Model.ProjectFileList };
  reveal_workspace_entry: { args: { repositoryRoot: string; workspacePath: string; kind: Model.WorkspaceEntryKind; }; result: Model.WorkspaceRevealResult };
  inspect_workspace_entry: { args: { repositoryRoot: string; workspacePath: string; }; result: Model.WorkspaceEntryInspection };
  plan_workspace_mutation: { args: { repositoryRoot: string; planId: string; operation: Model.WorkspaceMutationOperation; collisionPolicy: Model.WorkspaceCollisionPolicy; }; result: Model.WorkspaceMutationPreview };
  execute_workspace_mutation: { args: { repositoryRoot: string; planId: string; }; result: Model.WorkspaceMutationOutcome };
  cancel_workspace_mutation: { args: { repositoryRoot: string; planId: string; }; result: void };
  list_workspace_mutation_recoveries: { args: { repositoryRoot: string; }; result: Array<Model.WorkspaceMutationRecoverySummary> };
  search_workspace_text: { args: { repositoryRoot: string; requestId: string; query: string; options: Model.WorkspaceTextSearchOptions; }; result: Model.WorkspaceTextSearchReport };
  cancel_workspace_text_search: { args: { repositoryRoot: string; requestId: string; }; result: void };
  preview_workspace_replacement: { args: { repositoryRoot: string; planId: string; query: string; replacement: string; options: Model.WorkspaceTextSearchOptions; }; result: Model.WorkspaceReplacementPreview };
  apply_workspace_replacement: { args: { repositoryRoot: string; planId: string; selectedPaths: Array<string>; }; result: Model.ReplacementApplyResult };
  cancel_workspace_replacement: { args: { repositoryRoot: string; operationId: string; }; result: void };
  list_workspace_replacement_recoveries: { args: { repositoryRoot: string; }; result: Array<Model.ReplacementRecoverySummary> };
  rollback_workspace_replacement: { args: { repositoryRoot: string; recoveryId: string; }; result: Model.ReplacementApplyResult };
  finalize_workspace_replacement: { args: { repositoryRoot: string; recoveryId: string; }; result: void };
  read_text_file: { args: { repositoryRoot: string; repositoryId: string; path: string; }; result: Model.TextFileSnapshot };
  save_text_file: { args: { repositoryRoot: string; repositoryId: string; path: string; expectedRevision: string; content: string; utf8Bom: boolean; requestId: string; }; result: Model.SaveTextFileResult };
  read_commit_details: { args: { repositoryRoot: string; repositoryId: string; commitOid: string; }; result: Model.CommitDetails };
  read_git_blame: { args: { repositoryRoot: string; repositoryId: string; path: string; commitOid: string | null; parent: boolean; }; result: Model.GitBlameResult };
  read_commit_diff: { args: { repositoryRoot: string; repositoryId: string; commitOid: string; path: string; originalPath: string | null; expandedUnchanged: boolean; }; result: Model.CommitDiffResult };
  read_commit_image_diff: { args: { repositoryRoot: string; repositoryId: string; commitOid: string; path: string; originalPath: string | null; }; result: Model.ImageDiffPreview };
  stage_paths: { args: { repositoryRoot: string; paths: Array<string>; }; result: Model.WorkingTreeMutationOutcome };
  unstage_paths: { args: { repositoryRoot: string; paths: Array<string>; }; result: Model.WorkingTreeMutationOutcome };
  commit_changes: { args: { repositoryRoot: string; message: string; selected: Array<Model.FileChange>; }; result: Model.CommitSelectedResult };
  prepare_restore_changes: { args: { repositoryRoot: string; selected: Array<Model.FileChange>; }; result: Model.RestoreChangesPlan };
  list_git_worktree_recoveries: { args: { repositoryRoot: string; }; result: Array<Model.GitWorktreeRecovery> };
  undo_git_worktree_recovery: { args: { repositoryRoot: string; recoveryId: string; }; result: Model.RepositoryMutationOutcome };
  revert_changes: { args: { repositoryRoot: string; plan: Model.RestoreChangesPlan; }; result: Model.WorkingTreeMutationOutcome };
  switch_branch: { args: { repositoryRoot: string; targetFullName: string; }; result: Model.RepositoryMutationOutcome };
  create_branch: { args: { repositoryRoot: string; name: string; }; result: Model.RepositoryMutationOutcome };
  read_remote_authentication: { args: { repositoryRoot: string; remote: string; }; result: Model.RemoteAuthenticationStatus };
  store_remote_https_credential: { args: { repositoryRoot: string; remote: string; username: string; token: string; }; result: Model.RemoteAuthenticationStatus };
  configure_remote_ssh: { args: { repositoryRoot: string; remote: string; sshUrl: string; }; result: Model.RemoteAuthenticationStatus };
  fetch_remote: { args: { repositoryRoot: string; remote: string; operationId: string; }; result: Model.RepositoryMutationOutcome };
  read_push_preview: { args: { repositoryRoot: string; remote: string; tagMode: Model.PushTagMode; offset: number; pageSize: number; }; result: Model.PushPreview };
  read_push_file_commit: { args: { repositoryRoot: string; remote: string; tagMode: Model.PushTagMode; previewToken: string; path: string; }; result: Model.CommitDetails | null };
  pull_current: { args: { repositoryRoot: string; operationId: string; }; result: Model.RepositoryMutationOutcome };
  push_current: { args: { repositoryRoot: string; remote: string; mode: Model.PushMode; tagMode: Model.PushTagMode; previewToken: string; operationId: string; }; result: Model.RepositoryMutationOutcome };
  cancel_remote_operation: { args: { repositoryRoot: string; operationId: string; }; result: void };
  read_git_operation: { args: { repositoryRoot: string; }; result: Model.GitOperationSnapshot | null };
  prepare_git_operation: { args: { repositoryRoot: string; kind: Model.GitOperationKind; targetRefs: Array<string>; message: string | null; }; result: Model.GitOperationPlan };
  execute_git_operation: { args: { repositoryRoot: string; plan: Model.GitOperationPlan; }; result: Model.RepositoryMutationOutcome };
  run_git_operation_action: { args: { repositoryRoot: string; action: Model.GitOperationAction; }; result: Model.RepositoryMutationOutcome };
  read_conflict_content: { args: { repositoryRoot: string; path: string; }; result: Model.GitConflictContent };
  resolve_conflict: { args: { repositoryRoot: string; path: string; expectedRevisionToken: string; content: string | null; }; result: Model.GitOperationMutationOutcome };
}

export type DesktopCommandName = keyof DesktopCommandMap;

export const DESKTOP_RESULT_VALIDATORS: {
  readonly [Command in DesktopCommandName]: string;
} = {
  window_chrome_mode: "windowChromeMode",
  initial_repository: "nullableString",
  existing_project_directories: "stringArray",
  open_project: "openedProject",
  read_project_snapshot: "openedProject",
  focus_existing_project_window: "projectWindowMatch",
  read_repository_slices: "repositorySliceProject",
  start_workspace_watch: "workspaceWatchStatus",
  stop_workspace_watch: "void",
  start_terminal: "terminalStarted",
  write_terminal: "void",
  resize_terminal: "void",
  close_terminal: "boolean",
  read_tracked_changes: "trackedChangeScan",
  open_repository_window: "projectWindowOpenResult",
  read_history_page: "historyPage",
  scan_untracked: "untrackedScan",
  cancel_untracked_scan: "void",
  read_diff: "diffResult",
  read_local_diff: "diffResult",
  read_image_file: "imagePreview",
  read_local_image_diff: "imageDiffPreview",
  list_project_files: "projectFileList",
  reveal_workspace_entry: "workspaceRevealResult",
  inspect_workspace_entry: "workspaceEntryInspection",
  plan_workspace_mutation: "workspaceMutationPreview",
  execute_workspace_mutation: "workspaceMutationOutcome",
  cancel_workspace_mutation: "void",
  list_workspace_mutation_recoveries: "workspaceMutationRecoveryList",
  search_workspace_text: "workspaceTextSearchReport",
  cancel_workspace_text_search: "void",
  preview_workspace_replacement: "workspaceReplacementPreview",
  apply_workspace_replacement: "replacementApplyResult",
  cancel_workspace_replacement: "void",
  list_workspace_replacement_recoveries: "replacementRecoveryList",
  rollback_workspace_replacement: "replacementApplyResult",
  finalize_workspace_replacement: "void",
  read_text_file: "textFileSnapshot",
  save_text_file: "saveTextFileResult",
  read_commit_details: "commitDetails",
  read_git_blame: "gitBlameResult",
  read_commit_diff: "commitDiffResult",
  read_commit_image_diff: "imageDiffPreview",
  stage_paths: "workingTreeMutationOutcome",
  unstage_paths: "workingTreeMutationOutcome",
  commit_changes: "commitSelectedResult",
  prepare_restore_changes: "restoreChangesPlan",
  list_git_worktree_recoveries: "gitWorktreeRecoveries",
  undo_git_worktree_recovery: "repositoryMutationOutcome",
  revert_changes: "workingTreeMutationOutcome",
  switch_branch: "repositoryMutationOutcome",
  create_branch: "repositoryMutationOutcome",
  read_remote_authentication: "remoteAuthenticationStatus",
  store_remote_https_credential: "remoteAuthenticationStatus",
  configure_remote_ssh: "remoteAuthenticationStatus",
  fetch_remote: "repositoryMutationOutcome",
  read_push_preview: "pushPreview",
  read_push_file_commit: "nullableCommitDetails",
  pull_current: "repositoryMutationOutcome",
  push_current: "repositoryMutationOutcome",
  cancel_remote_operation: "void",
  read_git_operation: "nullableGitOperationSnapshot",
  prepare_git_operation: "gitOperationPlan",
  execute_git_operation: "repositoryMutationOutcome",
  run_git_operation_action: "repositoryMutationOutcome",
  read_conflict_content: "gitConflictContent",
  resolve_conflict: "gitOperationMutationOutcome",
};

