import { commandId } from "./command-service.ts";

export const WORKBENCH_COMMANDS = {
  commandPalette: commandId("workbench.commandPalette.open"),
  openRepository: commandId("workspace.repository.open"),
  toggleRepositoryMenu: commandId("workspace.repository.menu.toggle"),
  quickOpen: commandId("workspace.quickOpen.open"),
  recentFiles: commandId("workspace.recentFiles.open"),
  workspaceSearch: commandId("workspace.search.open"),
  editorFind: commandId("editor.find.open"),
  historyFind: commandId("history.find.focus"),
  saveFile: commandId("editor.file.save"),
  refresh: commandId("workbench.refresh"),
  openSettings: commandId("workbench.settings.open"),
  closeSettings: commandId("workbench.settings.close"),
  toggleFiles: commandId("workbench.tool.files.toggle"),
  toggleSearch: commandId("workbench.tool.search.toggle"),
  toggleChanges: commandId("workbench.tool.changes.toggle"),
  toggleGit: commandId("workbench.tool.branches.toggle"),
  toggleStash: commandId("workbench.tool.stash.toggle"),
  toggleTerminal: commandId("workbench.tool.terminal.toggle"),
  hideLeftTool: commandId("workbench.tool.left.hide"),
  hideBottomTool: commandId("workbench.tool.bottom.hide"),
  dismissNotification: commandId("workbench.notification.dismiss"),
} as const;
