import type { EffectiveLocale } from "../presentation/presentation-environment.ts";
import type { ChangeKind } from "../models.ts";

export interface CommonCopy {
  ready: string;
  operationFailed: string;
  cancel: string;
  close: string;
  retry: string;
  planned: string;
  available: string;
}

export interface ShellCopy {
  projectMenu: string;
  openProject: string;
  noProject: string;
  projectMenuFor(name: string): string;
  openProjectMenu: string;
  open: string;
  recentProjects: string;
  noOtherRecentProjects: string;
  browserDemo: string;
  search: string;
  searchFilesAndCommands: string;
  remoteActions: string;
  remoteForActions: string;
  noRemote: string;
  fetchBranch: string;
  updateBranch: string;
  pushBranch: string;
  cancelRemote: string;
  refreshProject: string;
  refreshShortcut: string;
  openSettings: string;
  settings: string;
  windowControls: string;
  minimizeWindow: string;
  minimize: string;
  maximizeWindow: string;
  maximize: string;
  restoreWindow: string;
  restore: string;
  closeWindow: string;
  toolWindows: string;
  version(name: string, version: string): string;
  files: string;
  branches: string;
  changes: string;
  toolReorder(label: string): string;
  openFolderFirst: string;
  gitUnavailableReorder: string;
  genericTool: string;
  leftToolWindow: string;
  hideFiles: string;
  hideChanges: string;
  waitingForProject: string;
  resizeLeft: string;
  editor: string;
  welcome: string;
  showOpenFiles: string;
  openFiles: string;
  editorName(name: string): string;
  openFolder: string;
  openFolderDetail: string;
  resizeGit: string;
  branchesAndLog: string;
  prepareGitOperation: string;
  gitOperations: string;
  recoverChanges: string;
  hideGit: string;
  commitLog: string;
  gitDetails: string;
  resizeBranchTree: string;
  resizeGitDetails: string;
  returnToWorkbench: string;
  backToWorkbench: string;
  settingsGroups: string;
  currentEncoding: string;
  dismissError: string;
  selectCommitOrBranch: string;
  inspectorDetail: string;
  simulateOpenFolder: string;
  demoFolderDetail: string;
  projectFolderPath: string;
  openProjectAction: string;
  whereOpenProject: string;
  targetWindowDetail: string;
  cancelOpeningProject: string;
  currentWindow: string;
  newWindow: string;
  folder: string;
  gitUnavailable: string;
  detachedAt(oid: string): string;
  noBranch: string;
  openingProject: string;
  refreshingRepository: string;
  refreshingProjectFiles: string;
}

export interface SettingsCopy {
  planned: string;
  available: string;
  sections: Record<"general" | "appearance" | "editor" | "version-control" | "code", string>;
  generalTitle: string;
  generalDescription: string;
  languageLabel: string;
  languageDescription: string;
  languageSystem: string;
  languageEnglish: string;
  languageChinese: string;
  appearanceTitle: string;
  appearanceDescription: string;
  themeLabel: string;
  themeDescription: string;
  themeSystem: string;
  themeDark: string;
  themeLight: string;
  applicationFontLabel: string;
  applicationFontDescription: string;
  applicationFontAria: string;
  editorTitle: string;
  editorDescription: string;
  editorFontLabel: string;
  editorFontDescription: string;
  editorFontSizeLabel: string;
  editorFontSizeDescription: string;
  editorFontSizeAria: string;
  lineSpacingLabel: string;
  lineSpacingDescription: string;
  lineSpacingAria: string;
  letterSpacingLabel: string;
  letterSpacingDescription: string;
  letterSpacingAria: string;
  defaultPixels(value: number): string;
  indentLabel: string;
  indentDescription: string;
  indentAria: string;
  spaces(value: number): string;
  tabWidthLabel: string;
  tabWidthDescription: string;
  tabWidthAria: string;
  versionControlTitle: string;
  versionControlDescription: string;
  diffLayoutLabel: string;
  diffLayoutDescription: string;
  diffLayoutAria: string;
  sideBySide: string;
  unified: string;
  whitespaceLabel: string;
  whitespaceDescription: string;
  showWhitespace: string;
  codeTitle: string;
  codeDescription: string;
  syntaxHighlighting: string;
  syntaxDescription: string;
  formatting: string;
  formattingDescription: string;
  includedWithApp: string;
  downloadingFont(label: string): string;
  downloadedFont: string;
  uncachedFont: string;
  cachedFont: string;
  fontReady: string;
  retryFont(label: string): string;
  editorFontAria: string;
}

export type NavigationCommandId =
  | "open-repository"
  | "go-file"
  | "recent-files"
  | "find-workspace"
  | "find-current"
  | "save-current"
  | "refresh"
  | "toggle-files"
  | "toggle-changes"
  | "toggle-git";

export interface NavigationCopy {
  navigationMode: string;
  tabs: Record<"files" | "recent" | "workspace" | "commands", string>;
  titles: Record<"files" | "recent" | "workspace" | "commands", string>;
  hints: Record<"files" | "recent" | "workspace" | "commands", string>;
  close: string;
  useRegularExpressions: string;
  regularExpression: string;
  enter: string;
  enterToSearch: string;
  navigate: string;
  open: string;
  workspaceSearchOptions: string;
  include: string;
  includeAria: string;
  exclude: string;
  excludeAria: string;
  context: string;
  contextLines: string;
  replace: string;
  replacementText: string;
  previewReplace: string;
  reviewRecoveries(count: number): string;
  recoveryRecords(count: number): string;
  noMatchingCommands: string;
  broaderCommand: string;
  noRecentFiles: string;
  noMatchingFiles: string;
  recentFilesDetail: string;
  catalogLoading: string;
  fileQueryDetail: string;
  searchingProject: string;
  boundedSearchDetail: string;
  searchFailed: string;
  tryAgain: string;
  searchFileContents: string;
  searchInstructions: string;
  noSubsetMatches: string;
  noMatches: string;
  zeroWidthMatch: string;
  coverageMatches(count: number): string;
  coverageFiles(searched: number, catalog: number): string;
  coverageEligible(searched: number, eligible: number, catalog: number): string;
  coverageComplete: string;
  coveragePartial(reasons: string): string;
  coverageReasons: Record<"catalogTruncated" | "candidateLimit" | "byteLimit" | "matchLimit", string>;
  coverageSkipped(count: number): string;
  commands: Record<NavigationCommandId, { label: string; detail: string; aliases: string }>;
}

export interface ProjectFilesCopy {
  locateCurrentFile: string;
  expandSelectedFolder: string;
  collapseSelectedFolder: string;
  loadingProjectFiles: string;
  listFailed: string;
  tryAgain: string;
  refreshingFiles: string;
  boundedCatalog: string;
  projectFiles: string;
  fileCount(editable: number, ignored: number): string;
  collapsePath(path: string): string;
  expandPath(path: string): string;
  changeLabels: Record<ChangeKind, string>;
}

export interface EditorCopy {
  conflict: string;
  saving: string;
  unsaved: string;
  saved: string;
  close: string;
  closeFile(name: string): string;
  preview: string;
  diff: string;
  imagePreview: string;
  diffPreview: string;
  closePreview(label: string): string;
  welcome: string;
  markdownMode: string;
  source: string;
  sourceTitle: string;
  split: string;
  splitTitle: string;
  renderedPreview: string;
  previewTitle: string;
  diffToolbar: string;
  diffNavigation: string;
  previousChange: string;
  nextChange: string;
  previousFile: string;
  nextFile: string;
  openSource: string;
  collapseUnchanged: string;
  expandUnchanged: string;
  diffPresentation: string;
  unified: string;
  unifiedTitle: string;
  sideBySide: string;
  sideBySideTitle: string;
  whitespace: string;
  whitespaceTitle: string;
  imageAlt(label: string, path: string): string;
  renderingMarkdown: string;
  renderingMarkdownDetail: string;
  tryAgain: string;
  loadingImage: string;
  imageFailed: string;
  imageSurface: string;
  loadingImageDiff: string;
  imageDiffFailed: string;
  before: string;
  after: string;
  fileDidNotExist: string;
  fileRemoved: string;
  imageDiff: string;
  markdownSource: string;
  resizeMarkdown: string;
  markdownPreview: string;
  largePreviewPaused: string;
  largePreviewDetail(size: string, limit: number): string;
  markdownFailed: string;
  blockedImage: string;
  imagePlaceholder(label: string): string;
  linkUnavailable: string;
  workspaceReady: string;
  workspaceReadyDetail: string;
  loadingText: string;
  openTextFailed: string;
  fileLoadFailed: string;
  localChanges: string;
  loadingPatch: string;
  patchLoadFailed: string;
  noTextualDiff: string;
  loadingCommitPatch: string;
  currentEncoding(label?: string): string;
  ignoredNotOpened: string;
  outsideProjectTree: string;
  searchUnsaved: string;
  waitForLoad: string;
  openFileLimit: string;
  searchRefreshFailed: string;
  wrongWorkspace: string;
  invalidSearchLocation: string;
  staleSearchResult: string;
  waitForFileOperation: string;
  savedFile(path: string): string;
  newerEditsUnsaved: string;
  waitForSave: string;
  confirmCloseFile(path: string): string;
  cancelKeepsTab: string;
  noFileChange(direction: "next" | "previous"): string;
  noChangedFile(direction: "next" | "previous"): string;
  diffFileMissing: string;
  patchTruncated: string;
  externalDirtyConflict: string;
  externalUnavailable: string;
  unexpectedEditorError: string;
  unexpectedProjectFilesError: string;
}

export interface ReplacementCopy {
  safeWorkspaceEdit: string;
  preparingPreview: string;
  rereadingFiles: string;
  cancel: string;
  previewUnavailable: string;
  close: string;
  createNewSearch: string;
  sameSize: string;
  byteDelta(value: number): string;
  matches(count: number): string;
  blockedFile: string;
  comparisonFor(path: string): string;
  before: string;
  after: string;
  skippedFiles(count: number): string;
  reviewTitle: string;
  reviewedSummary(matches: number, files: number): string;
  selectAll: string;
  cancelAndRestore: string;
  applying: string;
  applySelection(matches: number, files: number): string;
  noPendingRecovery: string;
  backupsResolved: string;
  recoveryFileSummary(replaced: number, total: number, conflicts: number): string;
  readyToVerify: string;
  needsRecovery: string;
  restoring: string;
  rollBack: string;
  keeping: string;
  keepChanges: string;
  crashSafeHistory: string;
  recoveryTitle: string;
  recoveryDetail: string;
  fileStates: Record<"original" | "replaced" | "conflict" | "unavailable", string>;
  cancellationRequested: string;
  blockedPaths(paths: string): string;
  blockedStatus: string;
  stoppedAndRestored: string;
  appliedWithRecovery: string;
  needsReview: string;
  recoveryCount(count: number): string;
  inspectionFailed: string;
  rollbackBlocked(paths: string): string;
  externalChangesPreserved: string;
  changesKept: string;
  originalsRestored: string;
}

export interface LocaleCatalog {
  readonly locale: EffectiveLocale;
  readonly common: CommonCopy;
  readonly shell: ShellCopy;
  readonly settings: SettingsCopy;
  readonly navigation: NavigationCopy;
  readonly projectFiles: ProjectFilesCopy;
  readonly editor: EditorCopy;
  readonly replacement: ReplacementCopy;
  readonly editorPhrases: Readonly<Record<string, string>>;
  readonly documentDescription: string;
}
