import type { EffectiveLocale } from "../presentation/presentation-environment.ts";
import type { BranchMutationKind, ChangeKind, GitOperationAction, GitOperationKind } from "../models.ts";

export interface CommonCopy {
  ready: string;
  operationFailed: string;
  cancel: string;
  close: string;
  retry: string;
  planned: string;
  available: string;
  confirmSaveBefore(count: number, action: string): string;
  cancelKeepsWorkspace: string;
  actions: Record<"closeApp" | "switchRepositories" | "pullChanges" | "reviewGitOperation" | "createCommit" | "changeBranches", string>;
  prepareStrategy(strategy: string): string;
}

export interface ShellCopy {
  projectMenu: string;
  openProject: string;
  noProject: string;
  projectMenuFor(name: string): string;
  openProjectMenu: string;
  open: string;
  recentProjects: string;
  noOtherRecentProjects: string;
  removeRecentProject(name: string): string;
  browserDemo: string;
  search: string;
  searchFilesAndCommands: string;
  remoteActions: string;
  remoteForActions: string;
  noRemote: string;
  moreRemoteActions: string;
  fetchBranch: string;
  updateBranch: string;
  pushBranch: string;
  cancelRemote: string;
  refreshProject: string;
  refreshShortcut: string;
  openSettings: string;
  settings: string;
  windowControls: string;
  minimizeWindow: string;
  minimize: string;
  maximizeWindow: string;
  maximize: string;
  restoreWindow: string;
  restore: string;
  closeWindow: string;
  toolWindows: string;
  version(name: string, version: string): string;
  files: string;
  branches: string;
  changes: string;
  terminal: string;
  toolReorder(label: string): string;
  openFolderFirst: string;
  gitUnavailableReorder: string;
  genericTool: string;
  leftToolWindow: string;
  hideFiles: string;
  hideChanges: string;
  waitingForProject: string;
  resizeLeft: string;
  editor: string;
  welcome: string;
  showOpenFiles: string;
  openFiles: string;
  editorName(name: string): string;
  openFolder: string;
  openFolderDetail: string;
  resizeGit: string;
  branchesAndLog: string;
  prepareGitOperation: string;
  gitOperations: string;
  recoverChanges: string;
  hideGit: string;
  hideTerminal: string;
  commitLog: string;
  gitDetails: string;
  resizeBranchTree: string;
  resizeGitDetails: string;
  returnToWorkbench: string;
  backToWorkbench: string;
  settingsGroups: string;
  currentEncoding: string;
  dismissError: string;
  selectCommitOrBranch: string;
  inspectorDetail: string;
  simulateOpenFolder: string;
  demoFolderDetail: string;
  projectFolderPath: string;
  openProjectAction: string;
  whereOpenProject: string;
  targetWindowDetail: string;
  cancelOpeningProject: string;
  currentWindow: string;
  newWindow: string;
  folder: string;
  gitUnavailable: string;
  detachedAt(oid: string): string;
  noBranch: string;
  openingProject: string;
  refreshingRepository: string;
  refreshingProjectFiles: string;
  projectOpenedInNewWindow: string;
  projectFocusedInExistingWindow: string;
}

export interface TerminalCopy {
  notRunning: string;
  starting: string;
  running: string;
  started(shell: string): string;
  exited(code: number): string;
  failed: string;
  newSession: string;
  clear: string;
  cleared: string;
  close: string;
  closed: string;
}

export interface SettingsCopy {
  planned: string;
  available: string;
  sections: Record<"general" | "appearance" | "editor" | "version-control" | "code", string>;
  generalTitle: string;
  generalDescription: string;
  languageLabel: string;
  languageDescription: string;
  languageSystem: string;
  languageEnglish: string;
  languageChinese: string;
  appearanceTitle: string;
  appearanceDescription: string;
  themeLabel: string;
  themeDescription: string;
  themeSystem: string;
  themeDark: string;
  themeLight: string;
  applicationFontLabel: string;
  applicationFontDescription: string;
  applicationFontAria: string;
  editorTitle: string;
  editorDescription: string;
  editorFontLabel: string;
  editorFontDescription: string;
  editorFontSizeLabel: string;
  editorFontSizeDescription: string;
  editorFontSizeAria: string;
  lineSpacingLabel: string;
  lineSpacingDescription: string;
  lineSpacingAria: string;
  letterSpacingLabel: string;
  letterSpacingDescription: string;
  letterSpacingAria: string;
  defaultPixels(value: number): string;
  indentLabel: string;
  indentDescription: string;
  indentAria: string;
  spaces(value: number): string;
  tabWidthLabel: string;
  tabWidthDescription: string;
  tabWidthAria: string;
  versionControlTitle: string;
  versionControlDescription: string;
  updateStrategyLabel: string;
  updateStrategyDescription: string;
  updateStrategyAria: string;
  updateStrategies: Record<"ffOnly" | "merge" | "rebase", string>;
  askBeforeRemoteUpdateLabel: string;
  askBeforeRemoteUpdateDescription: string;
  askBeforeRemoteUpdate: string;
  diffLayoutLabel: string;
  diffLayoutDescription: string;
  diffLayoutAria: string;
  sideBySide: string;
  unified: string;
  whitespaceLabel: string;
  whitespaceDescription: string;
  showWhitespace: string;
  codeTitle: string;
  codeDescription: string;
  syntaxHighlighting: string;
  syntaxDescription: string;
  formatting: string;
  formattingDescription: string;
  includedWithApp: string;
  downloadingFont(label: string): string;
  downloadedFont: string;
  uncachedFont: string;
  cachedFont: string;
  fontReady: string;
  retryFont(label: string): string;
  editorFontAria: string;
}

export type NavigationCommandId =
  | "open-repository"
  | "go-file"
  | "recent-files"
  | "find-workspace"
  | "find-current"
  | "save-current"
  | "refresh"
  | "toggle-files"
  | "toggle-changes"
  | "toggle-git"
  | "toggle-terminal";

export interface NavigationCopy {
  navigationMode: string;
  tabs: Record<"files" | "recent" | "workspace" | "commands", string>;
  titles: Record<"files" | "recent" | "workspace" | "commands", string>;
  hints: Record<"files" | "recent" | "workspace" | "commands", string>;
  close: string;
  useRegularExpressions: string;
  regularExpression: string;
  enter: string;
  enterToSearch: string;
  navigate: string;
  open: string;
  workspaceSearchOptions: string;
  include: string;
  includeAria: string;
  exclude: string;
  excludeAria: string;
  context: string;
  contextLines: string;
  replace: string;
  replacementText: string;
  previewReplace: string;
  reviewRecoveries(count: number): string;
  recoveryRecords(count: number): string;
  noMatchingCommands: string;
  broaderCommand: string;
  noRecentFiles: string;
  noMatchingFiles: string;
  recentFilesDetail: string;
  catalogLoading: string;
  fileQueryDetail: string;
  searchingProject: string;
  boundedSearchDetail: string;
  searchFailed: string;
  tryAgain: string;
  searchFileContents: string;
  searchInstructions: string;
  noSubsetMatches: string;
  noMatches: string;
  zeroWidthMatch: string;
  coverageMatches(count: number): string;
  coverageFiles(searched: number, catalog: number): string;
  coverageEligible(searched: number, eligible: number, catalog: number): string;
  coverageComplete: string;
  coveragePartial(reasons: string): string;
  coverageReasons: Record<"catalogTruncated" | "candidateLimit" | "byteLimit" | "matchLimit", string>;
  coverageSkipped(count: number): string;
  commands: Record<NavigationCommandId, { label: string; detail: string; aliases: string }>;
}

export interface ProjectFilesCopy {
  locateCurrentFile: string;
  expandSelectedFolder: string;
  collapseSelectedFolder: string;
  loadingProjectFiles: string;
  listFailed: string;
  tryAgain: string;
  refreshingFiles: string;
  boundedCatalog: string;
  projectFiles: string;
  fileCount(editable: number, ignored: number): string;
  collapsePath(path: string): string;
  expandPath(path: string): string;
  changeLabels: Record<ChangeKind, string>;
  contextMenu: {
    ariaLabel(path: string): string;
    newFile: string;
    cut: string;
    copy: string;
    paste: string;
    reveal: string;
    rename: string;
    copyPath: string;
    fileName: string;
    relativePath: string;
    absolutePath: string;
    gitHistory: string;
    trash: string;
    copiedFileName: string;
    copiedRelativePath: string;
    copiedAbsolutePath: string;
    clipboardUnavailable: string;
    revealedSelection: string;
    openedContainingFolder: string;
    readOnly: string;
    mutationBusy: string;
    clipboardEmpty: string;
    operationsUnavailable: string;
    gitUnavailable: string;
    noHistory: string;
    ambiguousHistory: string;
    nameLabel: string;
    choosePasteName: string;
    pasteNameDetail: string;
    cancel: string;
    working: string;
    confirmTrashTitle: string;
    confirmTrash: string;
    trashFileDetail(path: string): string;
    trashFolderDetail(entries: number, bytes: number, hidden: number): string;
    invalidName: string;
    unsafeSource: string;
    sourceChanged: string;
    trashBlocked: string;
    destinationExists: string;
    operationFailed: string;
    copiedEntry: string;
    cutEntry: string;
    createdFile: string;
    renamedEntry: string;
    pastedEntry: string;
    trashedEntry: string;
  };
}

export interface EditorCopy {
  conflict: string;
  saving: string;
  unsaved: string;
  saved: string;
  close: string;
  closeFile(name: string): string;
  preview: string;
  diff: string;
  imagePreview: string;
  diffPreview: string;
  historical: string;
  historicalPreview: string;
  historicalReadOnly: string;
  loadingHistoricalFile: string;
  historicalFileFailed: string;
  historicalComparison: string;
  loadingHistoricalComparison: string;
  historicalComparisonFailed: string;
  currentDiskVersion: string;
  currentUnsavedVersion: string;
  historicalComparisonBlameUnavailable: string;
  closePreview(label: string): string;
  welcome: string;
  markdownMode: string;
  source: string;
  sourceTitle: string;
  split: string;
  splitTitle: string;
  renderedPreview: string;
  previewTitle: string;
  diffToolbar: string;
  diffNavigation: string;
  previousChange: string;
  nextChange: string;
  previousFile: string;
  nextFile: string;
  openSource: string;
  collapseUnchanged: string;
  expandUnchanged: string;
  diffPresentation: string;
  unified: string;
  unifiedTitle: string;
  sideBySide: string;
  sideBySideTitle: string;
  whitespace: string;
  whitespaceTitle: string;
  imageAlt(label: string, path: string): string;
  renderingMarkdown: string;
  renderingMarkdownDetail: string;
  tryAgain: string;
  loadingImage: string;
  imageFailed: string;
  imageSurface: string;
  loadingImageDiff: string;
  imageDiffFailed: string;
  before: string;
  after: string;
  fileDidNotExist: string;
  fileRemoved: string;
  imageDiff: string;
  markdownSource: string;
  resizeMarkdown: string;
  markdownPreview: string;
  largePreviewPaused: string;
  largePreviewDetail(size: string, limit: number): string;
  markdownFailed: string;
  blockedImage: string;
  imagePlaceholder(label: string): string;
  linkUnavailable: string;
  workspaceReady: string;
  workspaceReadyDetail: string;
  loadingText: string;
  openTextFailed: string;
  fileLoadFailed: string;
  localChanges: string;
  loadingPatch: string;
  patchLoadFailed: string;
  noTextualDiff: string;
  loadingCommitPatch: string;
  currentEncoding(label?: string): string;
  ignoredReadOnly: string;
  outsideProjectTree: string;
  gutterActions: string;
  annotateGitBlame: string;
  hideGitBlame: string;
  loadingGitBlame: string;
    gitBlameLocal: string;
    gitBlameRequiresGit: string;
    gitBlameRequiresSavedFile: string;
    gitBlameRequiresTrackedFile: string;
    gitBlameRequiresSplit: string;
  gitBlameFileUnavailable: string;
  gitBlameLoaded(lines: number): string;
  gitBlameLimited(lines: number): string;
  gitBlameHidden: string;
  gitBlameDetails(author: string, email: string, date: string, oid: string, summary: string): string;
  searchUnsaved: string;
  waitForLoad: string;
  openFileLimit: string;
  searchRefreshFailed: string;
  wrongWorkspace: string;
  invalidSearchLocation: string;
  staleSearchResult: string;
  waitForFileOperation: string;
  savedFile(path: string): string;
  newerEditsUnsaved: string;
  waitForSave: string;
  confirmCloseFile(path: string): string;
  cancelKeepsTab: string;
  noFileChange(direction: "next" | "previous"): string;
  noChangedFile(direction: "next" | "previous"): string;
  diffFileMissing: string;
  patchTruncated: string;
  externalDirtyConflict: string;
  externalUnavailable: string;
  unexpectedEditorError: string;
  unexpectedProjectFilesError: string;
}

export interface ReplacementCopy {
  safeWorkspaceEdit: string;
  preparingPreview: string;
  rereadingFiles: string;
  cancel: string;
  previewUnavailable: string;
  close: string;
  createNewSearch: string;
  sameSize: string;
  byteDelta(value: number): string;
  matches(count: number): string;
  blockedFile: string;
  comparisonFor(path: string): string;
  before: string;
  after: string;
  skippedFiles(count: number): string;
  reviewTitle: string;
  reviewedSummary(matches: number, files: number): string;
  selectAll: string;
  cancelAndRestore: string;
  applying: string;
  applySelection(matches: number, files: number): string;
  noPendingRecovery: string;
  backupsResolved: string;
  recoveryFileSummary(replaced: number, total: number, conflicts: number): string;
  readyToVerify: string;
  needsRecovery: string;
  restoring: string;
  rollBack: string;
  keeping: string;
  keepChanges: string;
  crashSafeHistory: string;
  recoveryTitle: string;
  recoveryDetail: string;
  fileStates: Record<"original" | "replaced" | "conflict" | "unavailable", string>;
  cancellationRequested: string;
  blockedPaths(paths: string): string;
  blockedStatus: string;
  stoppedAndRestored: string;
  appliedWithRecovery: string;
  needsReview: string;
  recoveryCount(count: number): string;
  inspectionFailed: string;
  rollbackBlocked(paths: string): string;
  externalChangesPreserved: string;
  changesKept: string;
  originalsRestored: string;
}

export interface ChangesCopy {
  contextMenu: {
    ariaLabel(path: string): string;
    includeInCommit: string;
    showDiff: string;
    jumpToSource: string;
    resolveConflict: string;
    restoreChanges: string;
    trash: string;
    copyPath: string;
    fileName: string;
    relativePath: string;
    absolutePath: string;
    gitHistory: string;
    included: string;
    excluded: string;
    copiedFileName: string;
    copiedRelativePath: string;
    copiedAbsolutePath: string;
    clipboardUnavailable: string;
    conflictsStayIncluded: string;
    sourceDeleted: string;
    sourceUnavailable: string;
    conflictUnavailable: string;
    restoreUnavailable: string;
    mutationBusy: string;
    operationsUnavailable: string;
    noHistory: string;
    targetChanged: string;
  };
  groups: Record<"changes" | "unversioned", string>;
  commitFileActions: string;
  refreshChanges: string;
  selectTrackedToRestore: string;
  restoreToHead: string;
  restoreChanges: string;
  openSelectedDiff: string;
  flatList: string;
  directoryTree: string;
  showAs(view: string): string;
  expandAll: string;
  collapseAll: string;
  checkingUntracked: string;
  trackedReady: string;
  untrackedFailed: string;
  refreshToRetry: string;
  workingTreeClean: string;
  noLocalChanges: string;
  changedFiles: string;
  includeAll(group: string): string;
  expand(label: string): string;
  collapse(label: string): string;
  fileCount(count: number): string;
  include(path: string): string;
  selectedDiff(path: string, selected: boolean): string;
  includeInCommit(path: string): string;
  resolveConflict(path: string): string;
  resolve: string;
  untrackedScanFailed: string;
  scanningUntracked: string;
  changeLabels: Record<ChangeKind, string>;
  changedFileCount(count: number): string;
  resizeCommit: string;
  createCommit: string;
  commitMessage: string;
  commitButton: string;
  commitAndPushButton: string;
  resolveBeforeCommit: string;
  excludeSubmodules: string;
  selectFileToCommit: string;
  saveBeforeRevert: string;
  restoreConfirm(label: string): string;
  restoreAddedConfirm(label: string): string;
  saveBeforeRestore: string;
  reverting: string;
  reverted: string;
  filesSavedReview: string;
  creatingCommit: string;
  commitConcurrent: string;
  commitRefreshing: string;
  commitCreated: string;
  commitAndPushUnavailable(reason: string): string;
  commitCreatedPushUnavailable(reason: string): string;
  patchTruncated: string;
  unexpectedError: string;
  fileSavedRefreshFailed: string;
}

export interface GitOperationCopy {
  activeOperation: string;
  unresolvedFiles(count: number): string;
  readyToContinue: string;
  names: Record<GitOperationKind, string>;
  actions: Record<GitOperationAction, string>;
  prepare(name: string): string;
  operation: string;
  setupOptions: Record<"merge" | "cherryPick" | "rebase" | "squash" | "revert", string>;
  targetsForCherryPick: string;
  targetBeforeSquash: string;
  targetRef: string;
  targetLinesPlaceholder: string;
  newCommitMessage: string;
  squashMessagePlaceholder: string;
  exactReviewNote: string;
  preparing: string;
  review: string;
  reviewTitle: string;
  planUnavailable: string;
  confirm(name: string): string;
  squashWarning: string;
  conflictWarning: string;
  currentBranch: string;
  reviewedOperation: string;
  exactTargets: string;
  commitMessage: string;
  back: string;
  running: string;
  openConflict: string;
  readingConflict: string;
  conflictUnavailable: string;
  resolve(path: string): string;
  conflictInputs: string;
  base: string;
  ours: string;
  theirs: string;
  resolvedResult: string;
  binaryConflict: string;
  resolvedFileContent: string;
  resolveSafetyNote: string;
  resolveAsDeleted: string;
  resolving: string;
  saveAndStage: string;
  closeDialog: string;
  notPresent: string;
  loadingReview: string;
  discardConflict: string;
  cancel: string;
  unavailableForFolder: string;
  alreadyInProgress(name: string): string;
  saveBeforeReview: string;
  saveBeforeChangingActive: string;
  inProgress(name: string): string;
  completed(name: string): string;
  actionInProgress(action: string): string;
  aborted: string;
  skippedCommit: string;
  continued: string;
  resolvingPath(path: string): string;
  resolvedAndStaged(path: string): string;
  paused(name: string): string;
  conflictPaused: string;
  conflictChangedExternally: string;
  operationFailed: string;
}

export interface RecoveryCopy {
  title: string;
  close: string;
  loading: string;
  noneAvailable: string;
  undoOperation: string;
  confirmUndo(operation: string, paths: string): string;
  incomplete(backupPath: string): string;
  waitForOperation: string;
  saveBeforeRestore: string;
  restoring: string;
  restored: string;
}

export interface RemoteCopy {
  unsupported: string;
  noRemote: string;
  noBranch: string;
  noCheckedOutBranch: string;
  noUpstream: string;
  selectedRemoteScope(remote: string): string;
  unavailable(detail: string): string;
  cancelOperation(kind: string, branch: string, remote: string): string;
  cancelRemoteOperation: string;
  actionNames: Record<"fetch" | "pull" | "push", string>;
  selectionUnavailable: string;
  fetchUnavailable: string;
  updateUnavailable: string;
  pushUnavailable: string;
  actionStateChanged(action: string): string;
  workbenchBusy: string;
  fetchDescription(remote: string, behind: number): string;
  updateDescription(source: string, remote: string, destination: string): string;
  pushDescription(source: string, remote: string, destination: string, ahead: number): string;
  strategies: Record<"ffOnly" | "merge" | "rebase", string>;
  cancelling: string;
  updating: string;
  update: string;
  fetchAndReview(strategy: string): string;
  currentBranch: string;
  updateBranch(branch: string): string;
  cancelUpdateConfirmation: string;
  updateDescriptionText: string;
  updateRoute: string;
  updateMethod: string;
  fastForwardOnly: string;
  fastForwardDetail: string;
  mergeIncoming: string;
  mergeIncomingDetail: string;
  rebaseCurrent: string;
  rebaseCurrentDetail: string;
  updateSafetyNote: string;
  dontAskAgain: string;
  cancelUpdate: string;
  updateFastForwardAria(source: string, remote: string, destination: string): string;
  updateReviewAria(remote: string, strategy: string, destination: string, source: string): string;
  readingPushPreview: string;
  pushPreviewUnavailable: string;
  route(source: string, remote: string, destination: string): string;
  selectedRoute: string;
  forcePushWithLease: string;
  publish: string;
  push: string;
  tags(count: number): string;
  noMatchingTags: string;
  pushCommitsTo(branch: string): string;
  currentBranchFallback: string;
  cancelPushConfirmation: string;
  pushReviewDescription: string;
  forcePushNote: string;
  ordinaryPushNote: string;
  tagsAndRetryNote: string;
  pushTags: string;
  tagScope: string;
  all: string;
  refreshingReview: string;
  cancelPush: string;
  pushing: string;
  checkingAuthentication: string;
  authenticationTitle(host: string): string;
  authenticationDescription(remote: string): string;
  httpsCredentialTitle: string;
  passwordUnsupported: string;
  username: string;
  usernamePlaceholder: string;
  personalAccessToken: string;
  tokenPlaceholder: string;
  credentialStorageNotice: string;
  credentialHelperMissing: string;
  credentialHelperUnavailable: string;
  saveCredentialAndPush: string;
  savingCredential: string;
  sshCredentialTitle: string;
  sshCredentialDescription: string;
  sshUrl: string;
  sshUrlPlaceholder: string;
  configureSshAndPush: string;
  configuringSsh: string;
  sshIdentityMissing: string;
  recheckAuthentication: string;
  authenticationFieldsRequired: string;
  credentialNotRetained: string;
  sshUrlRequired: string;
  invalidSshUrl: string;
  pushConfirmationAria(action: string, commits: number, tags: number, route: string): string;
  choosePushMode: string;
  pushMode: string;
  ordinaryNonForce: string;
  forceLeaseDetail: string;
  pushRouteAria(branch: string, destination: string): string;
  showAllOutgoingFiles: string;
  localBranch: string;
  outgoingCommitCount(count: number): string;
  showAllFiles: string;
  remoteBranch: string;
  pushRemote: string;
  selectedDestination: string;
  noNewCommitObjects: string;
  publishCreatesDestination: string;
  filesInSelectedCommit: string;
  filesInAllCommits: string;
  outgoingCommits: string;
  outgoingListAria: string;
  loading: string;
  showMore: string;
  truncatedCommits(total: string): string;
  readingSelectedFiles: string;
  pushedRangeExceeded: string;
  noSelectedCommitFiles: string;
  noNetFileChanges: string;
  pushedFileToolbar: string;
  openOutgoingDiff: string;
  showPushedFilesAs(view: string): string;
  flatList: string;
  folderTree: string;
  expandPushedFolders: string;
  collapsePushedFolders: string;
  loadingPushedDiff: string;
  closePushedDiff: string;
  pushedDiffToolbar: string;
  previousPushedFile: string;
  nextPushedFile: string;
  imagePreviewAlt(label: string): string;
  upstreamChanged: string;
  alreadyUpToDate: string;
  activeProjectNotGit: string;
  endedRefreshRequired: string;
  operationInProgress(name: string): string;
  operationCompleted(name: string): string;
  operationNeedsReview: string;
  cancellingOperation(name: string): string;
  branchOrRemoteChanged: string;
  noOutgoingCommitForFile(path: string): string;
  selectedOutgoingFileMissing: string;
  unexpectedError: string;
  policy: {
    finishActive(name: string): string;
    selectConfigured: string;
    unsupportedFetch: string;
    refreshRefs(remote: string): string;
    requireBranch: string;
    publishOrConfigure: string;
    selectUpstream: string;
    selectNamedUpstream(name: string): string;
    unsupportedUpstream: string;
    waitForScan: string;
    refreshAfterScanFailure: string;
    clearLocalChanges: string;
    reviewDivergence(ahead: number, behind: number): string;
    fastForward(count: number): string;
    checkUpstream: string;
    unsupportedPush: string;
    reviewOtherRemote(remote: string, upstream: string): string;
    createRemoteBranch(remote: string): string;
    publishBranch: string;
    behindOrDiverged: string;
    sendCommits(count: number, remote: string): string;
    noPendingCommits: string;
  };
}

export interface ErrorCopy {
  remoteCancelledUnknown: string;
  remoteCancelledChanged: string;
  remoteCancelled: string;
  remoteFailedFallback: string;
  authenticationFailed: string;
  networkFailed: string;
  remoteRejected: string;
  fileConflictPreserved: string;
  unexpectedOperation: string;
  watchUnavailable(detail?: string): string;
  watchStartFailed(detail: string): string;
  watchSuspended(): string;
  externalReconcileFailed(detail: string): string;
  translate(message: string): string;
}

export interface HistoryCopy {
  branchContextMenu: BranchContextMenuCopy;
  branchMutation: BranchMutationCopy;
  commitContextMenu: HistoryCommitContextMenuCopy;
  rangeContextMenu: HistoryCommitRangeContextMenuCopy;
  commitFolderContextMenu: HistoryCommitFolderContextMenuCopy;
  commitFileContextMenu: HistoryCommitFileContextMenuCopy;
  rangeSelectionLimit: string;
  rangeSelectionBarrier: string;
  comparisonTitle: string;
  comparisonFileRange: string;
  swapComparisonSides: string;
  comparisonBefore: string;
  comparisonAfter: string;
  comparisonDivergent: string;
  comparisonRelated: string;
  comparisonReversed: string;
  couldNotLoadComparison: string;
  noComparisonChanges: string;
  comparisonAria(before: string, after: string): string;
  noRefs: string;
  refsAppearHere: string;
  branchOrTag: string;
  filterBranchesAndTags: string;
  noMatchingRefs: string;
  tryAnotherRef: string;
  groups: Record<"local" | "remote" | "tag", string>;
  activateAgainForAllRefs: string;
  roots(count: number): string;
  allRefs: string;
  allRefsTitle: string;
  upToCommit(shortOid: string): string;
  historyStartsAt(shortOid: string, repositoryId: string): string;
  branchCount(count: number): string;
  textOrHash: string;
  filterCommitHistory: string;
  useRegularExpression: string;
  matchCase: string;
  queryFilters: string;
  filterByAuthor: string;
  filterByDate: string;
  filterByPathsOrRoots: string;
  graphOptions: string;
  select: string;
  recent: string;
  favorites: string;
  allUsers: string;
  identity: string;
  me: string;
  loadedAuthors: string;
  allDates: string;
  last24Hours: string;
  last7Days: string;
  selectInTree: string;
  rootsLabel: string;
  loadingTrackedPaths: string;
  trackedPathsFailed: string;
  boundedTree: string;
  keepOneRoot: string;
  includeRootHistory(name: string): string;
  sort: string;
  byCommitDate: string;
  topologically: string;
  options: string;
  firstParent: string;
  noMerges: string;
  branchActions: string;
  expandLinearBranches: string;
  collapseLinearBranches: string;
  pathsCount(count: number): string;
  rootsCount(count: number): string;
  paths: string;
  user: string;
  userCount(count: number): string;
  date: string;
  hours24: string;
  days7: string;
  loadingFilteredHistory: string;
  couldNotLoadHistory: string;
  queryCouldNotBeRead: string;
  noCommitsForFilters: string;
  clearFilters: string;
  invalidExpression(error: string, showingUnfiltered: boolean): string;
  noMatchingCommits: string;
  tryCommitSearch: string;
  expandLinearTitle(count: number): string;
  linearCommitsCollapsed(count: number): string;
  expand: string;
  gitRoot(path: string): string;
  commitHistory: string;
  loadingOlderCommits: string;
  showingNewestLimit(count: string): string;
  scrollForOlder: string;
  allHistoryLoaded(count: string, singular: boolean): string;
  noOlderCommits: string;
  olderCommitsFailed(detail: string): string;
  historyRefreshFailed(detail: string): string;
  historyRefreshWarning: string;
  filteredHistoryWarning: string;
  rootCommit: string;
  outgoingCommit: string;
  oneParent: string;
  mergeParents(count: number): string;
  collapsedGraphLane(lane: number, total: number): string;
  graphLane(lane: number, total: number, parentSummary: string): string;
  state: string;
  upstream: string;
  tracking: string;
  updated: string;
  checkedOut: string;
  none: string;
  noDivergence: string;
  operationsUsing(name: string): string;
  mergeIntoCurrent: string;
  rebaseCurrentOnto: string;
  checkout: string;
  currentBranch: string;
  checkoutBranch(name: string): string;
  checkoutBlocked: string;
  localBranchesOnly: string;
  submoduleHistoryOnly: string;
  selectLocalBranch: string;
  submoduleReadOnly: string;
  moreBlockers(count: number): string;
  changedPathsBlock(count: number): string;
  checkingUntrackedForBranch: string;
  untrackedCheckFailedForBranch: string;
  cleanWorktreeVerified: string;
  newLocalBranch: string;
  createFromHead: string;
  branchName: string;
  createAndCheckout: string;
  details: string;
  nothingSelected: string;
  selectToInspect: string;
  changedFiles: string;
  files: string;
  flatList: string;
  directoryTree: string;
  showChangedFilesAs(view: string): string;
  expandChangedFolders: string;
  collapseChangedFolders: string;
  resizeCommitDetails: string;
  loadingChangedFiles: string;
  couldNotLoadCommit: string;
  noFirstParentChanges: string;
  changedFilesByDirectory: string;
  fileCount(count: number): string;
  operationsUsingCommit: string;
  cherryPick: string;
  squashAfterThis: string;
  commitMessageAndDetails: string;
  authoredOn: string;
  emptyTree: string;
  noNamedRefs: string;
  refsSummary(count: number, summary: string): string;
  showAll: string;
  firstParentComparison: string;
  comparedWith(value: string): string;
  unknownTime: string;
  referenceKinds: Record<"head" | "local" | "remote" | "tag" | "other", string>;
  countOfCommits(filtered: string, total: string, scope: string): string;
  refreshing: string;
  logicalRefsCount(visible: string, total: string): string;
  applyCount(count: string): string;
  selectBranchesOrTags: string;
  noMatchingBranchesOrTags: string;
  availableBranchesAndTags: string;
  addToFavorites: string;
  removeFromFavorites: string;
  clear: string;
  apply: string;
  all: string;
  selectPathsToFilter: string;
  pathTextHelp: string;
  trackedRepositoryPaths: string;
  noTrackedPaths: string;
  unknownTrackedPath(path: string): string;
  ambiguousTrackedPath(path: string): string;
  expandPath(path: string): string;
  collapsePath(path: string): string;
  checkingOut(name: string): string;
  checkedOutBranch(name: string): string;
  creatingBranch(name: string): string;
  createdBranch(name: string): string;
}

export interface BranchContextMenuCopy {
  ariaLabel(name: string): string;
  viewHistory: string;
  switchTo(name: string): string;
  checkoutRemote: string;
  newBranchFrom: string;
  mergeIntoCurrent: string;
  rebaseCurrentOnto: string;
  update: string;
  push: string;
  rename: string;
  copyBranch: string;
  shortName: string;
  fullReference: string;
  deleteLocal: string;
  copiedShort: string;
  copiedFull: string;
  clipboardUnavailable: string;
  busy: string;
  cleanRequired: string;
  targetChanged: string;
}

export interface BranchMutationCopy {
  eyebrow: string;
  titles: Record<BranchMutationKind, string>;
  descriptions: Record<BranchMutationKind, string>;
  actions: Record<BranchMutationKind, string>;
  progress(kind: BranchMutationKind, source: string): string;
  completed(kind: BranchMutationKind, source: string, destination: string | null): string;
  source: string;
  object: string;
  destination: string;
  currentHead: string;
  upstream: string;
  noUpstream: string;
  mergedIntoCurrent: string;
  localOnly: string;
  branchName: string;
  branchNameRequired: string;
  review: string;
  reviewing: string;
  back: string;
  cancel: string;
  working: string;
  failed: string;
}

export interface HistoryCommitContextMenuCopy {
  ariaLabel(subject: string): string;
  copyCommitId: string;
  cherryPick: string;
  revertCommit: string;
  newBranchFromCommit: string;
  copiedCommitId: string;
  clipboardUnavailable: string;
  busy: string;
  cleanRequired: string;
  localBranchRequired: string;
  mergeMainlineRequired: string;
  targetChanged: string;
}

export interface HistoryCommitRangeContextMenuCopy extends HistoryCommitRangePolicyCopy {
  ariaLabel(count: number): string;
  copyCommitIds: string;
  compareTwoCommits: string;
  cherryPickSelected: string;
  revertSelected: string;
  squashSelected: string;
  copiedCommitIds(count: number): string;
  clipboardUnavailable: string;
  targetChanged: string;
}

export interface HistoryCommitFolderContextMenuCopy {
  ariaLabel(path: string): string;
  showChanges: string;
  revealInFiles: string;
  historyUpToCommit: string;
  copyPath: string;
  folderName: string;
  relativePath: string;
  absolutePath: string;
  copiedFolderName: string;
  copiedRelativePath: string;
  copiedAbsolutePath: string;
  clipboardUnavailable: string;
  currentDirectoryUnavailable: string;
  targetChanged: string;
  folderChanges: string;
  projectedRangeDescription(count: number, formattedCount: string): string;
  commit: string;
  comparisonBase: string;
}

export interface HistoryCommitFileContextMenuCopy {
  ariaLabel(path: string): string;
  showDiff: string;
  openHistorical: string;
  compareCurrent: string;
  openCurrent: string;
  restore: string;
  historyUpToCommit: string;
  copyPath: string;
  fileName: string;
  relativePath: string;
  absolutePath: string;
  copiedFileName: string;
  copiedRelativePath: string;
  copiedAbsolutePath: string;
  clipboardUnavailable: string;
  currentFileUnavailable: string;
  saveBeforeRestore: string;
  waitForEditor: string;
  restoreBusy: string;
  targetChanged: string;
  restoreEyebrow: string;
  restoreTitle: string;
  recoveryTitle: string;
  restoreDescription: string;
  appliedDescription: string;
  recoveryDescription: string;
  preparing: string;
  target: string;
  source: string;
  action: string;
  size: string;
  mode: string;
  byteChange(before: number | null, after: number): string;
  workingTreeOnly: string;
  editorChanged: string;
  restoreActions: Record<"create" | "overwrite" | "unchanged", string>;
  recoveryStates: Record<"original" | "restored" | "conflict" | "unavailable", string>;
  noRecoveries: string;
  restoreNow: string;
  undo: string;
  keep: string;
  working: string;
  cancel: string;
  close: string;
}

export interface HistoryCommitRangePolicyCopy {
  busy: string;
  cleanRequired: string;
  localBranchRequired: string;
  sameRootRequired: string;
  topLevelRequired: string;
  linearRequired: string;
  mergeRequired: string;
  currentBranchRequired: string;
  headSuffixRequired: string;
  rootBaseRequired: string;
}

export interface LocaleCatalog {
  readonly locale: EffectiveLocale;
  readonly common: CommonCopy;
  readonly shell: ShellCopy;
  readonly terminal: TerminalCopy;
  readonly settings: SettingsCopy;
  readonly navigation: NavigationCopy;
  readonly projectFiles: ProjectFilesCopy;
  readonly editor: EditorCopy;
  readonly replacement: ReplacementCopy;
  readonly changes: ChangesCopy;
  readonly gitOperations: GitOperationCopy;
  readonly history: HistoryCopy;
  readonly recovery: RecoveryCopy;
  readonly remote: RemoteCopy;
  readonly errors: ErrorCopy;
  readonly editorPhrases: Readonly<Record<string, string>>;
  readonly documentDescription: string;
}
