import type { LocaleCatalog } from "./catalog.ts";

export const EN_US: LocaleCatalog = {
  locale: "en-US",
  common: {
    ready: "Ready",
    operationFailed: "Operation failed",
    cancel: "Cancel",
    close: "Close",
    retry: "Retry",
    planned: "Planned",
    available: "Available",
    confirmSaveBefore: (count, action) => `Save ${count} unsaved ${count === 1 ? "file" : "files"} before ${action}?`,
    cancelKeepsWorkspace: "Cancel keeps the current workspace open.",
    actions: { closeApp: "closing Asterlyn", switchRepositories: "switching repositories", pullChanges: "pulling changes", reviewGitOperation: "reviewing a Git operation", createCommit: "creating the commit", changeBranches: "changing branches" },
    prepareStrategy: (strategy) => `preparing ${strategy}`,
  },
  shell: {
    projectMenu: "Project menu",
    openProject: "Open a project",
    noProject: "No project",
    projectMenuFor: (name) => `Project menu for ${name}`,
    openProjectMenu: "Open project menu",
    open: "Open…",
    recentProjects: "Recent Projects",
    noOtherRecentProjects: "No other recent projects",
    browserDemo: "Browser demo",
    search: "Search",
    searchFilesAndCommands: "Search files and commands",
    remoteActions: "Current branch remote actions",
    remoteForActions: "Remote used by current branch actions",
    noRemote: "No remote",
    fetchBranch: "Fetch current branch",
    updateBranch: "Update current branch",
    pushBranch: "Push current branch",
    cancelRemote: "Cancel remote operation",
    refreshProject: "Refresh project",
    refreshShortcut: "Refresh (Ctrl/Cmd+R)",
    openSettings: "Open settings",
    settings: "Settings",
    windowControls: "Window controls",
    minimizeWindow: "Minimize window",
    minimize: "Minimize",
    maximizeWindow: "Maximize window",
    maximize: "Maximize",
    restoreWindow: "Restore window",
    restore: "Restore",
    closeWindow: "Close window",
    toolWindows: "Tool windows",
    version: (name, version) => `${name} version ${version}`,
    files: "Files",
    branches: "Branches",
    changes: "Changes",
    toolReorder: (label) => `${label} — drag to reorder`,
    openFolderFirst: "Open a project folder first — drag to reorder",
    gitUnavailableReorder: "Git is unavailable for this folder — drag to reorder",
    genericTool: "Tool window",
    leftToolWindow: "Left tool window",
    hideFiles: "Hide Files tool window",
    hideChanges: "Hide Changes tool window",
    waitingForProject: "Waiting for a project",
    resizeLeft: "Resize left tool window",
    editor: "Editor",
    welcome: "Welcome",
    showOpenFiles: "Show open files",
    openFiles: "Open files",
    editorName: (name) => `${name} Editor`,
    openFolder: "Open a project folder",
    openFolderDetail: "Browse ordinary folders, or use Git tools when the selected folder is a repository root.",
    resizeGit: "Resize Git tool window",
    branchesAndLog: "Branches and Log",
    prepareGitOperation: "Prepare a Merge, Cherry-pick, Rebase, or Squash operation",
    gitOperations: "Git operations…",
    recoverChanges: "Recover local changes",
    hideGit: "Hide Git tool window",
    commitLog: "Commit log",
    gitDetails: "Git details",
    resizeBranchTree: "Resize branch tree",
    resizeGitDetails: "Resize Git details",
    returnToWorkbench: "Return to workbench",
    backToWorkbench: "Back to workbench",
    settingsGroups: "Settings groups",
    currentEncoding: "Current file encoding",
    dismissError: "Dismiss error",
    selectCommitOrBranch: "Select a commit or branch",
    inspectorDetail: "Commit files and message details share this compact inspector.",
    simulateOpenFolder: "Simulate opening a project folder",
    demoFolderDetail: "Enter a sample path for browser-only interaction testing. This demo does not read that folder from your computer.",
    projectFolderPath: "Project folder path",
    openProjectAction: "Open project",
    whereOpenProject: "Where should this project open?",
    targetWindowDetail: "The current window already contains a project. Open the selected folder here or keep this workspace and open another window.",
    cancelOpeningProject: "Cancel opening project",
    currentWindow: "Current window",
    newWindow: "New window",
    folder: "Folder",
    gitUnavailable: "Git unavailable",
    detachedAt: (oid) => `Detached at ${oid}`,
    noBranch: "No branch",
    openingProject: "Opening project…",
    refreshingRepository: "Refreshing repository…",
    refreshingProjectFiles: "Refreshing project files…",
    projectOpenedInNewWindow: "Project opened in a new window",
  },
  settings: {
    planned: "Planned",
    available: "Available",
    sections: { general: "General", appearance: "Appearance", editor: "Editor", "version-control": "Version Control", code: "Code" },
    generalTitle: "General",
    generalDescription: "Application-wide behavior and presentation language.",
    languageLabel: "Application language",
    languageDescription: "Choose a fixed interface language or follow the operating system.",
    languageSystem: "System",
    languageEnglish: "English",
    languageChinese: "简体中文",
    appearanceTitle: "Appearance",
    appearanceDescription: "Interface color and application-menu typography.",
    themeLabel: "Theme",
    themeDescription: "Choose a fixed palette or follow the operating-system appearance.",
    themeSystem: "System",
    themeDark: "Dark",
    themeLight: "Light",
    applicationFontLabel: "Application menu font",
    applicationFontDescription: "Changes navigation, toolbar, tabs, settings, and status text without scaling the editor.",
    applicationFontAria: "Application menu font size",
    editorTitle: "Editor",
    editorDescription: "Shared defaults for text editors and source-aware Diff panes.",
    editorFontLabel: "Editor font",
    editorFontDescription: "JetBrains Mono is included. Other fonts download only when selected, pass an integrity check, and remain cached in this profile.",
    editorFontSizeLabel: "Editor font size",
    editorFontSizeDescription: "Applies immediately to text files and Diff code.",
    editorFontSizeAria: "Editor font size",
    lineSpacingLabel: "Line spacing",
    lineSpacingDescription: "Controls vertical code density without changing file content.",
    lineSpacingAria: "Editor line spacing",
    letterSpacingLabel: "Letter spacing",
    letterSpacingDescription: "Adjusts horizontal spacing between code glyphs. The editor default is represented by 0 px.",
    letterSpacingAria: "Editor letter spacing",
    defaultPixels: (value) => `Default · ${value} px`,
    indentLabel: "Indent size",
    indentDescription: "Sets the spaces inserted for one editor indentation level.",
    indentAria: "Editor indent size",
    spaces: (value) => `${value} spaces`,
    tabWidthLabel: "Tab width",
    tabWidthDescription: "Controls the visual width of an existing tab character without rewriting content.",
    tabWidthAria: "Editor tab width",
    versionControlTitle: "Version Control",
    versionControlDescription: "Defaults shared by working-tree and commit Diff views.",
    diffLayoutLabel: "Diff layout",
    diffLayoutDescription: "Choose the default presentation used by every Diff preview.",
    diffLayoutAria: "Default Diff layout",
    sideBySide: "Side by side",
    unified: "Unified",
    whitespaceLabel: "Whitespace",
    whitespaceDescription: "Show spaces and tabs in Diff panes.",
    showWhitespace: "Show whitespace characters",
    codeTitle: "Code",
    codeDescription: "Syntax and language-specific services are introduced only when their boundaries are real.",
    syntaxHighlighting: "Syntax highlighting",
    syntaxDescription: "CodeMirror language packages load on demand for editors and Diff panes.",
    formatting: "Per-language formatting",
    formattingDescription: "Formatter choice, style profiles, and format-on-save need the future language-service boundary.",
    includedWithApp: "Included with Asterlyn",
    downloadingFont: (label) => `Downloading and verifying ${label}…`,
    downloadedFont: "Downloaded, verified, and cached",
    uncachedFont: "Loaded for this window; local cache is unavailable",
    cachedFont: "Loaded from verified local cache",
    fontReady: "Ready in this window",
    retryFont: (label) => `Retry ${label}`,
    editorFontAria: "Editor font family",
  },
  navigation: {
    navigationMode: "Navigation mode",
    tabs: { files: "Files", recent: "Recent", workspace: "Text", commands: "Commands" },
    titles: {
      files: "Search project files", recent: "Filter recent files",
      workspace: "Search text in current project", commands: "Search available commands",
    },
    hints: {
      files: "Go to File · authorized project catalog",
      recent: "Recent Files · successful opens in this project",
      workspace: "Find in Files · bounded search · reviewed recoverable replacement",
      commands: "Command Palette · only currently safe commands are enabled",
    },
    close: "Close", useRegularExpressions: "Use regular expressions", regularExpression: "Regular expression",
    enter: "Enter", enterToSearch: "Enter to search", navigate: "Navigate", open: "Open",
    workspaceSearchOptions: "Workspace search options", include: "Include",
    includeAria: "Files to include, comma-separated full-path globs", exclude: "Exclude",
    excludeAria: "Files to exclude, comma-separated full-path globs", context: "Context", contextLines: "Context lines",
    replace: "Replace", replacementText: "Replacement text", previewReplace: "Preview Replace",
    reviewRecoveries: (count) => `Review ${count} replacement recoveries`,
    recoveryRecords: (count) => `${count} recovery ${count === 1 ? "record" : "records"}`,
    noMatchingCommands: "No matching commands", broaderCommand: "Try a broader command name.",
    noRecentFiles: "No recent files", noMatchingFiles: "No matching files",
    recentFilesDetail: "Files appear here after they open successfully.",
    catalogLoading: "The project catalog is still loading.", fileQueryDetail: "Try part of a filename or path.",
    searchingProject: "Searching current project…", boundedSearchDetail: "The scan is bounded and cancellable.",
    searchFailed: "Search could not complete", tryAgain: "Try again.", searchFileContents: "Search file contents",
    searchInstructions: "Enter a case-sensitive literal or regular expression, then press Enter. Replacement always requires a separate preview.",
    noSubsetMatches: "No matches in the searched subset", noMatches: "No matches", zeroWidthMatch: "Zero-width match",
    coverageMatches: (count) => `${count} matches`, coverageFiles: (searched, catalog) => `${searched}/${catalog} files`,
    coverageEligible: (searched, eligible, catalog) => `${searched}/${eligible} eligible · ${catalog} catalog`,
    coverageComplete: "complete", coveragePartial: (reasons) => `partial: ${reasons}`,
    coverageReasons: { catalogTruncated: "catalog limit", candidateLimit: "candidate limit", byteLimit: "byte limit", matchLimit: "match limit" },
    coverageSkipped: (count) => `${count} skipped`,
    commands: {
      "open-repository": { label: "Open Project", detail: "Choose a local folder", aliases: "open folder repository" },
      "go-file": { label: "Go to File", detail: "Open a project file by name", aliases: "quick open" },
      "recent-files": { label: "Recent Files", detail: "Reopen a successful file", aliases: "history" },
      "find-workspace": { label: "Find in Files", detail: "Bounded search with reviewed replacement", aliases: "workspace search replace" },
      "find-current": { label: "Find and Replace in Current File", detail: "Undoable changes stay in the active buffer", aliases: "search" },
      "save-current": { label: "Save Current File", detail: "Use the conflict-safe save path", aliases: "write" },
      refresh: { label: "Refresh Project", detail: "Reload project files and available Git state", aliases: "reload sync" },
      "toggle-files": { label: "Toggle Files", detail: "Show or hide the Files tool window", aliases: "project tree" },
      "toggle-changes": { label: "Toggle Changes", detail: "Show or hide the Changes tool window", aliases: "git status" },
      "toggle-git": { label: "Toggle Git", detail: "Show or hide Branches and Log", aliases: "history branches" },
    },
  },
  projectFiles: {
    locateCurrentFile: "Locate current file in project",
    expandSelectedFolder: "Expand selected folder",
    collapseSelectedFolder: "Collapse selected folder",
    loadingProjectFiles: "Loading project files…",
    listFailed: "Could not list project files",
    tryAgain: "Try again",
    refreshingFiles: "Refreshing files…",
    boundedCatalog: "Showing a bounded project catalog; some paths were omitted.",
    projectFiles: "Project files", fileCount: (editable, ignored) => `${editable} editable files and ${ignored} ignored entries`,
    collapsePath: (path) => `Collapse ${path}`,
    expandPath: (path) => `Expand ${path}`,
    changeLabels: {
      unmodified: "Unmodified", added: "Added", modified: "Modified", deleted: "Deleted", renamed: "Renamed",
      copied: "Copied", typeChanged: "Type changed", unmerged: "Unmerged", untracked: "Untracked",
      ignored: "Ignored", unknown: "Unknown",
    },
  },
  editor: {
    conflict: "Conflict", saving: "Saving", unsaved: "Unsaved", saved: "Saved", close: "Close",
    closeFile: (name) => `Close ${name}`, preview: "Preview", diff: "Diff", imagePreview: "Image preview", diffPreview: "Diff preview",
    closePreview: (label) => `Close ${label} preview`, welcome: "Welcome", markdownMode: "Markdown editor mode",
    source: "Source", sourceTitle: "Edit Markdown source", split: "Split", splitTitle: "Edit source with live preview",
    renderedPreview: "Preview", previewTitle: "Rendered preview (read-only)", diffToolbar: "Diff navigation and presentation",
    diffNavigation: "Diff navigation", previousChange: "Previous change in file", nextChange: "Next change in file",
    previousFile: "Previous changed file", nextFile: "Next changed file", openSource: "Open file and reveal in Project",
    collapseUnchanged: "Collapse unchanged lines", expandUnchanged: "Expand unchanged lines", diffPresentation: "Diff presentation",
    unified: "Unified", unifiedTitle: "Unified diff", sideBySide: "Split", sideBySideTitle: "Side-by-side diff",
    whitespace: "Whitespace", whitespaceTitle: "Show whitespace characters",
    imageAlt: (label, path) => `${label} image for ${path}`,
    renderingMarkdown: "Rendering Markdown…", renderingMarkdownDetail: "The editor remains available while the preview engine loads.",
    tryAgain: "Try again", loadingImage: "Loading image preview…", imageFailed: "Could not preview image", imageSurface: "Image preview",
    loadingImageDiff: "Loading image Diff…", imageDiffFailed: "Could not preview image Diff", before: "Before", after: "After",
    fileDidNotExist: "File did not exist", fileRemoved: "File was removed", imageDiff: "Image Diff",
    markdownSource: "Markdown source editor", resizeMarkdown: "Resize Markdown source and preview", markdownPreview: "Markdown preview",
    largePreviewPaused: "Preview paused for this large file",
    largePreviewDetail: (size, limit) => `The document is ${size} MiB. Live preview is limited to ${limit} MiB; source editing and saving remain available.`,
    markdownFailed: "Markdown preview failed", blockedImage: "Image preview blocked", imagePlaceholder: (label) => `[Image: ${label}]`,
    linkUnavailable: "Link opening is not available in preview", workspaceReady: "Editor workspace ready",
    workspaceReadyDetail: "Open a project file to edit it, or choose a changed or committed file to inspect its Diff.",
    loadingText: "Loading text file…", openTextFailed: "Could not open text file", fileLoadFailed: "The file could not be loaded.",
    localChanges: "Local changes", loadingPatch: "Loading patch…", patchLoadFailed: "Could not load patch",
    noTextualDiff: "No textual diff is available for this selection.", loadingCommitPatch: "Loading commit patch…",
    currentEncoding: (label) => label ? `Current file encoding: ${label}` : "Current file encoding",
    ignoredNotOpened: "Ignored entries are shown for context and are not opened",
    outsideProjectTree: "The current file is outside the bounded project tree",
    searchUnsaved: "Search location was not applied because this file has unsaved edits",
    waitForLoad: "Wait for the current file load, then run the search again",
    openFileLimit: "All 20 open files contain unsaved changes; save or close one before opening another",
    searchRefreshFailed: "Search location could not be refreshed safely", wrongWorkspace: "Search result belongs to another workspace",
    invalidSearchLocation: "Search location is no longer valid; run the search again", staleSearchResult: "Search result is stale; run the search again",
    waitForFileOperation: "Wait for the current file operation before continuing", savedFile: (path) => `Saved ${path}`,
    newerEditsUnsaved: "Saved captured changes; newer edits remain unsaved", waitForSave: "Wait for the file to finish saving",
    confirmCloseFile: (path) => `Save changes to ${path} before closing?`, cancelKeepsTab: "Cancel keeps the tab open.",
    noFileChange: (direction) => `No ${direction} change in this file`, noChangedFile: (direction) => `No ${direction} changed file`,
    diffFileMissing: "The current Diff file is not present in the project tree", patchTruncated: "Patch truncated at 4 MiB",
    externalDirtyConflict: "A file with unsaved edits changed outside Asterlyn. The local buffer was preserved.",
    externalUnavailable: "The file changed or became unavailable outside Asterlyn; its open buffer was preserved.",
    unexpectedEditorError: "Unexpected editor-session error", unexpectedProjectFilesError: "Unexpected project-files error",
  },
  replacement: {
    safeWorkspaceEdit: "Safe workspace edit", preparingPreview: "Preparing replacement preview",
    rereadingFiles: "Re-reading the Git-authorized files…", cancel: "Cancel", previewUnavailable: "Replacement preview unavailable",
    close: "Close", createNewSearch: "Create a new search and preview.", sameSize: "same size",
    byteDelta: (value) => `${value > 0 ? "+" : ""}${value} B`, matches: (count) => `${count} ${count === 1 ? "match" : "matches"}`,
    blockedFile: "save or unselect the open edited file", comparisonFor: (path) => `Before and after preview for ${path}`,
    before: "Before", after: "After", skippedFiles: (count) => `${count} unsupported or unreadable files remain outside this reviewed replacement.`,
    reviewTitle: "Review Replace in Files", reviewedSummary: (matches, files) => `${matches} reviewed replacements across ${files} files. Only checked files will change.`,
    selectAll: "Select all files", cancelAndRestore: "Cancel and restore", applying: "Applying safely…",
    applySelection: (matches, files) => `Replace ${matches} in ${files} ${files === 1 ? "file" : "files"}`,
    noPendingRecovery: "No pending replacement recovery", backupsResolved: "Reviewed backups have been resolved.",
    recoveryFileSummary: (replaced, total, conflicts) => `${replaced}/${total} files contain the reviewed replacement${conflicts ? ` · ${conflicts} need manual review` : ""}`,
    readyToVerify: "Ready to verify", needsRecovery: "Needs recovery", restoring: "Restoring…", rollBack: "Roll back",
    keeping: "Keeping…", keepChanges: "Keep changes", crashSafeHistory: "Crash-safe history", recoveryTitle: "Replacement recovery",
    recoveryDetail: "Backups remain until you verify and keep the reviewed changes, or restore the exact originals.",
    fileStates: { original: "Original", replaced: "Replaced", conflict: "Changed externally", unavailable: "Unavailable" },
    cancellationRequested: "Cancellation requested. Restoring any files already changed…",
    blockedPaths: (paths) => `Save, close, or unselect ${paths} before replacing.`, blockedStatus: "Replacement blocked by an open edited file",
    stoppedAndRestored: "Replacement stopped; every changed file was restored",
    appliedWithRecovery: "Replacement applied; recovery retained until you keep or roll back", needsReview: "Replacement needs recovery review",
    recoveryCount: (count) => `${count} replacement recovery ${count === 1 ? "record needs" : "records need"} review`,
    inspectionFailed: "Replacement recovery could not be inspected",
    rollbackBlocked: (paths) => `Save or close edited recovery files before rollback: ${paths}`,
    externalChangesPreserved: "Some files changed outside Asterlyn and were preserved; recovery still needs review",
    changesKept: "Replacement changes kept", originalsRestored: "Replacement originals restored",
  },
  changes: {
    groups: { changes: "Changes", unversioned: "Unversioned Files" }, commitFileActions: "Commit file actions",
    refreshChanges: "Refresh changes", selectTrackedToRestore: "Select an ordinary tracked file to restore",
    restoreToHead: "Restore uncommitted changes to HEAD", restoreChanges: "Restore uncommitted changes",
    openSelectedDiff: "Open selected file Diff", flatList: "flat list", directoryTree: "directory tree", showAs: (view) => `Show changes as ${view}`,
    expandAll: "Expand all folders", collapseAll: "Collapse all folders", checkingUntracked: "Checking for untracked files",
    trackedReady: "Tracked changes are ready.", untrackedFailed: "Untracked scan failed", refreshToRetry: "Refresh to try again.",
    workingTreeClean: "Working tree clean", noLocalChanges: "There are no local changes to commit.", changedFiles: "Changed files",
    includeAll: (group) => `Include all ${group}`, expand: (label) => `Expand ${label}`, collapse: (label) => `Collapse ${label}`,
    fileCount: (count) => `${count} ${count === 1 ? "file" : "files"}`, include: (path) => `Include ${path}`,
    selectedDiff: (path, selected) => `${selected ? "Selected, " : ""}open complete local diff for ${path}`,
    includeInCommit: (path) => `Include ${path} in commit`, resolveConflict: (path) => `Resolve conflict in ${path}`, resolve: "Resolve",
    untrackedScanFailed: "Untracked files could not be scanned. Refresh to retry.", scanningUntracked: "Scanning untracked files… counts are provisional.",
    changeLabels: {
      unmodified: "Unmodified", added: "Added", modified: "Modified", deleted: "Deleted", renamed: "Renamed",
      copied: "Copied", typeChanged: "Type changed", unmerged: "Unmerged", untracked: "Untracked", ignored: "Ignored", unknown: "Unknown",
    },
    changedFileCount: (count) => `${count} changed files`, resizeCommit: "Resize commit message area", createCommit: "Create commit",
    commitMessage: "Commit Message", commitButton: (count) => `Commit ${count || ""}`.trimEnd(), resolveBeforeCommit: "Resolve conflicts before committing.",
    excludeSubmodules: "Exclude submodule changes; commit them from their own Git root.", selectFileToCommit: "Select at least one file to commit.",
    saveBeforeRevert: "Save or undo the unsaved editor changes before reverting this file",
    restoreConfirm: (label) => `Restore 1 tracked file to HEAD?\n\n${label}\n\nThis replaces the reviewed staged and working-tree content. A recovery copy will be saved; Undo is available from Git → Recover local changes.`,
    saveBeforeRestore: "Save or undo unsaved editor changes before restoring these files", reverting: "Reverting selected file…",
    reverted: "Selected file reverted", filesSavedReview: "Files saved; review the refreshed selection before committing",
    creatingCommit: "Creating commit…", commitConcurrent: "Commit finished, but Git changed concurrently; inspect refreshed history before committing again",
    commitRefreshing: "Commit created; refreshing repository status…", commitCreated: "Commit created",
    patchTruncated: "Patch truncated at 4 MiB", unexpectedError: "Unexpected Changes operation error",
    fileSavedRefreshFailed: "File saved; Git status refresh failed",
  },
  gitOperations: {
    activeOperation: "Active Git operation", unresolvedFiles: (count) => `${count} unresolved ${count === 1 ? "file" : "files"}`,
    readyToContinue: "Ready to continue",
    names: { merge: "Merge", cherryPick: "Cherry-pick", rebase: "Rebase", squash: "Squash", revert: "Revert", bisect: "Bisect" },
    actions: { continue: "Continue", skip: "Skip", abort: "Abort" },
    prepare: (name) => `Prepare ${name}`, operation: "Operation",
    setupOptions: { merge: "Merge into current branch", cherryPick: "Cherry-pick commit(s)", rebase: "Rebase current branch", squash: "Squash current-branch commits" },
    targetsForCherryPick: "Commits, in application order", targetBeforeSquash: "Parent commit before the range",
    targetRef: "Target branch, tag, or commit", targetLinesPlaceholder: "One full ref or commit per line",
    newCommitMessage: "New commit message", squashMessagePlaceholder: "Describe the squashed change",
    exactReviewNote: "Asterlyn resolves every target to an exact object and binds the review to the current branch, HEAD, clean index, and worktree. Changes after review make the plan stale.",
    preparing: "Preparing…", review: "Review", reviewTitle: "Git operation review", planUnavailable: "The reviewed plan is unavailable.",
    confirm: (name) => `Confirm ${name}`, squashWarning: "Squash rewrites the checked-out branch. Push it later only with an explicitly reviewed force-with-lease.",
    conflictWarning: "Conflicts pause successfully and remain recoverable after restarting Asterlyn.", currentBranch: "Current branch",
    reviewedOperation: "Reviewed operation", exactTargets: "Exact targets", commitMessage: "Commit message", back: "Back", running: "Running…",
    openConflict: "Open conflict", readingConflict: "Reading base, ours, theirs, and worktree content…",
    conflictUnavailable: "The conflict is unavailable.", resolve: (path) => `Resolve ${path}`, conflictInputs: "Conflict inputs",
    base: "Base", ours: "Ours", theirs: "Theirs", resolvedResult: "Resolved result",
    binaryConflict: "Binary conflicts cannot be edited as text. Resolve them in an external tool or choose deletion.",
    resolvedFileContent: "Resolved file content",
    resolveSafetyNote: "Saving verifies the exact index stages and worktree revision opened above, writes the result, stages it, and confirms the staged blob.",
    resolveAsDeleted: "Resolve as Deleted", resolving: "Resolving…", saveAndStage: "Save and Stage",
    closeDialog: "Close Git operation dialog", notPresent: "Not present", loadingReview: "Loading Git operation review…",
    discardConflict: "Discard the unsaved conflict result? Copy any text you need first. Cancel keeps the result open.",
    cancel: "Cancel",
    unavailableForFolder: "Git operations are unavailable for this folder", alreadyInProgress: (name) => `${name} is already in progress`,
    saveBeforeReview: "Save or undo editor changes, then review the Git operation again",
    saveBeforeChangingActive: "Save or undo editor changes before changing the active Git operation",
    inProgress: (name) => `${name} in progress…`, completed: (name) => `${name} completed`, actionInProgress: (action) => `${action} Git operation…`,
    aborted: "Git operation aborted", skippedCommit: "Git operation skipped the current commit", continued: "Git operation continued",
    resolvingPath: (path) => `Resolving ${path}…`, resolvedAndStaged: (path) => `Resolved and staged ${path}`,
    paused: (name) => `${name} paused; review the operation controls in Changes`,
    conflictPaused: "Git paused with conflicts. Resolve the listed files from Changes, then Continue, Skip, or Abort the operation.",
    conflictChangedExternally: "This conflict changed outside Asterlyn. Your unsaved result is preserved; copy it before closing or reopening the conflict.",
    operationFailed: "The Git operation could not complete.",
  },
  history: {
    noRefs: "No refs", refsAppearHere: "Branches and tags will appear here.", branchOrTag: "Branch or tag",
    filterBranchesAndTags: "Filter branches and tags", noMatchingRefs: "No matching refs",
    tryAnotherRef: "Try another branch, remote, or tag name.", groups: { local: "Local", remote: "Remote", tag: "Tags" },
    activateAgainForAllRefs: "Activate again to show all refs", roots: (count) => `${count} Git roots`,
    allRefs: "All refs", allRefsTitle: "History from local branches, remote-tracking branches, and tags",
    branchCount: (count) => `Branch ${count}`, textOrHash: "Text or hash", filterCommitHistory: "Filter commit history",
    useRegularExpression: "Use regular expression", matchCase: "Match case", queryFilters: "History query filters",
    filterByAuthor: "Filter by commit author", filterByDate: "Filter by commit date",
    filterByPathsOrRoots: "Filter by repository paths or Git roots", graphOptions: "Graph order and traversal options",
    select: "Select…", recent: "Recent", favorites: "Favorites", allUsers: "All users", identity: "Identity",
    me: "me", loadedAuthors: "Loaded authors", allDates: "All dates", last24Hours: "Last 24 hours",
    last7Days: "Last 7 days", selectInTree: "Select in Tree…", rootsLabel: "Roots",
    loadingTrackedPaths: "Loading tracked paths…", trackedPathsFailed: "Tracked paths could not be loaded.",
    boundedTree: "Tree selection uses the bounded project file set.", keepOneRoot: "At least one module must remain selected",
    includeRootHistory: (name) => `Include ${name} history`, sort: "Sort", byCommitDate: "By commit date",
    topologically: "Topologically", options: "Options", firstParent: "First Parent", noMerges: "No Merges",
    branchActions: "Branch actions", expandLinearBranches: "Expand Linear Branches", collapseLinearBranches: "Collapse Linear Branches",
    pathsCount: (count) => `Paths ${count}`, rootsCount: (count) => `Roots ${count}`, paths: "Paths", user: "User",
    userCount: (count) => `User ${count}`, date: "Date", hours24: "24 hours", days7: "7 days",
    loadingFilteredHistory: "Loading filtered history…", couldNotLoadHistory: "Could not load history",
    queryCouldNotBeRead: "The selected history query could not be read.", noCommitsForFilters: "No commits match these filters",
    clearFilters: "Clear one or more history filters to widen the query.",
    invalidExpression: (error, showing) => `Invalid expression: ${error}${showing ? ". Showing the unfiltered result." : ""}`,
    noMatchingCommits: "No matching commits", tryCommitSearch: "Try a message, author, decoration, or full hash.",
    expandLinearTitle: (count) => `Expand ${count} linear commits`, linearCommitsCollapsed: (count) => `${count} linear commits collapsed`,
    expand: "Expand", gitRoot: (path) => `Git root: ${path}`, commitHistory: "Commit history",
    loadingOlderCommits: "Loading older commits…", showingNewestLimit: (count) => `Showing the newest ${count} commits (session limit)`,
    scrollForOlder: "Scroll to load older commits", allHistoryLoaded: (count, singular) => `All history loaded · ${count} ${singular ? "commit" : "commits"}`,
    noOlderCommits: "No older commits are available for the current filters.",
    olderCommitsFailed: (detail) => `Older commits could not be loaded: ${detail}`,
    historyRefreshFailed: (detail) => `History could not be refreshed: ${detail}`,
    historyRefreshWarning: "History refresh could not be completed", filteredHistoryWarning: "Filtered history could not be loaded",
    rootCommit: "root commit", oneParent: "one parent",
    mergeParents: (count) => `merge commit with ${count} parents`,
    collapsedGraphLane: (lane, total) => `Collapsed linear continuation in graph lane ${lane} of ${total}`,
    graphLane: (lane, total, parent) => `Graph lane ${lane} of ${total}, ${parent}`,
    state: "State", upstream: "Upstream", tracking: "Tracking", updated: "Updated", checkedOut: "Checked out",
    none: "None", noDivergence: "No divergence", operationsUsing: (name) => `Operations using ${name}`,
    mergeIntoCurrent: "Merge into current", rebaseCurrentOnto: "Rebase current onto", checkout: "Checkout",
    currentBranch: "Current branch", checkoutBranch: (name) => `Checkout ${name}`, checkoutBlocked: "Checkout blocked",
    localBranchesOnly: "Local branches only", submoduleHistoryOnly: "Submodule history only",
    selectLocalBranch: "Select a local branch to check it out. Remote and tag checkout remain deferred.",
    submoduleReadOnly: "This initialized submodule is available for history inspection only; branch mutations remain scoped to the main repository.",
    moreBlockers: (count) => `and ${count} more`,
    changedPathsBlock: (count) => `${count} changed ${count === 1 ? "path blocks" : "paths block"} branch mutation. Commit, stash, or remove the changes first.`,
    checkingUntrackedForBranch: "Checking for untracked files before branch mutation…",
    untrackedCheckFailedForBranch: "The untracked-file check failed. Refresh before changing branches.",
    cleanWorktreeVerified: "The index and working tree are clean. Asterlyn will verify again immediately before switching.",
    newLocalBranch: "New local branch",
    createFromHead: "Create from the current HEAD. The same clean-worktree gate applies.", branchName: "Branch name",
    createAndCheckout: "Create and checkout", details: "Details", nothingSelected: "Nothing selected",
    selectToInspect: "Select an item to inspect its metadata and available actions.", changedFiles: "Changed files", files: "Files",
    flatList: "flat list", directoryTree: "directory tree", showChangedFilesAs: (view) => `Show changed files as a ${view}`,
    expandChangedFolders: "Expand all changed-file folders", collapseChangedFolders: "Collapse all changed-file folders",
    resizeCommitDetails: "Resize commit message and details", loadingChangedFiles: "Loading changed files…",
    couldNotLoadCommit: "Could not load commit", noFirstParentChanges: "No first-parent changes",
    changedFilesByDirectory: "Changed files by directory", fileCount: (count) => `${count} ${count === 1 ? "file" : "files"}`,
    operationsUsingCommit: "Operations using this commit", cherryPick: "Cherry-pick", squashAfterThis: "Squash commits after this",
    commitMessageAndDetails: "Commit message and details", authoredOn: "on", emptyTree: "Empty tree",
    noNamedRefs: "No named refs point to this commit", refsSummary: (count, summary) => `In ${count} refs: ${summary}…`,
    showAll: "Show all", firstParentComparison: "First-parent comparison", comparedWith: (value) => `Compared with ${value}`,
    unknownTime: "Unknown time", referenceKinds: { head: "Head", local: "Local", remote: "Remote", tag: "Tag", other: "Other" },
    countOfCommits: (filtered, total, scope) => `${filtered} of ${total} commits in ${scope}`, refreshing: "Refreshing…",
    logicalRefsCount: (visible, total) => `${visible} of ${total} logical refs`, applyCount: (count) => `Apply ${count}`,
    selectBranchesOrTags: "Select Branches or Tags", noMatchingBranchesOrTags: "No matching branches or tags.",
    availableBranchesAndTags: "Available branches and tags", addToFavorites: "Add to favorites", removeFromFavorites: "Remove from favorites",
    clear: "Clear", apply: "Apply", all: "all", selectPathsToFilter: "Select Paths to Filter by",
    pathTextHelp: "Enter one or more exact tracked files or directories on separate lines. Ctrl/Cmd+Enter applies the selection.",
    trackedRepositoryPaths: "Tracked repository paths", noTrackedPaths: "No tracked paths.",
    unknownTrackedPath: (path) => `Unknown tracked path: ${path}`,
    ambiguousTrackedPath: (path) => `Path belongs to more than one Git root: ${path}`,
    expandPath: (path) => `Expand ${path}`, collapsePath: (path) => `Collapse ${path}`,
    checkingOut: (name) => `Checking out ${name}…`, checkedOutBranch: (name) => `Checked out ${name}`,
    creatingBranch: (name) => `Creating ${name}…`, createdBranch: (name) => `Created and checked out ${name}`,
  },
  recovery: {
    title: "Recover local changes", close: "Close", loading: "Loading recovery copies…",
    noneAvailable: "No recovery copies are available for this project. New Restore and conflict-resolution operations create a copy automatically.",
    undoOperation: "Undo this operation",
    confirmUndo: (operation, paths) => `Undo ${operation}?\n\n${paths}\n\nRestores the previous file and staging state. If the files, index, or HEAD have changed since, Undo stops and preserves the recovery copy.`,
    incomplete: (path) => `This operation did not reach a verified completion. Inspect its retained original files and proposed result before restoring: ${path}`,
    waitForOperation: "Wait for the current operation to finish.", saveBeforeRestore: "Save or undo unsaved editor changes before restoring these files.",
    restoring: "Restoring local changes…", restored: "Local changes restored",
  },
  remote: {
    unsupported: "unsupported", noRemote: "No remote", noBranch: "No branch", noCheckedOutBranch: "no checked-out branch", noUpstream: "No upstream",
    selectedRemoteScope: (remote) => `Selected remote: ${remote}. Fetch refreshes all standard branch-tracking refs from this remote. Update and Push apply only to the checked-out branch.`,
    unavailable: (detail) => `Unavailable: ${detail}`,
    cancelOperation: (kind, branch, remote) => `Cancel ${kind.toLocaleLowerCase()} for ${branch} using ${remote}. Git may already have changed local or remote state, so Asterlyn will refresh before another action.`,
    cancelRemoteOperation: "Cancel remote operation", actionNames: { fetch: "Fetch", pull: "Update", push: "Push" },
    selectionUnavailable: "Remote selection is unavailable because this project is not an active Git repository.",
    fetchUnavailable: "Fetch is unavailable because this project is not an active Git repository. Fetch would refresh the selected remote's standard branch-tracking refs without changing working files.",
    updateUnavailable: "Update is unavailable because this project is not an active Git repository. Update would affect only the checked-out branch and would require a confirmed fast-forward.",
    pushUnavailable: "Push is unavailable because this project is not an active Git repository. Push would open a current-branch review before any remote write.",
    fetchDescription: (remote, behind) => `Fetch from ${remote}. Refresh all standard branch-tracking refs for this remote without changing the checked-out branch or working files. The badge shows ${behind} incoming ${behind === 1 ? "commit" : "commits"} known after the last Fetch.`,
    updateDescription: (source, remote, destination) => `Update ${source} from ${remote}:${destination}. Opens a confirmation for Fast-forward, Merge, or Rebase. Merge and Rebase fetch first, then require a second exact-object review; conflicts pause for explicit resolution, Continue, Skip, or Abort.`,
    pushDescription: (source, remote, destination, ahead) => `Review Push from ${source} to ${remote}:${destination}. The badge shows ${ahead} outgoing ${ahead === 1 ? "commit" : "commits"} known from the last Fetch. Review can explicitly include tags or choose Force Push with an exact lease; it never retries automatically.`,
    strategies: { ffOnly: "Fast-forward", merge: "Merge", rebase: "Rebase" }, cancelling: "Cancelling…", updating: "Updating…", update: "Update",
    fetchAndReview: (strategy) => `Fetch and Review ${strategy}`, currentBranch: "Current branch", updateBranch: (branch) => `Update ${branch}`,
    cancelUpdateConfirmation: "Cancel Update confirmation",
    updateDescriptionText: "Choose how the configured upstream should be integrated into the checked-out branch. Merge and Rebase fetch first, then open an exact-object review before changing local history.",
    updateRoute: "Update route", updateMethod: "Update method", fastForwardOnly: "Fast-forward only",
    fastForwardDetail: "Fetch the configured upstream, then move the current branch only when no merge or rebase is required.",
    mergeIncoming: "Merge incoming changes", mergeIncomingDetail: "Fetch, review the exact tracking commit, then merge it. Conflicts pause with editable Base, Ours, and Theirs content.",
    rebaseCurrent: "Rebase the current branch", rebaseCurrentDetail: "Fetch, review the exact tracking commit, then replay local commits. Continue, Skip, and Abort remain restart-safe.",
    updateSafetyNote: "Fast-forward executes after this confirmation. Merge and Rebase require another review bound to the fetched object and current clean HEAD. No reset, stash, force, or automatic retry is performed.",
    cancelUpdate: "Cancel update", updateFastForwardAria: (source, remote, destination) => `Update ${source} from ${remote}:${destination} using fast-forward only`,
    updateReviewAria: (remote, strategy, destination, source) => `Fetch ${remote}, then review ${strategy} of ${remote}:${destination} into ${source}`,
    readingPushPreview: "Reading outgoing commits, tags, and files from the last-fetched refs…",
    pushPreviewUnavailable: "Push preview is unavailable. Close this window and refresh before retrying.",
    route: (source, remote, destination) => `${source} to ${remote}:${destination}`, selectedRoute: "the selected current-branch route",
    forcePushWithLease: "Force Push with Lease", publish: "Publish", push: "Push", tags: (count) => `${count} ${count === 1 ? "tag" : "tags"}`,
    noMatchingTags: "No matching tags", pushCommitsTo: (branch) => `Push Commits to ${branch}`, currentBranchFallback: "current branch",
    cancelPushConfirmation: "Cancel Push confirmation",
    pushReviewDescription: "Review the exact current-branch route, outgoing commits, aggregate changed files, optional tags, and push mode before writing to the selected remote.",
    forcePushNote: "Force Push uses an exact --force-with-lease bound to the last-fetched destination object. If the remote changed, Git rejects the push.",
    ordinaryPushNote: "Ordinary Push never rewrites the destination.", tagsAndRetryNote: "Tags are sent only when the checkbox is enabled. A rejection ends the operation; Asterlyn never retries automatically.",
    pushTags: "Push tags:", tagScope: "Tag scope", all: "All", refreshingReview: "Refreshing review…", cancelPush: "Cancel push", pushing: "Pushing…",
    pushConfirmationAria: (action, commits, tags, route) => `${action} ${commits} outgoing commits and ${tags} selected tags over ${route}`,
    choosePushMode: "Choose Push mode", pushMode: "Push mode", ordinaryNonForce: "Ordinary non-force update",
    forceLeaseDetail: "Rewrite only if the remote still matches the reviewed object",
    pushRouteAria: (branch, destination) => `Push route from local branch ${branch} to remote branch ${destination}`,
    showAllOutgoingFiles: "Show files changed by all outgoing commits", localBranch: "Local branch",
    outgoingCommitCount: (count) => `${count} outgoing ${count === 1 ? "commit" : "commits"}`, showAllFiles: "show all files",
    remoteBranch: "Remote branch", pushRemote: "Push remote", selectedDestination: "Selected destination for this push",
    noNewCommitObjects: "No new commit objects are visible against the selected remote's last-fetched refs.",
    publishCreatesDestination: "Publishing will still create the destination branch.", filesInSelectedCommit: "Files in selected commit",
    filesInAllCommits: "Files in all outgoing commits", outgoingCommits: "Outgoing commits",
    outgoingListAria: "Outgoing commits; activate the selected commit again to show all outgoing files", loading: "Loading…", showMore: "Show more",
    truncatedCommits: (total) => `Showing the first 1,000 of ${total} commits. Push includes all ${total}.`,
    readingSelectedFiles: "Reading files in the selected commit…", pushedRangeExceeded: "The pushed file range exceeded the bounded review limit.",
    noSelectedCommitFiles: "No files are reported for the selected commit.", noNetFileChanges: "No net file changes are present in the reviewed range.",
    pushedFileToolbar: "Pushed file presentation and navigation", openOutgoingDiff: "Open the latest outgoing commit Diff for the selected file",
    showPushedFilesAs: (view) => `Show pushed files as ${view}`, flatList: "a flat list", folderTree: "a folder tree",
    expandPushedFolders: "Expand all pushed file folders", collapsePushedFolders: "Collapse all pushed file folders",
    loadingPushedDiff: "Loading pushed file Diff…", closePushedDiff: "Close pushed file Diff", pushedDiffToolbar: "Pushed file Diff navigation and presentation",
    previousPushedFile: "Previous pushed file", nextPushedFile: "Next pushed file", imagePreviewAlt: (label) => `${label} image preview`,
    upstreamChanged: "The current upstream changed during Fetch; open Update again", alreadyUpToDate: "The current branch is already up to date",
    activeProjectNotGit: "The active project is no longer a Git repository.", endedRefreshRequired: "Remote operation ended; refresh required",
    operationInProgress: (name) => `${name} in progress…`, operationCompleted: (name) => `${name} completed`,
    operationNeedsReview: "Remote operation needs review", cancellingOperation: (name) => `Cancelling ${name}…`,
    branchOrRemoteChanged: "The branch or remote-tracking state changed. Close and review Push again.",
    noOutgoingCommitForFile: (path) => `No outgoing commit contains ${path}.`,
    selectedOutgoingFileMissing: "The selected outgoing file is no longer present. Refresh the Push review.",
    unexpectedError: "The remote operation could not complete.",
    policy: {
      finishActive: (name) => `Finish the active ${name} operation first.`, selectConfigured: "Select a configured remote.",
      unsupportedFetch: "This remote uses an unsupported fetch mapping.", refreshRefs: (remote) => `Refresh all standard branch-tracking refs from ${remote}.`,
      requireBranch: "A checked-out branch with a commit is required.",
      publishOrConfigure: "Publish the branch or configure a supported upstream first.", selectUpstream: "Select the current branch's upstream remote.",
      selectNamedUpstream: (name) => `Select ${name}, the configured upstream for this branch.`, unsupportedUpstream: "The upstream uses an unsupported fetch mapping.",
      waitForScan: "Wait for the complete worktree scan.", refreshAfterScanFailure: "Refresh after the worktree scan failure.",
      clearLocalChanges: "Commit, stash, or remove local changes first.",
      reviewDivergence: (ahead, behind) => `Review Merge or Rebase for ${ahead} local and ${behind} incoming commits.`,
      fastForward: (count) => `Fast-forward by ${count} upstream ${count === 1 ? "commit" : "commits"}.`, upToDate: "No upstream commits need to be pulled.",
      unsupportedPush: "This remote is mirrored or uses an unsupported mapping.",
      reviewOtherRemote: (remote, upstream) => `Review the same-named branch on ${remote}. A successful Push keeps ${upstream} as the configured upstream.`,
      createRemoteBranch: (remote) => `Create the same-named branch on ${remote}.`, publishBranch: "Publish branch",
      behindOrDiverged: "The branch is behind or diverged. Ordinary Push will remain blocked in review; Force Push with Lease is available only as an explicit choice.",
      sendCommits: (count, remote) => `Send ${count} ${count === 1 ? "commit" : "commits"} to ${remote}.`,
      noPendingCommits: "No branch commits are pending; open review to inspect optional tags.",
    },
  },
  errors: {
    remoteCancelledUnknown: "Push cancellation was requested. The remote outcome is unknown; fetch before retrying.",
    remoteCancelledChanged: "Remote operation was cancelled. Repository refs or files may have changed; the view was refreshed.",
    remoteCancelled: "Remote operation was cancelled.",
    remoteFailedFallback: "The remote operation failed without exposing child-process output. Check Git configuration and retry.",
    authenticationFailed: "Authentication was unavailable. Configure a non-interactive Git credential helper or SSH agent, then retry.",
    networkFailed: "The remote could not be reached. Check the network and remote configuration.",
    remoteRejected: "The remote rejected the update. Fetch and review the branch state before retrying.",
    fileConflictPreserved: "This file changed outside Asterlyn. Your local buffer is still open and was not overwritten.",
    unexpectedOperation: "An unexpected operation error occurred.",
    watchUnavailable: (detail) => detail ?? "Native file watching is unavailable; focus and manual refresh remain active.",
    watchStartFailed: (detail) => `Native file watching could not start: ${detail}`,
    externalReconcileFailed: (detail) => `External changes could not be reconciled: ${detail}`,
    translate: (message) => message,
  },
  editorPhrases: {
    "Control character": "Control character",
    "Go to line": "Go to line",
    "Selection deleted": "Selection deleted",
    close: "close",
    "current match": "current match",
    "folded code": "folded code",
    go: "go",
    "on line": "on line",
    "replaced $ matches": "replaced $ matches",
    "replaced match on line $": "replaced match on line $",
    to: "to",
    unfold: "unfold",
    Find: "Find",
    Replace: "Replace",
    next: "next",
    previous: "previous",
    all: "all",
    "match case": "match case",
    regexp: "regexp",
    "by word": "by word",
    replace: "replace",
    "replace all": "replace all",
    "Folded lines": "Folded lines",
    "Unfolded lines": "Unfolded lines",
    "Fold line": "Fold line",
    "Unfold line": "Unfold line",
  },
  documentDescription: "Asterlyn — a lightweight developer workspace with Git at its center.",
};
