import type { LocaleCatalog } from "./catalog.ts";

export const EN_US: LocaleCatalog = {
  locale: "en-US",
  common: {
    ready: "Ready",
    operationFailed: "Operation failed",
    cancel: "Cancel",
    close: "Close",
    retry: "Retry",
    planned: "Planned",
    available: "Available",
  },
  shell: {
    projectMenu: "Project menu",
    openProject: "Open a project",
    noProject: "No project",
    projectMenuFor: (name) => `Project menu for ${name}`,
    openProjectMenu: "Open project menu",
    open: "Open…",
    recentProjects: "Recent Projects",
    noOtherRecentProjects: "No other recent projects",
    browserDemo: "Browser demo",
    search: "Search",
    searchFilesAndCommands: "Search files and commands",
    remoteActions: "Current branch remote actions",
    remoteForActions: "Remote used by current branch actions",
    noRemote: "No remote",
    fetchBranch: "Fetch current branch",
    updateBranch: "Update current branch",
    pushBranch: "Push current branch",
    cancelRemote: "Cancel remote operation",
    refreshProject: "Refresh project",
    refreshShortcut: "Refresh (Ctrl/Cmd+R)",
    openSettings: "Open settings",
    settings: "Settings",
    windowControls: "Window controls",
    minimizeWindow: "Minimize window",
    minimize: "Minimize",
    maximizeWindow: "Maximize window",
    maximize: "Maximize",
    restoreWindow: "Restore window",
    restore: "Restore",
    closeWindow: "Close window",
    toolWindows: "Tool windows",
    version: (name, version) => `${name} version ${version}`,
    files: "Files",
    branches: "Branches",
    changes: "Changes",
    toolReorder: (label) => `${label} — drag to reorder`,
    openFolderFirst: "Open a project folder first — drag to reorder",
    gitUnavailableReorder: "Git is unavailable for this folder — drag to reorder",
    genericTool: "Tool window",
    leftToolWindow: "Left tool window",
    hideFiles: "Hide Files tool window",
    hideChanges: "Hide Changes tool window",
    waitingForProject: "Waiting for a project",
    resizeLeft: "Resize left tool window",
    editor: "Editor",
    welcome: "Welcome",
    showOpenFiles: "Show open files",
    openFiles: "Open files",
    editorName: (name) => `${name} Editor`,
    openFolder: "Open a project folder",
    openFolderDetail: "Browse ordinary folders, or use Git tools when the selected folder is a repository root.",
    resizeGit: "Resize Git tool window",
    branchesAndLog: "Branches and Log",
    prepareGitOperation: "Prepare a Merge, Cherry-pick, Rebase, or Squash operation",
    gitOperations: "Git operations…",
    recoverChanges: "Recover local changes",
    hideGit: "Hide Git tool window",
    commitLog: "Commit log",
    gitDetails: "Git details",
    resizeBranchTree: "Resize branch tree",
    resizeGitDetails: "Resize Git details",
    returnToWorkbench: "Return to workbench",
    backToWorkbench: "Back to workbench",
    settingsGroups: "Settings groups",
    currentEncoding: "Current file encoding",
    dismissError: "Dismiss error",
    selectCommitOrBranch: "Select a commit or branch",
    inspectorDetail: "Commit files and message details share this compact inspector.",
    simulateOpenFolder: "Simulate opening a project folder",
    demoFolderDetail: "Enter a sample path for browser-only interaction testing. This demo does not read that folder from your computer.",
    projectFolderPath: "Project folder path",
    openProjectAction: "Open project",
    whereOpenProject: "Where should this project open?",
    targetWindowDetail: "The current window already contains a project. Open the selected folder here or keep this workspace and open another window.",
    cancelOpeningProject: "Cancel opening project",
    currentWindow: "Current window",
    newWindow: "New window",
    folder: "Folder",
    gitUnavailable: "Git unavailable",
    detachedAt: (oid) => `Detached at ${oid}`,
    noBranch: "No branch",
    openingProject: "Opening project…",
    refreshingRepository: "Refreshing repository…",
    refreshingProjectFiles: "Refreshing project files…",
  },
  settings: {
    planned: "Planned",
    available: "Available",
    sections: { general: "General", appearance: "Appearance", editor: "Editor", "version-control": "Version Control", code: "Code" },
    generalTitle: "General",
    generalDescription: "Application-wide behavior and presentation language.",
    languageLabel: "Application language",
    languageDescription: "Choose a fixed interface language or follow the operating system.",
    languageSystem: "System",
    languageEnglish: "English",
    languageChinese: "简体中文",
    appearanceTitle: "Appearance",
    appearanceDescription: "Interface color and application-menu typography.",
    themeLabel: "Theme",
    themeDescription: "Choose a fixed palette or follow the operating-system appearance.",
    themeSystem: "System",
    themeDark: "Dark",
    themeLight: "Light",
    applicationFontLabel: "Application menu font",
    applicationFontDescription: "Changes navigation, toolbar, tabs, settings, and status text without scaling the editor.",
    applicationFontAria: "Application menu font size",
    editorTitle: "Editor",
    editorDescription: "Shared defaults for text editors and source-aware Diff panes.",
    editorFontLabel: "Editor font",
    editorFontDescription: "JetBrains Mono is included. Other fonts download only when selected, pass an integrity check, and remain cached in this profile.",
    editorFontSizeLabel: "Editor font size",
    editorFontSizeDescription: "Applies immediately to text files and Diff code.",
    editorFontSizeAria: "Editor font size",
    lineSpacingLabel: "Line spacing",
    lineSpacingDescription: "Controls vertical code density without changing file content.",
    lineSpacingAria: "Editor line spacing",
    letterSpacingLabel: "Letter spacing",
    letterSpacingDescription: "Adjusts horizontal spacing between code glyphs. The editor default is represented by 0 px.",
    letterSpacingAria: "Editor letter spacing",
    defaultPixels: (value) => `Default · ${value} px`,
    indentLabel: "Indent size",
    indentDescription: "Sets the spaces inserted for one editor indentation level.",
    indentAria: "Editor indent size",
    spaces: (value) => `${value} spaces`,
    tabWidthLabel: "Tab width",
    tabWidthDescription: "Controls the visual width of an existing tab character without rewriting content.",
    tabWidthAria: "Editor tab width",
    versionControlTitle: "Version Control",
    versionControlDescription: "Defaults shared by working-tree and commit Diff views.",
    diffLayoutLabel: "Diff layout",
    diffLayoutDescription: "Choose the default presentation used by every Diff preview.",
    diffLayoutAria: "Default Diff layout",
    sideBySide: "Side by side",
    unified: "Unified",
    whitespaceLabel: "Whitespace",
    whitespaceDescription: "Show spaces and tabs in Diff panes.",
    showWhitespace: "Show whitespace characters",
    codeTitle: "Code",
    codeDescription: "Syntax and language-specific services are introduced only when their boundaries are real.",
    syntaxHighlighting: "Syntax highlighting",
    syntaxDescription: "CodeMirror language packages load on demand for editors and Diff panes.",
    formatting: "Per-language formatting",
    formattingDescription: "Formatter choice, style profiles, and format-on-save need the future language-service boundary.",
    includedWithApp: "Included with Asterlyn",
    downloadingFont: (label) => `Downloading and verifying ${label}…`,
    downloadedFont: "Downloaded, verified, and cached",
    uncachedFont: "Loaded for this window; local cache is unavailable",
    cachedFont: "Loaded from verified local cache",
    fontReady: "Ready in this window",
    retryFont: (label) => `Retry ${label}`,
    editorFontAria: "Editor font family",
  },
  navigation: {
    navigationMode: "Navigation mode",
    tabs: { files: "Files", recent: "Recent", workspace: "Text", commands: "Commands" },
    titles: {
      files: "Search project files", recent: "Filter recent files",
      workspace: "Search text in current project", commands: "Search available commands",
    },
    hints: {
      files: "Go to File · authorized project catalog",
      recent: "Recent Files · successful opens in this project",
      workspace: "Find in Files · bounded search · reviewed recoverable replacement",
      commands: "Command Palette · only currently safe commands are enabled",
    },
    close: "Close", useRegularExpressions: "Use regular expressions", regularExpression: "Regular expression",
    enter: "Enter", enterToSearch: "Enter to search", navigate: "Navigate", open: "Open",
    workspaceSearchOptions: "Workspace search options", include: "Include",
    includeAria: "Files to include, comma-separated full-path globs", exclude: "Exclude",
    excludeAria: "Files to exclude, comma-separated full-path globs", context: "Context", contextLines: "Context lines",
    replace: "Replace", replacementText: "Replacement text", previewReplace: "Preview Replace",
    reviewRecoveries: (count) => `Review ${count} replacement recoveries`,
    recoveryRecords: (count) => `${count} recovery ${count === 1 ? "record" : "records"}`,
    noMatchingCommands: "No matching commands", broaderCommand: "Try a broader command name.",
    noRecentFiles: "No recent files", noMatchingFiles: "No matching files",
    recentFilesDetail: "Files appear here after they open successfully.",
    catalogLoading: "The project catalog is still loading.", fileQueryDetail: "Try part of a filename or path.",
    searchingProject: "Searching current project…", boundedSearchDetail: "The scan is bounded and cancellable.",
    searchFailed: "Search could not complete", tryAgain: "Try again.", searchFileContents: "Search file contents",
    searchInstructions: "Enter a case-sensitive literal or regular expression, then press Enter. Replacement always requires a separate preview.",
    noSubsetMatches: "No matches in the searched subset", noMatches: "No matches", zeroWidthMatch: "Zero-width match",
    coverageMatches: (count) => `${count} matches`, coverageFiles: (searched, catalog) => `${searched}/${catalog} files`,
    coverageEligible: (searched, eligible, catalog) => `${searched}/${eligible} eligible · ${catalog} catalog`,
    coverageComplete: "complete", coveragePartial: (reasons) => `partial: ${reasons}`,
    coverageReasons: { catalogTruncated: "catalog limit", candidateLimit: "candidate limit", byteLimit: "byte limit", matchLimit: "match limit" },
    coverageSkipped: (count) => `${count} skipped`,
    commands: {
      "open-repository": { label: "Open Project", detail: "Choose a local folder", aliases: "open folder repository" },
      "go-file": { label: "Go to File", detail: "Open a project file by name", aliases: "quick open" },
      "recent-files": { label: "Recent Files", detail: "Reopen a successful file", aliases: "history" },
      "find-workspace": { label: "Find in Files", detail: "Bounded search with reviewed replacement", aliases: "workspace search replace" },
      "find-current": { label: "Find and Replace in Current File", detail: "Undoable changes stay in the active buffer", aliases: "search" },
      "save-current": { label: "Save Current File", detail: "Use the conflict-safe save path", aliases: "write" },
      refresh: { label: "Refresh Project", detail: "Reload project files and available Git state", aliases: "reload sync" },
      "toggle-files": { label: "Toggle Files", detail: "Show or hide the Files tool window", aliases: "project tree" },
      "toggle-changes": { label: "Toggle Changes", detail: "Show or hide the Changes tool window", aliases: "git status" },
      "toggle-git": { label: "Toggle Git", detail: "Show or hide Branches and Log", aliases: "history branches" },
    },
  },
  projectFiles: {
    locateCurrentFile: "Locate current file in project",
    expandSelectedFolder: "Expand selected folder",
    collapseSelectedFolder: "Collapse selected folder",
    loadingProjectFiles: "Loading project files…",
    listFailed: "Could not list project files",
    tryAgain: "Try again",
    refreshingFiles: "Refreshing files…",
    boundedCatalog: "Showing a bounded project catalog; some paths were omitted.",
    projectFiles: "Project files", fileCount: (editable, ignored) => `${editable} editable files and ${ignored} ignored entries`,
    collapsePath: (path) => `Collapse ${path}`,
    expandPath: (path) => `Expand ${path}`,
    changeLabels: {
      unmodified: "Unmodified", added: "Added", modified: "Modified", deleted: "Deleted", renamed: "Renamed",
      copied: "Copied", typeChanged: "Type changed", unmerged: "Unmerged", untracked: "Untracked",
      ignored: "Ignored", unknown: "Unknown",
    },
  },
  editor: {
    conflict: "Conflict", saving: "Saving", unsaved: "Unsaved", saved: "Saved", close: "Close",
    closeFile: (name) => `Close ${name}`, preview: "Preview", diff: "Diff", imagePreview: "Image preview", diffPreview: "Diff preview",
    closePreview: (label) => `Close ${label} preview`, welcome: "Welcome", markdownMode: "Markdown editor mode",
    source: "Source", sourceTitle: "Edit Markdown source", split: "Split", splitTitle: "Edit source with live preview",
    renderedPreview: "Preview", previewTitle: "Rendered preview (read-only)", diffToolbar: "Diff navigation and presentation",
    diffNavigation: "Diff navigation", previousChange: "Previous change in file", nextChange: "Next change in file",
    previousFile: "Previous changed file", nextFile: "Next changed file", openSource: "Open file and reveal in Project",
    collapseUnchanged: "Collapse unchanged lines", expandUnchanged: "Expand unchanged lines", diffPresentation: "Diff presentation",
    unified: "Unified", unifiedTitle: "Unified diff", sideBySide: "Split", sideBySideTitle: "Side-by-side diff",
    whitespace: "Whitespace", whitespaceTitle: "Show whitespace characters",
    imageAlt: (label, path) => `${label} image for ${path}`,
    renderingMarkdown: "Rendering Markdown…", renderingMarkdownDetail: "The editor remains available while the preview engine loads.",
    tryAgain: "Try again", loadingImage: "Loading image preview…", imageFailed: "Could not preview image", imageSurface: "Image preview",
    loadingImageDiff: "Loading image Diff…", imageDiffFailed: "Could not preview image Diff", before: "Before", after: "After",
    fileDidNotExist: "File did not exist", fileRemoved: "File was removed", imageDiff: "Image Diff",
    markdownSource: "Markdown source editor", resizeMarkdown: "Resize Markdown source and preview", markdownPreview: "Markdown preview",
    largePreviewPaused: "Preview paused for this large file",
    largePreviewDetail: (size, limit) => `The document is ${size} MiB. Live preview is limited to ${limit} MiB; source editing and saving remain available.`,
    markdownFailed: "Markdown preview failed", blockedImage: "Image preview blocked", imagePlaceholder: (label) => `[Image: ${label}]`,
    linkUnavailable: "Link opening is not available in preview", workspaceReady: "Editor workspace ready",
    workspaceReadyDetail: "Open a project file to edit it, or choose a changed or committed file to inspect its Diff.",
    loadingText: "Loading text file…", openTextFailed: "Could not open text file", fileLoadFailed: "The file could not be loaded.",
    localChanges: "Local changes", loadingPatch: "Loading patch…", patchLoadFailed: "Could not load patch",
    noTextualDiff: "No textual diff is available for this selection.", loadingCommitPatch: "Loading commit patch…",
    currentEncoding: (label) => label ? `Current file encoding: ${label}` : "Current file encoding",
    ignoredNotOpened: "Ignored entries are shown for context and are not opened",
    outsideProjectTree: "The current file is outside the bounded project tree",
    searchUnsaved: "Search location was not applied because this file has unsaved edits",
    waitForLoad: "Wait for the current file load, then run the search again",
    openFileLimit: "All 20 open files contain unsaved changes; save or close one before opening another",
    searchRefreshFailed: "Search location could not be refreshed safely", wrongWorkspace: "Search result belongs to another workspace",
    invalidSearchLocation: "Search location is no longer valid; run the search again", staleSearchResult: "Search result is stale; run the search again",
    waitForFileOperation: "Wait for the current file operation before continuing", savedFile: (path) => `Saved ${path}`,
    newerEditsUnsaved: "Saved captured changes; newer edits remain unsaved", waitForSave: "Wait for the file to finish saving",
    confirmCloseFile: (path) => `Save changes to ${path} before closing?`, cancelKeepsTab: "Cancel keeps the tab open.",
    noFileChange: (direction) => `No ${direction} change in this file`, noChangedFile: (direction) => `No ${direction} changed file`,
    diffFileMissing: "The current Diff file is not present in the project tree", patchTruncated: "Patch truncated at 4 MiB",
    externalDirtyConflict: "A file with unsaved edits changed outside Asterlyn. The local buffer was preserved.",
    externalUnavailable: "The file changed or became unavailable outside Asterlyn; its open buffer was preserved.",
    unexpectedEditorError: "Unexpected editor-session error", unexpectedProjectFilesError: "Unexpected project-files error",
  },
  replacement: {
    safeWorkspaceEdit: "Safe workspace edit", preparingPreview: "Preparing replacement preview",
    rereadingFiles: "Re-reading the Git-authorized files…", cancel: "Cancel", previewUnavailable: "Replacement preview unavailable",
    close: "Close", createNewSearch: "Create a new search and preview.", sameSize: "same size",
    byteDelta: (value) => `${value > 0 ? "+" : ""}${value} B`, matches: (count) => `${count} ${count === 1 ? "match" : "matches"}`,
    blockedFile: "save or unselect the open edited file", comparisonFor: (path) => `Before and after preview for ${path}`,
    before: "Before", after: "After", skippedFiles: (count) => `${count} unsupported or unreadable files remain outside this reviewed replacement.`,
    reviewTitle: "Review Replace in Files", reviewedSummary: (matches, files) => `${matches} reviewed replacements across ${files} files. Only checked files will change.`,
    selectAll: "Select all files", cancelAndRestore: "Cancel and restore", applying: "Applying safely…",
    applySelection: (matches, files) => `Replace ${matches} in ${files} ${files === 1 ? "file" : "files"}`,
    noPendingRecovery: "No pending replacement recovery", backupsResolved: "Reviewed backups have been resolved.",
    recoveryFileSummary: (replaced, total, conflicts) => `${replaced}/${total} files contain the reviewed replacement${conflicts ? ` · ${conflicts} need manual review` : ""}`,
    readyToVerify: "Ready to verify", needsRecovery: "Needs recovery", restoring: "Restoring…", rollBack: "Roll back",
    keeping: "Keeping…", keepChanges: "Keep changes", crashSafeHistory: "Crash-safe history", recoveryTitle: "Replacement recovery",
    recoveryDetail: "Backups remain until you verify and keep the reviewed changes, or restore the exact originals.",
    fileStates: { original: "Original", replaced: "Replaced", conflict: "Changed externally", unavailable: "Unavailable" },
    cancellationRequested: "Cancellation requested. Restoring any files already changed…",
    blockedPaths: (paths) => `Save, close, or unselect ${paths} before replacing.`, blockedStatus: "Replacement blocked by an open edited file",
    stoppedAndRestored: "Replacement stopped; every changed file was restored",
    appliedWithRecovery: "Replacement applied; recovery retained until you keep or roll back", needsReview: "Replacement needs recovery review",
    recoveryCount: (count) => `${count} replacement recovery ${count === 1 ? "record needs" : "records need"} review`,
    inspectionFailed: "Replacement recovery could not be inspected",
    rollbackBlocked: (paths) => `Save or close edited recovery files before rollback: ${paths}`,
    externalChangesPreserved: "Some files changed outside Asterlyn and were preserved; recovery still needs review",
    changesKept: "Replacement changes kept", originalsRestored: "Replacement originals restored",
  },
  changes: {
    groups: { changes: "Changes", unversioned: "Unversioned Files" }, commitFileActions: "Commit file actions",
    refreshChanges: "Refresh changes", selectTrackedToRestore: "Select an ordinary tracked file to restore",
    restoreToHead: "Restore uncommitted changes to HEAD", restoreChanges: "Restore uncommitted changes",
    openSelectedDiff: "Open selected file Diff", flatList: "flat list", directoryTree: "directory tree", showAs: (view) => `Show changes as ${view}`,
    expandAll: "Expand all folders", collapseAll: "Collapse all folders", checkingUntracked: "Checking for untracked files",
    trackedReady: "Tracked changes are ready.", untrackedFailed: "Untracked scan failed", refreshToRetry: "Refresh to try again.",
    workingTreeClean: "Working tree clean", noLocalChanges: "There are no local changes to commit.", changedFiles: "Changed files",
    includeAll: (group) => `Include all ${group}`, expand: (label) => `Expand ${label}`, collapse: (label) => `Collapse ${label}`,
    fileCount: (count) => `${count} ${count === 1 ? "file" : "files"}`, include: (path) => `Include ${path}`,
    selectedDiff: (path, selected) => `${selected ? "Selected, " : ""}open complete local diff for ${path}`,
    includeInCommit: (path) => `Include ${path} in commit`, resolveConflict: (path) => `Resolve conflict in ${path}`, resolve: "Resolve",
    untrackedScanFailed: "Untracked files could not be scanned. Refresh to retry.", scanningUntracked: "Scanning untracked files… counts are provisional.",
    changeLabels: {
      unmodified: "Unmodified", added: "Added", modified: "Modified", deleted: "Deleted", renamed: "Renamed",
      copied: "Copied", typeChanged: "Type changed", unmerged: "Unmerged", untracked: "Untracked", ignored: "Ignored", unknown: "Unknown",
    },
    changedFileCount: (count) => `${count} changed files`, resizeCommit: "Resize commit message area", createCommit: "Create commit",
    commitMessage: "Commit Message", commitButton: (count) => `Commit ${count || ""}`.trimEnd(), resolveBeforeCommit: "Resolve conflicts before committing.",
    excludeSubmodules: "Exclude submodule changes; commit them from their own Git root.", selectFileToCommit: "Select at least one file to commit.",
    saveBeforeRevert: "Save or undo the unsaved editor changes before reverting this file",
    restoreConfirm: (label) => `Restore 1 tracked file to HEAD?\n\n${label}\n\nThis replaces the reviewed staged and working-tree content. A recovery copy will be saved; Undo is available from Git → Recover local changes.`,
    saveBeforeRestore: "Save or undo unsaved editor changes before restoring these files", reverting: "Reverting selected file…",
    reverted: "Selected file reverted", filesSavedReview: "Files saved; review the refreshed selection before committing",
    creatingCommit: "Creating commit…", commitConcurrent: "Commit finished, but Git changed concurrently; inspect refreshed history before committing again",
    commitRefreshing: "Commit created; refreshing repository status…", commitCreated: "Commit created",
    patchTruncated: "Patch truncated at 4 MiB", unexpectedError: "Unexpected Changes operation error",
  },
  gitOperations: {
    activeOperation: "Active Git operation", unresolvedFiles: (count) => `${count} unresolved ${count === 1 ? "file" : "files"}`,
    readyToContinue: "Ready to continue",
    names: { merge: "Merge", cherryPick: "Cherry-pick", rebase: "Rebase", squash: "Squash", revert: "Revert", bisect: "Bisect" },
    actions: { continue: "Continue", skip: "Skip", abort: "Abort" },
  },
  history: {
    noRefs: "No refs", refsAppearHere: "Branches and tags will appear here.", branchOrTag: "Branch or tag",
    filterBranchesAndTags: "Filter branches and tags", noMatchingRefs: "No matching refs",
    tryAnotherRef: "Try another branch, remote, or tag name.", groups: { local: "Local", remote: "Remote", tag: "Tags" },
    activateAgainForAllRefs: "Activate again to show all refs", roots: (count) => `${count} Git roots`,
    allRefs: "All refs", allRefsTitle: "History from local branches, remote-tracking branches, and tags",
    branchCount: (count) => `Branch ${count}`, textOrHash: "Text or hash", filterCommitHistory: "Filter commit history",
    useRegularExpression: "Use regular expression", matchCase: "Match case", queryFilters: "History query filters",
    filterByAuthor: "Filter by commit author", filterByDate: "Filter by commit date",
    filterByPathsOrRoots: "Filter by repository paths or Git roots", graphOptions: "Graph order and traversal options",
    select: "Select…", recent: "Recent", favorites: "Favorites", allUsers: "All users", identity: "Identity",
    me: "me", loadedAuthors: "Loaded authors", allDates: "All dates", last24Hours: "Last 24 hours",
    last7Days: "Last 7 days", selectInTree: "Select in Tree…", rootsLabel: "Roots",
    loadingTrackedPaths: "Loading tracked paths…", trackedPathsFailed: "Tracked paths could not be loaded.",
    boundedTree: "Tree selection uses the bounded project file set.", keepOneRoot: "At least one module must remain selected",
    includeRootHistory: (name) => `Include ${name} history`, sort: "Sort", byCommitDate: "By commit date",
    topologically: "Topologically", options: "Options", firstParent: "First Parent", noMerges: "No Merges",
    branchActions: "Branch actions", expandLinearBranches: "Expand Linear Branches", collapseLinearBranches: "Collapse Linear Branches",
    pathsCount: (count) => `Paths ${count}`, rootsCount: (count) => `Roots ${count}`, paths: "Paths", user: "User",
    userCount: (count) => `User ${count}`, date: "Date", hours24: "24 hours", days7: "7 days",
    loadingFilteredHistory: "Loading filtered history…", couldNotLoadHistory: "Could not load history",
    queryCouldNotBeRead: "The selected history query could not be read.", noCommitsForFilters: "No commits match these filters",
    clearFilters: "Clear one or more history filters to widen the query.",
    invalidExpression: (error, showing) => `Invalid expression: ${error}${showing ? ". Showing the unfiltered result." : ""}`,
    noMatchingCommits: "No matching commits", tryCommitSearch: "Try a message, author, decoration, or full hash.",
    expandLinearTitle: (count) => `Expand ${count} linear commits`, linearCommitsCollapsed: (count) => `${count} linear commits collapsed`,
    expand: "Expand", gitRoot: (path) => `Git root: ${path}`, commitHistory: "Commit history",
    loadingOlderCommits: "Loading older commits…", showingNewestLimit: (count) => `Showing the newest ${count} commits (session limit)`,
    scrollForOlder: "Scroll to load older commits", allHistoryLoaded: (count, singular) => `All history loaded · ${count} ${singular ? "commit" : "commits"}`,
    noOlderCommits: "No older commits are available for the current filters.", rootCommit: "root commit", oneParent: "one parent",
    mergeParents: (count) => `merge commit with ${count} parents`,
    collapsedGraphLane: (lane, total) => `Collapsed linear continuation in graph lane ${lane} of ${total}`,
    graphLane: (lane, total, parent) => `Graph lane ${lane} of ${total}, ${parent}`,
    state: "State", upstream: "Upstream", tracking: "Tracking", updated: "Updated", checkedOut: "Checked out",
    none: "None", noDivergence: "No divergence", operationsUsing: (name) => `Operations using ${name}`,
    mergeIntoCurrent: "Merge into current", rebaseCurrentOnto: "Rebase current onto", checkout: "Checkout",
    currentBranch: "Current branch", checkoutBranch: (name) => `Checkout ${name}`, checkoutBlocked: "Checkout blocked",
    localBranchesOnly: "Local branches only", submoduleHistoryOnly: "Submodule history only",
    selectLocalBranch: "Select a local branch to check it out. Remote and tag checkout remain deferred.",
    submoduleReadOnly: "This initialized submodule is available for history inspection only; branch mutations remain scoped to the main repository.",
    moreBlockers: (count) => `and ${count} more`,
    changedPathsBlock: (count) => `${count} changed ${count === 1 ? "path blocks" : "paths block"} branch mutation. Commit, stash, or remove the changes first.`,
    checkingUntrackedForBranch: "Checking for untracked files before branch mutation…",
    untrackedCheckFailedForBranch: "The untracked-file check failed. Refresh before changing branches.",
    cleanWorktreeVerified: "The index and working tree are clean. Asterlyn will verify again immediately before switching.",
    newLocalBranch: "New local branch",
    createFromHead: "Create from the current HEAD. The same clean-worktree gate applies.", branchName: "Branch name",
    createAndCheckout: "Create and checkout", details: "Details", nothingSelected: "Nothing selected",
    selectToInspect: "Select an item to inspect its metadata and available actions.", changedFiles: "Changed files", files: "Files",
    flatList: "flat list", directoryTree: "directory tree", showChangedFilesAs: (view) => `Show changed files as a ${view}`,
    expandChangedFolders: "Expand all changed-file folders", collapseChangedFolders: "Collapse all changed-file folders",
    resizeCommitDetails: "Resize commit message and details", loadingChangedFiles: "Loading changed files…",
    couldNotLoadCommit: "Could not load commit", noFirstParentChanges: "No first-parent changes",
    changedFilesByDirectory: "Changed files by directory", fileCount: (count) => `${count} ${count === 1 ? "file" : "files"}`,
    operationsUsingCommit: "Operations using this commit", cherryPick: "Cherry-pick", squashAfterThis: "Squash commits after this",
    commitMessageAndDetails: "Commit message and details", authoredOn: "on", emptyTree: "Empty tree",
    noNamedRefs: "No named refs point to this commit", refsSummary: (count, summary) => `In ${count} refs: ${summary}…`,
    showAll: "Show all", firstParentComparison: "First-parent comparison", comparedWith: (value) => `Compared with ${value}`,
    unknownTime: "Unknown time", referenceKinds: { head: "Head", local: "Local", remote: "Remote", tag: "Tag", other: "Other" },
    countOfCommits: (filtered, total, scope) => `${filtered} of ${total} commits in ${scope}`, refreshing: "Refreshing…",
    logicalRefsCount: (visible, total) => `${visible} of ${total} logical refs`, applyCount: (count) => `Apply ${count}`,
    selectBranchesOrTags: "Select Branches or Tags", noMatchingBranchesOrTags: "No matching branches or tags.",
    availableBranchesAndTags: "Available branches and tags", addToFavorites: "Add to favorites", removeFromFavorites: "Remove from favorites",
    clear: "Clear", apply: "Apply", all: "all", selectPathsToFilter: "Select Paths to Filter by",
    pathTextHelp: "Enter one or more exact tracked files or directories on separate lines. Ctrl/Cmd+Enter applies the selection.",
    trackedRepositoryPaths: "Tracked repository paths", noTrackedPaths: "No tracked paths.",
    expandPath: (path) => `Expand ${path}`, collapsePath: (path) => `Collapse ${path}`,
  },
  editorPhrases: {
    "Control character": "Control character",
    "Go to line": "Go to line",
    "Selection deleted": "Selection deleted",
    close: "close",
    "current match": "current match",
    "folded code": "folded code",
    go: "go",
    "on line": "on line",
    "replaced $ matches": "replaced $ matches",
    "replaced match on line $": "replaced match on line $",
    to: "to",
    unfold: "unfold",
    Find: "Find",
    Replace: "Replace",
    next: "next",
    previous: "previous",
    all: "all",
    "match case": "match case",
    regexp: "regexp",
    "by word": "by word",
    replace: "replace",
    "replace all": "replace all",
    "Folded lines": "Folded lines",
    "Unfolded lines": "Unfolded lines",
    "Fold line": "Fold line",
    "Unfold line": "Unfold line",
  },
  documentDescription: "Asterlyn — a lightweight developer workspace with Git at its center.",
};
