import type { KeybindingCopy } from "./keybinding-copy.ts";

export const KEYBINDING_EN_US: KeybindingCopy = {
  title: "Keyboard Shortcuts",
  description: "Search commands, record custom shortcuts, and resolve conflicts from one place.",
  search: "Search shortcuts",
  searchPlaceholder: "Command name, ID, or shortcut",
  filter: "Shortcut filters",
  categoryFilter: "Command category",
  allCategories: "All categories",
  all: "All",
  modified: "Modified",
  conflicts: "Conflicts",
  conflict: "Conflict",
  resetAll: "Reset all",
  resetAllConfirm: "Reset every customized keyboard shortcut to the current platform defaults?",
  reset: "Reset",
  add: "Add",
  unassigned: "Unassigned",
  unknown: "Unknown command",
  unavailable: "Unavailable",
  listLabel: "Application commands and keyboard shortcuts",
  noResults: "No keyboard shortcuts match the current search and filter.",
  pressKeys: "Press a shortcut",
  record: (command) => `Record shortcut for ${command}`,
  recordInstructions: "Press one or two key combinations. Enter saves, Backspace clears, and Escape cancels.",
  recorderAria: "Keyboard shortcut recorder",
  cancel: "Cancel",
  save: "Save",
  replace: "Replace conflict",
  reservedBinding: "That combination is reserved for window or accessible component behavior.",
  protectedBinding: "That combination is protected for ordinary text editing in this context.",
  conflictWith: (commands) => `This shortcut conflicts with ${commands}.`,
  editBinding: (command, binding) => `Edit ${binding} for ${command}`,
  removeBinding: (command) => `Remove shortcut from ${command}`,
  profileInvalid: "The saved shortcut profile is invalid. Platform defaults remain active; reset all shortcuts to repair it.",
  profileOversized: "The saved shortcut profile exceeds the safety limit. Platform defaults remain active; reset all shortcuts to repair it.",
  waitingForChord: "Waiting for the second shortcut key…",
  workspaceRequired: "Open a project first.",
  editorRequired: "Focus an available editor first.",
  historyRequired: "Open and focus Git history first.",
  gitRequired: "This command requires a Git project.",
  categories: { workbench: "Workbench", workspace: "Project", editor: "Editor", view: "Tool windows" },
};
