import type { KeybindingCopy } from "./keybinding-copy.ts";

export const KEYBINDING_ZH_CN: KeybindingCopy = {
  title: "快捷键",
  description: "集中搜索命令、录制自定义快捷键并处理冲突。",
  search: "搜索快捷键",
  searchPlaceholder: "命令名称、ID 或快捷键",
  filter: "快捷键筛选",
  categoryFilter: "命令分类",
  allCategories: "全部分类",
  all: "全部",
  modified: "已修改",
  conflicts: "冲突",
  conflict: "冲突",
  resetAll: "全部重置",
  resetAllConfirm: "确定将所有自定义快捷键重置为当前平台的默认值吗？",
  reset: "重置",
  add: "添加",
  unassigned: "未分配",
  unknown: "未知命令",
  unavailable: "当前不可用",
  listLabel: "应用命令和快捷键",
  noResults: "没有符合当前搜索和筛选条件的快捷键。",
  pressKeys: "请按快捷键",
  record: (command) => `为“${command}”录制快捷键`,
  recordInstructions: "可输入一段或两段组合键。Enter 保存，Backspace 清除，Escape 取消。",
  recorderAria: "快捷键录制器",
  cancel: "取消",
  save: "保存",
  replace: "替换冲突项",
  reservedBinding: "该组合键由窗口或无障碍组件行为保留。",
  protectedBinding: "该组合键在当前作用域中受普通文本编辑行为保护。",
  conflictWith: (commands) => `该快捷键与 ${commands} 冲突。`,
  editBinding: (command, binding) => `编辑“${command}”的 ${binding}`,
  removeBinding: (command) => `移除“${command}”的快捷键`,
  profileInvalid: "已保存的快捷键配置无效，当前使用平台默认值；请全部重置以修复。",
  profileOversized: "已保存的快捷键配置超过安全上限，当前使用平台默认值；请全部重置以修复。",
  waitingForChord: "正在等待第二段快捷键…",
  workspaceRequired: "请先打开项目。",
  editorRequired: "请先聚焦可用的编辑器。",
  historyRequired: "请先打开并聚焦 Git 历史记录。",
  gitRequired: "该命令需要 Git 项目。",
  settingsRequired: "请先打开设置。",
  leftToolRequired: "请先显示一个左侧工具窗口。",
  bottomToolRequired: "请先显示一个底部工具窗口。",
  categories: { workbench: "工作台", workspace: "项目", editor: "编辑器", view: "工具窗口" },
};
