export interface KeybindingCopy {
  title: string;
  description: string;
  search: string;
  searchPlaceholder: string;
  filter: string;
  categoryFilter: string;
  allCategories: string;
  all: string;
  modified: string;
  conflicts: string;
  conflict: string;
  resetAll: string;
  resetAllConfirm: string;
  reset: string;
  add: string;
  unassigned: string;
  unknown: string;
  unavailable: string;
  listLabel: string;
  noResults: string;
  pressKeys: string;
  record(command: string): string;
  recordInstructions: string;
  recorderAria: string;
  cancel: string;
  save: string;
  replace: string;
  reservedBinding: string;
  protectedBinding: string;
  conflictWith(commands: string): string;
  editBinding(command: string, binding: string): string;
  removeBinding(command: string): string;
  profileInvalid: string;
  profileOversized: string;
  waitingForChord: string;
  workspaceRequired: string;
  editorRequired: string;
  historyRequired: string;
  gitRequired: string;
  categories: Record<"workbench" | "workspace" | "editor" | "view", string>;
}
