import type { LocaleCatalog } from "./catalog.ts";

export const ZH_CN = {
  locale: "zh-CN",
  common: { ready: "就绪", operationFailed: "操作失败", cancel: "取消", close: "关闭", retry: "重试", planned: "计划中", available: "可用" },
  shell: {
    projectMenu: "项目菜单", openProject: "打开项目", noProject: "未打开项目",
    projectMenuFor: (name) => `${name} 的项目菜单`, openProjectMenu: "打开项目菜单",
    open: "打开…", recentProjects: "最近项目", noOtherRecentProjects: "没有其他最近项目",
    browserDemo: "浏览器演示", search: "搜索", searchFilesAndCommands: "搜索文件和命令",
    remoteActions: "当前分支远程操作", remoteForActions: "当前分支操作使用的远程仓库", noRemote: "无远程仓库",
    fetchBranch: "获取当前分支", updateBranch: "更新当前分支", pushBranch: "推送当前分支", cancelRemote: "取消远程操作",
    refreshProject: "刷新项目", refreshShortcut: "刷新（Ctrl/Cmd+R）", openSettings: "打开设置", settings: "设置",
    windowControls: "窗口控制", minimizeWindow: "最小化窗口", minimize: "最小化", maximizeWindow: "最大化窗口", maximize: "最大化",
    restoreWindow: "还原窗口", restore: "还原", closeWindow: "关闭窗口", toolWindows: "工具窗口",
    version: (name, version) => `${name} 版本 ${version}`, files: "文件", branches: "分支", changes: "更改",
    toolReorder: (label) => `${label} — 拖动可排序`, openFolderFirst: "请先打开项目文件夹 — 拖动可排序",
    gitUnavailableReorder: "此文件夹无法使用 Git — 拖动可排序", genericTool: "工具窗口", leftToolWindow: "左侧工具窗口",
    hideFiles: "隐藏文件工具窗口", hideChanges: "隐藏更改工具窗口", waitingForProject: "正在等待项目", resizeLeft: "调整左侧工具窗口大小", editor: "编辑器",
    welcome: "欢迎", showOpenFiles: "显示已打开文件", openFiles: "已打开文件", editorName: (name) => `${name} 编辑器`,
    openFolder: "打开项目文件夹", openFolderDetail: "可浏览普通文件夹；当所选文件夹为仓库根目录时，还可使用 Git 工具。",
    resizeGit: "调整 Git 工具窗口大小", branchesAndLog: "分支与日志", prepareGitOperation: "准备合并、拣选、变基或压缩操作",
    gitOperations: "Git 操作…", recoverChanges: "恢复本地更改", hideGit: "隐藏 Git 工具窗口", commitLog: "提交日志",
    gitDetails: "Git 详情", resizeBranchTree: "调整分支树大小", resizeGitDetails: "调整 Git 详情大小",
    returnToWorkbench: "返回工作台", backToWorkbench: "返回工作台", settingsGroups: "设置分组",
    currentEncoding: "当前文件编码", dismissError: "关闭错误提示", selectCommitOrBranch: "请选择提交或分支",
    inspectorDetail: "提交文件和消息详情显示在此检查器中。", simulateOpenFolder: "模拟打开项目文件夹",
    demoFolderDetail: "输入示例路径以测试浏览器交互。此演示不会读取计算机上的对应文件夹。",
    projectFolderPath: "项目文件夹路径", openProjectAction: "打开项目", whereOpenProject: "在哪里打开此项目？",
    targetWindowDetail: "当前窗口已有项目。可以在此窗口打开所选文件夹，也可以保留当前工作区并打开新窗口。",
    cancelOpeningProject: "取消打开项目", currentWindow: "当前窗口", newWindow: "新窗口", folder: "文件夹",
    gitUnavailable: "Git 不可用", detachedAt: (oid) => `分离于 ${oid}`, noBranch: "无分支",
    openingProject: "正在打开项目…", refreshingRepository: "正在刷新仓库…", refreshingProjectFiles: "正在刷新项目文件…",
  },
  settings: {
    planned: "计划中", available: "可用",
    sections: { general: "常规", appearance: "外观", editor: "编辑器", "version-control": "版本控制", code: "代码" },
    generalTitle: "常规", generalDescription: "应用范围的行为与界面语言。", languageLabel: "应用语言",
    languageDescription: "选择固定的界面语言，或跟随操作系统。", languageSystem: "跟随系统", languageEnglish: "English", languageChinese: "简体中文",
    appearanceTitle: "外观", appearanceDescription: "界面颜色和应用菜单字体。", themeLabel: "主题",
    themeDescription: "选择固定配色，或跟随操作系统外观。", themeSystem: "跟随系统", themeDark: "深色", themeLight: "浅色",
    applicationFontLabel: "应用菜单字体", applicationFontDescription: "调整导航、工具栏、标签页、设置和状态文字，不缩放编辑器。",
    applicationFontAria: "应用菜单字号", editorTitle: "编辑器", editorDescription: "文本编辑器和源码差异窗格共用的默认设置。",
    editorFontLabel: "编辑器字体", editorFontDescription: "JetBrains Mono 已内置。其他字体仅在选中后下载，校验完整性并缓存在此配置中。",
    editorFontSizeLabel: "编辑器字号", editorFontSizeDescription: "立即应用于文本文件和差异代码。", editorFontSizeAria: "编辑器字号",
    lineSpacingLabel: "行距", lineSpacingDescription: "调整代码的纵向密度，不改变文件内容。", lineSpacingAria: "编辑器行距",
    letterSpacingLabel: "字距", letterSpacingDescription: "调整代码字符之间的横向间距，0 px 表示编辑器默认值。", letterSpacingAria: "编辑器字距",
    defaultPixels: (value) => `默认 · ${value} px`, indentLabel: "缩进大小", indentDescription: "设置一级编辑器缩进插入的空格数。",
    indentAria: "编辑器缩进大小", spaces: (value) => `${value} 个空格`, tabWidthLabel: "制表符宽度",
    tabWidthDescription: "调整已有制表符的显示宽度，不重写文件内容。", tabWidthAria: "编辑器制表符宽度",
    versionControlTitle: "版本控制", versionControlDescription: "工作树和提交差异视图共用的默认设置。", diffLayoutLabel: "差异布局",
    diffLayoutDescription: "选择所有差异预览使用的默认布局。", diffLayoutAria: "默认差异布局", sideBySide: "并排", unified: "统一",
    whitespaceLabel: "空白字符", whitespaceDescription: "在差异窗格中显示空格和制表符。", showWhitespace: "显示空白字符",
    codeTitle: "代码", codeDescription: "仅在边界明确时引入语法和语言相关服务。", syntaxHighlighting: "语法高亮",
    syntaxDescription: "编辑器和差异窗格按需加载 CodeMirror 语言包。", formatting: "按语言格式化",
    formattingDescription: "格式化程序、样式配置和保存时格式化需要未来的语言服务边界。", includedWithApp: "Asterlyn 已内置",
    downloadingFont: (label) => `正在下载并校验 ${label}…`, downloadedFont: "已下载、校验并缓存",
    uncachedFont: "已在当前窗口加载；本地缓存不可用", cachedFont: "已从校验过的本地缓存加载", fontReady: "当前窗口已就绪",
    retryFont: (label) => `重试 ${label}`, editorFontAria: "编辑器字体系列",
  },
  navigation: {
    navigationMode: "导航模式",
    tabs: { files: "文件", recent: "最近", workspace: "文本", commands: "命令" },
    titles: {
      files: "搜索项目文件", recent: "筛选最近文件", workspace: "搜索当前项目中的文本", commands: "搜索可用命令",
    },
    hints: {
      files: "转到文件 · 已授权的项目目录", recent: "最近文件 · 本项目中成功打开的文件",
      workspace: "在文件中查找 · 有界搜索 · 经确认且可恢复的替换", commands: "命令面板 · 仅启用当前安全的命令",
    },
    close: "关闭", useRegularExpressions: "使用正则表达式", regularExpression: "正则表达式",
    enter: "回车", enterToSearch: "回车搜索", navigate: "导航", open: "打开",
    workspaceSearchOptions: "工作区搜索选项", include: "包含", includeAria: "要包含的文件，以逗号分隔的完整路径 glob",
    exclude: "排除", excludeAria: "要排除的文件，以逗号分隔的完整路径 glob", context: "上下文", contextLines: "上下文行数",
    replace: "替换", replacementText: "替换文本", previewReplace: "预览替换",
    reviewRecoveries: (count) => `查看 ${count} 条替换恢复记录`, recoveryRecords: (count) => `${count} 条恢复记录`,
    noMatchingCommands: "没有匹配的命令", broaderCommand: "请尝试更宽泛的命令名称。",
    noRecentFiles: "没有最近文件", noMatchingFiles: "没有匹配的文件", recentFilesDetail: "成功打开文件后会显示在这里。",
    catalogLoading: "项目目录仍在加载。", fileQueryDetail: "请尝试输入文件名或路径的一部分。",
    searchingProject: "正在搜索当前项目…", boundedSearchDetail: "扫描范围有限，并且可以取消。",
    searchFailed: "搜索未能完成", tryAgain: "请重试。", searchFileContents: "搜索文件内容",
    searchInstructions: "输入区分大小写的文本或正则表达式，然后按回车。替换始终需要单独预览。",
    noSubsetMatches: "已搜索范围内没有匹配项", noMatches: "没有匹配项", zeroWidthMatch: "零宽匹配",
    commands: {
      "open-repository": { label: "打开项目", detail: "选择本地文件夹", aliases: "open folder repository 打开文件夹仓库" },
      "go-file": { label: "转到文件", detail: "按名称打开项目文件", aliases: "go to file quick open 快速打开" },
      "recent-files": { label: "最近文件", detail: "重新打开成功读取过的文件", aliases: "recent files history 历史" },
      "find-workspace": { label: "在文件中查找", detail: "有界搜索与经确认的替换", aliases: "find in files workspace search replace 全局搜索" },
      "find-current": { label: "在当前文件中查找和替换", detail: "可撤销的更改保留在活动缓冲区", aliases: "find replace search 查找" },
      "save-current": { label: "保存当前文件", detail: "使用可安全处理冲突的保存流程", aliases: "save write 保存" },
      refresh: { label: "刷新项目", detail: "重新加载项目文件和可用 Git 状态", aliases: "refresh reload sync 刷新" },
      "toggle-files": { label: "切换文件窗口", detail: "显示或隐藏文件工具窗口", aliases: "toggle files project tree 项目树" },
      "toggle-changes": { label: "切换更改窗口", detail: "显示或隐藏更改工具窗口", aliases: "toggle changes git status 状态" },
      "toggle-git": { label: "切换 Git 窗口", detail: "显示或隐藏分支与日志", aliases: "toggle git history branches 历史分支" },
    },
  },
  editorPhrases: {
    "Control character": "控制字符",
    "Go to line": "转到行",
    "Selection deleted": "已删除所选内容",
    close: "关闭",
    "current match": "当前匹配",
    "folded code": "已折叠的代码",
    go: "转到",
    "on line": "位于第",
    "replaced $ matches": "已替换 $ 处匹配",
    "replaced match on line $": "已替换第 $ 行的匹配",
    to: "至",
    unfold: "展开",
    Find: "查找",
    Replace: "替换",
    next: "下一个",
    previous: "上一个",
    all: "全部",
    "match case": "区分大小写",
    regexp: "正则表达式",
    "by word": "全字匹配",
    replace: "替换",
    "replace all": "全部替换",
    "Folded lines": "已折叠行",
    "Unfolded lines": "已展开行",
    "Fold line": "折叠行",
    "Unfold line": "展开行",
  },
  documentDescription: "Asterlyn — 以 Git 为中心的轻量开发工作区。",
} satisfies LocaleCatalog;
