import type { LocaleCatalog } from "./catalog.ts";

export const ZH_CN = {
  locale: "zh-CN",
  common: {
    ready: "就绪", operationFailed: "操作失败", cancel: "取消", close: "关闭", retry: "重试", planned: "计划中", available: "可用",
    confirmSaveBefore: (count, action) => `在${action}前保存 ${count} 个未保存文件吗？`, cancelKeepsWorkspace: "取消将保持当前工作区打开。",
    actions: { closeApp: "关闭 Asterlyn", switchRepositories: "切换仓库", pullChanges: "拉取更改", reviewGitOperation: "审查 Git 操作", createCommit: "创建提交", changeBranches: "更改分支" },
    prepareStrategy: (strategy) => `准备${strategy}`,
  },
  shell: {
    projectMenu: "项目菜单", openProject: "打开项目", noProject: "未打开项目",
    projectMenuFor: (name) => `${name} 的项目菜单`, openProjectMenu: "打开项目菜单",
    open: "打开…", recentProjects: "最近项目", noOtherRecentProjects: "没有其他最近项目",
    removeRecentProject: (name) => `从最近项目中移除 ${name}`,
    browserDemo: "浏览器演示", search: "搜索", searchFilesAndCommands: "搜索文件和命令",
    remoteActions: "当前分支远程操作", remoteForActions: "当前分支操作使用的远程仓库", noRemote: "无远程仓库", moreRemoteActions: "更多远程操作",
    fetchBranch: "获取当前分支", updateBranch: "更新当前分支", pushBranch: "推送当前分支", cancelRemote: "取消远程操作",
    refreshProject: "刷新项目", refreshShortcut: "刷新（Ctrl/Cmd+R）", openSettings: "打开设置", settings: "设置",
    windowControls: "窗口控制", minimizeWindow: "最小化窗口", minimize: "最小化", maximizeWindow: "最大化窗口", maximize: "最大化",
    restoreWindow: "还原窗口", restore: "还原", closeWindow: "关闭窗口", toolWindows: "工具窗口",
    version: (name, version) => `${name} 版本 ${version}`, files: "文件", branches: "分支", changes: "更改", terminal: "终端",
    toolReorder: (label) => `${label} — 拖动可排序`, openFolderFirst: "请先打开项目文件夹 — 拖动可排序",
    gitUnavailableReorder: "此文件夹无法使用 Git — 拖动可排序", genericTool: "工具窗口", leftToolWindow: "左侧工具窗口",
    hideFiles: "隐藏文件工具窗口", hideChanges: "隐藏更改工具窗口", waitingForProject: "正在等待项目", resizeLeft: "调整左侧工具窗口大小", editor: "编辑器",
    welcome: "欢迎", showOpenFiles: "显示已打开文件", openFiles: "已打开文件", editorName: (name) => `${name} 编辑器`,
    openFolder: "打开项目文件夹", openFolderDetail: "可浏览普通文件夹；当所选文件夹为仓库根目录时，还可使用 Git 工具。",
    resizeGit: "调整 Git 工具窗口大小", branchesAndLog: "分支与日志", prepareGitOperation: "准备合并、拣选、变基或压缩操作",
    gitOperations: "Git 操作…", recoverChanges: "恢复本地更改", hideGit: "隐藏 Git 工具窗口", hideTerminal: "隐藏终端工具窗口",
    commitLog: "提交日志",
    gitDetails: "Git 详情", resizeBranchTree: "调整分支树大小", resizeGitDetails: "调整 Git 详情大小",
    returnToWorkbench: "返回工作台", backToWorkbench: "返回工作台", settingsGroups: "设置分组",
    currentEncoding: "当前文件编码", dismissError: "关闭消息", selectCommitOrBranch: "请选择提交或分支",
    inspectorDetail: "提交文件和消息详情显示在此检查器中。", simulateOpenFolder: "模拟打开项目文件夹",
    demoFolderDetail: "输入示例路径以测试浏览器交互。此演示不会读取计算机上的对应文件夹。",
    projectFolderPath: "项目文件夹路径", openProjectAction: "打开项目", whereOpenProject: "在哪里打开此项目？",
    targetWindowDetail: "当前窗口已有项目。可以在此窗口打开所选文件夹，也可以保留当前工作区并打开新窗口。",
    cancelOpeningProject: "取消打开项目", currentWindow: "当前窗口", newWindow: "新窗口", folder: "文件夹",
    gitUnavailable: "Git 不可用", detachedAt: (oid) => `分离于 ${oid}`, noBranch: "无分支",
    openingProject: "正在打开项目…", refreshingRepository: "正在刷新仓库…", refreshingProjectFiles: "正在刷新项目文件…",
    projectOpenedInNewWindow: "项目已在新窗口中打开",
    projectFocusedInExistingWindow: "项目已打开，现有窗口已切换到前台",
  },
  terminal: {
    notRunning: "没有活动会话",
    starting: "正在启动终端…",
    running: "终端正在运行",
    started: (shell) => `${shell} 终端已启动`,
    exited: (code) => `终端已退出（${code}）`,
    failed: "终端运行失败",
    newSession: "在当前项目文件夹中启动新的终端会话",
    clear: "清空终端回滚记录",
    cleared: "已清空终端回滚记录",
    close: "关闭当前终端会话",
    closed: "终端会话已关闭",
  },
  settings: {
    planned: "计划中", available: "可用",
    sections: { general: "常规", appearance: "外观", editor: "编辑器", "version-control": "版本控制", code: "代码" },
    generalTitle: "常规", generalDescription: "应用范围的行为与界面语言。", languageLabel: "应用语言",
    languageDescription: "选择固定的界面语言，或跟随操作系统。", languageSystem: "跟随系统", languageEnglish: "English", languageChinese: "简体中文",
    appearanceTitle: "外观", appearanceDescription: "界面颜色和应用菜单字体。", themeLabel: "主题",
    themeDescription: "选择固定配色，或跟随操作系统外观。", themeSystem: "跟随系统", themeDark: "深色", themeLight: "浅色",
    applicationFontLabel: "应用菜单字体", applicationFontDescription: "调整导航、工具栏、标签页、设置和状态文字，不缩放编辑器。",
    applicationFontAria: "应用菜单字号", editorTitle: "编辑器", editorDescription: "文本编辑器和源码差异窗格共用的默认设置。",
    editorFontLabel: "编辑器字体", editorFontDescription: "JetBrains Mono 已内置。其他字体仅在选中后下载，校验完整性并缓存在此配置中。",
    editorFontSizeLabel: "编辑器字号", editorFontSizeDescription: "立即应用于文本文件和差异代码。", editorFontSizeAria: "编辑器字号",
    lineSpacingLabel: "行距", lineSpacingDescription: "调整代码的纵向密度，不改变文件内容。", lineSpacingAria: "编辑器行距",
    letterSpacingLabel: "字距", letterSpacingDescription: "调整代码字符之间的横向间距，0 px 表示编辑器默认值。", letterSpacingAria: "编辑器字距",
    defaultPixels: (value) => `默认 · ${value} px`, indentLabel: "缩进大小", indentDescription: "设置一级编辑器缩进插入的空格数。",
    indentAria: "编辑器缩进大小", spaces: (value) => `${value} 个空格`, tabWidthLabel: "制表符宽度",
    tabWidthDescription: "调整已有制表符的显示宽度，不重写文件内容。", tabWidthAria: "编辑器制表符宽度",
    versionControlTitle: "版本控制", versionControlDescription: "当前分支更新和差异视图共用的默认设置。",
    updateStrategyLabel: "默认更新方式", updateStrategyDescription: "关闭更新确认后直接使用。合并和变基仍需准确对象安全审查。",
    updateStrategyAria: "默认远程更新方式", updateStrategies: { ffOnly: "仅快进", merge: "合并传入更改", rebase: "变基当前分支" }, askBeforeRemoteUpdateLabel: "更新确认",
    askBeforeRemoteUpdateDescription: "每次更新当前分支前，询问要使用哪种整合方式。", askBeforeRemoteUpdate: "每次更新前询问",
    diffLayoutLabel: "差异布局",
    diffLayoutDescription: "选择所有差异预览使用的默认布局。", diffLayoutAria: "默认差异布局", sideBySide: "并排", unified: "统一",
    whitespaceLabel: "空白字符", whitespaceDescription: "在差异窗格中显示空格和制表符。", showWhitespace: "显示空白字符",
    codeTitle: "代码", codeDescription: "仅在边界明确时引入语法和语言相关服务。", syntaxHighlighting: "语法高亮",
    syntaxDescription: "编辑器和差异窗格按需加载 CodeMirror 语言包。", formatting: "按语言格式化",
    formattingDescription: "格式化程序、样式配置和保存时格式化需要未来的语言服务边界。", includedWithApp: "Asterlyn 已内置",
    downloadingFont: (label) => `正在下载并校验 ${label}…`, downloadedFont: "已下载、校验并缓存",
    uncachedFont: "已在当前窗口加载；本地缓存不可用", cachedFont: "已从校验过的本地缓存加载", fontReady: "当前窗口已就绪",
    retryFont: (label) => `重试 ${label}`, editorFontAria: "编辑器字体系列",
  },
  navigation: {
    navigationMode: "导航模式",
    tabs: { files: "文件", recent: "最近", workspace: "文本", commands: "命令" },
    titles: {
      files: "搜索项目文件", recent: "筛选最近文件", workspace: "搜索当前项目中的文本", commands: "搜索可用命令",
    },
    hints: {
      files: "转到文件 · 已授权的项目目录", recent: "最近文件 · 本项目中成功打开的文件",
      workspace: "在文件中查找 · 有界搜索 · 经确认且可恢复的替换", commands: "命令面板 · 仅启用当前安全的命令",
    },
    close: "关闭", useRegularExpressions: "使用正则表达式", regularExpression: "正则表达式",
    enter: "回车", enterToSearch: "回车搜索", navigate: "导航", open: "打开",
    workspaceSearchOptions: "工作区搜索选项", include: "包含", includeAria: "要包含的文件，以逗号分隔的完整路径 glob",
    exclude: "排除", excludeAria: "要排除的文件，以逗号分隔的完整路径 glob", context: "上下文", contextLines: "上下文行数",
    replace: "替换", replacementText: "替换文本", previewReplace: "预览替换",
    reviewRecoveries: (count) => `查看 ${count} 条替换恢复记录`, recoveryRecords: (count) => `${count} 条恢复记录`,
    noMatchingCommands: "没有匹配的命令", broaderCommand: "请尝试更宽泛的命令名称。",
    noRecentFiles: "没有最近文件", noMatchingFiles: "没有匹配的文件", recentFilesDetail: "成功打开文件后会显示在这里。",
    catalogLoading: "项目目录仍在加载。", fileQueryDetail: "请尝试输入文件名或路径的一部分。",
    searchingProject: "正在搜索当前项目…", boundedSearchDetail: "扫描范围有限，并且可以取消。",
    searchFailed: "搜索未能完成", tryAgain: "请重试。", searchFileContents: "搜索文件内容",
    searchInstructions: "输入区分大小写的文本或正则表达式，然后按回车。替换始终需要单独预览。",
    noSubsetMatches: "已搜索范围内没有匹配项", noMatches: "没有匹配项", zeroWidthMatch: "零宽匹配",
    coverageMatches: (count) => `${count} 处匹配`, coverageFiles: (searched, catalog) => `已搜索 ${searched}/${catalog} 个文件`,
    coverageEligible: (searched, eligible, catalog) => `已搜索 ${searched}/${eligible} 个符合条件的文件 · 目录共 ${catalog} 个`,
    coverageComplete: "完整", coveragePartial: (reasons) => `部分结果：${reasons}`,
    coverageReasons: { catalogTruncated: "目录上限", candidateLimit: "候选上限", byteLimit: "字节上限", matchLimit: "匹配上限" },
    coverageSkipped: (count) => `跳过 ${count} 个`,
    commands: {
      "open-repository": { label: "打开项目", detail: "选择本地文件夹", aliases: "open folder repository 打开文件夹仓库" },
      "go-file": { label: "转到文件", detail: "按名称打开项目文件", aliases: "go to file quick open 快速打开" },
      "recent-files": { label: "最近文件", detail: "重新打开成功读取过的文件", aliases: "recent files history 历史" },
      "find-workspace": { label: "在文件中查找", detail: "有界搜索与经确认的替换", aliases: "find in files workspace search replace 全局搜索" },
      "find-current": { label: "在当前文件中查找和替换", detail: "可撤销的更改保留在活动缓冲区", aliases: "find replace search 查找" },
      "save-current": { label: "保存当前文件", detail: "使用可安全处理冲突的保存流程", aliases: "save write 保存" },
      refresh: { label: "刷新项目", detail: "重新加载项目文件和可用 Git 状态", aliases: "refresh reload sync 刷新" },
      "toggle-files": { label: "切换文件窗口", detail: "显示或隐藏文件工具窗口", aliases: "toggle files project tree 项目树" },
      "toggle-changes": { label: "切换更改窗口", detail: "显示或隐藏更改工具窗口", aliases: "toggle changes git status 状态" },
      "toggle-git": { label: "切换 Git 窗口", detail: "显示或隐藏分支与日志", aliases: "toggle git history branches 历史分支" },
      "toggle-terminal": { label: "切换终端窗口", detail: "显示或隐藏当前项目终端", aliases: "terminal shell console 命令行" },
    },
  },
  projectFiles: {
    locateCurrentFile: "在项目中定位当前文件", expandSelectedFolder: "展开所选文件夹", collapseSelectedFolder: "折叠所选文件夹",
    loadingProjectFiles: "正在加载项目文件…", listFailed: "无法列出项目文件", tryAgain: "重试",
    refreshingFiles: "正在刷新文件…", boundedCatalog: "当前显示有限范围的项目目录，部分路径已省略。", projectFiles: "项目文件",
    fileCount: (editable, ignored) => `${editable} 个可编辑文件，${ignored} 个已忽略条目`,
    collapsePath: (path) => `折叠 ${path}`, expandPath: (path) => `展开 ${path}`,
    changeLabels: {
      unmodified: "未修改", added: "已添加", modified: "已修改", deleted: "已删除", renamed: "已重命名",
      copied: "已复制", typeChanged: "类型已更改", unmerged: "未合并", untracked: "未跟踪",
      ignored: "已忽略", unknown: "未知",
    },
  },
  editor: {
    conflict: "冲突", saving: "正在保存", unsaved: "未保存", saved: "已保存", close: "关闭",
    closeFile: (name) => `关闭 ${name}`, preview: "预览", diff: "差异", imagePreview: "图像预览", diffPreview: "差异预览",
    closePreview: (label) => `关闭${label}`, welcome: "欢迎", markdownMode: "Markdown 编辑模式",
    source: "源码", sourceTitle: "编辑 Markdown 源码", split: "拆分", splitTitle: "编辑源码并实时预览",
    renderedPreview: "预览", previewTitle: "渲染预览（只读）", diffToolbar: "差异导航与显示",
    diffNavigation: "差异导航", previousChange: "文件中的上一处更改", nextChange: "文件中的下一处更改",
    previousFile: "上一个已更改文件", nextFile: "下一个已更改文件", openSource: "打开文件并在项目中定位",
    collapseUnchanged: "折叠未更改行", expandUnchanged: "展开未更改行", diffPresentation: "差异显示",
    unified: "统一", unifiedTitle: "统一差异", sideBySide: "并排", sideBySideTitle: "并排差异",
    whitespace: "空白字符", whitespaceTitle: "显示空白字符",
    imageAlt: (label, path) => `${path} 的${label}图像`,
    renderingMarkdown: "正在渲染 Markdown…", renderingMarkdownDetail: "预览引擎加载期间仍可使用编辑器。",
    tryAgain: "重试", loadingImage: "正在加载图像预览…", imageFailed: "无法预览图像", imageSurface: "图像预览",
    loadingImageDiff: "正在加载图像差异…", imageDiffFailed: "无法预览图像差异", before: "之前", after: "之后",
    fileDidNotExist: "文件原先不存在", fileRemoved: "文件已删除", imageDiff: "图像差异",
    markdownSource: "Markdown 源码编辑器", resizeMarkdown: "调整 Markdown 源码与预览的大小", markdownPreview: "Markdown 预览",
    largePreviewPaused: "此大文件的预览已暂停",
    largePreviewDetail: (size, limit) => `文档大小为 ${size} MiB。实时预览上限为 ${limit} MiB；仍可编辑和保存源码。`,
    markdownFailed: "Markdown 预览失败", blockedImage: "图像预览已阻止", imagePlaceholder: (label) => `[图像：${label}]`,
    linkUnavailable: "预览中无法打开链接", workspaceReady: "编辑器工作区已就绪",
    workspaceReadyDetail: "打开项目文件进行编辑，或选择已更改/已提交的文件查看差异。",
    loadingText: "正在加载文本文件…", openTextFailed: "无法打开文本文件", fileLoadFailed: "无法加载此文件。",
    localChanges: "本地更改", loadingPatch: "正在加载补丁…", patchLoadFailed: "无法加载补丁",
    noTextualDiff: "此选择没有可用的文本差异。", loadingCommitPatch: "正在加载提交补丁…",
    currentEncoding: (label) => label ? `当前文件编码：${label}` : "当前文件编码",
    ignoredReadOnly: "Git 忽略的文件以只读方式预览", outsideProjectTree: "当前文件不在有限范围的项目树中",
    searchUnsaved: "此文件有未保存的编辑，因此未跳转到搜索位置", waitForLoad: "请等待当前文件加载完成，然后重新搜索",
    openFileLimit: "20 个已打开文件均有未保存的更改；请先保存或关闭一个文件", searchRefreshFailed: "无法安全刷新搜索位置",
    wrongWorkspace: "搜索结果属于另一个工作区", invalidSearchLocation: "搜索位置已失效，请重新搜索", staleSearchResult: "搜索结果已过期，请重新搜索",
    waitForFileOperation: "请等待当前文件操作完成", savedFile: (path) => `已保存 ${path}`,
    newerEditsUnsaved: "已保存捕获的更改；较新的编辑仍未保存", waitForSave: "请等待文件保存完成",
    confirmCloseFile: (path) => `关闭前是否保存 ${path} 的更改？`, cancelKeepsTab: "取消会保持标签页打开。",
    noFileChange: (direction) => `此文件中没有${direction === "next" ? "下一处" : "上一处"}更改`,
    noChangedFile: (direction) => `没有${direction === "next" ? "下一个" : "上一个"}已更改文件`,
    diffFileMissing: "当前差异文件不在项目树中", patchTruncated: "补丁已在 4 MiB 处截断",
    externalDirtyConflict: "有未保存编辑的文件在 Asterlyn 外部发生更改，本地缓冲区已保留。",
    externalUnavailable: "文件在 Asterlyn 外部发生更改或已不可用；打开的缓冲区已保留。",
    unexpectedEditorError: "出现意外的编辑器会话错误", unexpectedProjectFilesError: "出现意外的项目文件错误",
  },
  replacement: {
    safeWorkspaceEdit: "安全工作区编辑", preparingPreview: "正在准备替换预览", rereadingFiles: "正在重新读取 Git 授权的文件…",
    cancel: "取消", previewUnavailable: "替换预览不可用", close: "关闭", createNewSearch: "请重新搜索并生成预览。",
    sameSize: "大小不变", byteDelta: (value) => `${value > 0 ? "+" : ""}${value} B`, matches: (count) => `${count} 处匹配`,
    blockedFile: "请保存或取消选择已打开并编辑的文件", comparisonFor: (path) => `${path} 的替换前后预览`, before: "之前", after: "之后",
    skippedFiles: (count) => `${count} 个不支持或无法读取的文件未纳入本次已确认的替换。`, reviewTitle: "检查文件替换",
    reviewedSummary: (matches, files) => `已检查 ${files} 个文件中的 ${matches} 处替换。只有勾选的文件会发生更改。`,
    selectAll: "选择所有文件", cancelAndRestore: "取消并恢复", applying: "正在安全应用…",
    applySelection: (matches, files) => `替换 ${files} 个文件中的 ${matches} 处内容`, noPendingRecovery: "没有待处理的替换恢复记录",
    backupsResolved: "已处理所有经检查的备份。", recoveryFileSummary: (replaced, total, conflicts) => `${total} 个文件中有 ${replaced} 个包含已检查的替换${conflicts ? ` · ${conflicts} 个需要人工检查` : ""}`,
    readyToVerify: "可以验证", needsRecovery: "需要恢复", restoring: "正在恢复…", rollBack: "回滚",
    keeping: "正在保留…", keepChanges: "保留更改", crashSafeHistory: "崩溃安全记录", recoveryTitle: "替换恢复",
    recoveryDetail: "备份会一直保留，直到你验证并保留更改，或恢复完全一致的原始内容。",
    fileStates: { original: "原始内容", replaced: "已替换", conflict: "外部已更改", unavailable: "不可用" },
    cancellationRequested: "已请求取消，正在恢复所有已更改的文件…",
    blockedPaths: (paths) => `替换前请保存、关闭或取消选择：${paths}`, blockedStatus: "已打开并编辑的文件阻止了替换",
    stoppedAndRestored: "替换已停止，所有更改的文件均已恢复", appliedWithRecovery: "替换已应用；恢复记录将保留到你选择保留或回滚",
    needsReview: "替换需要恢复检查", recoveryCount: (count) => `${count} 条替换恢复记录需要检查`, inspectionFailed: "无法检查替换恢复记录",
    rollbackBlocked: (paths) => `回滚前请保存或关闭已编辑的恢复文件：${paths}`,
    externalChangesPreserved: "部分文件已在 Asterlyn 外部更改并被保留；仍需检查恢复记录",
    changesKept: "已保留替换更改", originalsRestored: "已恢复替换前的原始内容",
  },
  changes: {
    groups: { changes: "更改", unversioned: "未纳入版本控制的文件" }, commitFileActions: "提交文件操作",
    refreshChanges: "刷新更改", selectTrackedToRestore: "请选择已跟踪文件或已暂存的新增文件进行恢复", restoreToHead: "将未提交的更改恢复到 HEAD",
    restoreChanges: "恢复未提交的更改", openSelectedDiff: "打开所选文件的差异", flatList: "平铺列表", directoryTree: "目录树",
    showAs: (view) => `以${view}显示更改`, expandAll: "展开所有文件夹", collapseAll: "折叠所有文件夹",
    checkingUntracked: "正在检查未跟踪文件", trackedReady: "已跟踪的更改已就绪。", untrackedFailed: "未跟踪文件扫描失败",
    refreshToRetry: "请刷新后重试。", workingTreeClean: "工作树干净", noLocalChanges: "没有可提交的本地更改。", changedFiles: "已更改文件",
    includeAll: (group) => `全部纳入${group}`, expand: (label) => `展开${label}`, collapse: (label) => `折叠${label}`,
    fileCount: (count) => `${count} 个文件`, include: (path) => `纳入 ${path}`, selectedDiff: (path, selected) => `${selected ? "已选择，" : ""}打开 ${path} 的完整本地差异`,
    includeInCommit: (path) => `在提交中纳入 ${path}`, resolveConflict: (path) => `解决 ${path} 中的冲突`, resolve: "解决",
    untrackedScanFailed: "无法扫描未跟踪文件，请刷新后重试。", scanningUntracked: "正在扫描未跟踪文件，当前计数为暂定值。",
    changeLabels: {
      unmodified: "未修改", added: "已添加", modified: "已修改", deleted: "已删除", renamed: "已重命名",
      copied: "已复制", typeChanged: "类型已更改", unmerged: "未合并", untracked: "未跟踪", ignored: "已忽略", unknown: "未知",
    },
    changedFileCount: (count) => `${count} 个已更改文件`, resizeCommit: "调整提交消息区域大小", createCommit: "创建提交",
    commitMessage: "提交消息", commitButton: "提交", commitAndPushButton: "提交并推送…", resolveBeforeCommit: "请先解决冲突再提交。",
    excludeSubmodules: "请排除子模块更改，并在其 Git 根目录中提交。", selectFileToCommit: "请至少选择一个要提交的文件。",
    saveBeforeRevert: "恢复此文件前，请保存或撤销未保存的编辑", restoreConfirm: (label) => `是否将 1 个已跟踪文件恢复到 HEAD？\n\n${label}\n\n这会替换已检查的暂存区和工作树内容。系统会保存恢复副本，以供撤销。`,
    restoreAddedConfirm: (label) => `是否从暂存区和工作树中移除 1 个已暂存的新增文件？\n\n${label}\n\n该文件在 HEAD 中不存在，因此恢复操作会将其删除。系统会保存恢复副本，可还原文件的完整内容和暂存状态。`,
    saveBeforeRestore: "恢复这些文件前，请保存或撤销未保存的编辑", reverting: "正在恢复所选文件…", reverted: "已恢复所选文件",
    filesSavedReview: "文件已保存；提交前请检查刷新后的选择", creatingCommit: "正在创建提交…",
    commitConcurrent: "提交已完成，但 Git 同时发生变化；再次提交前请检查刷新的历史记录", commitRefreshing: "提交已创建，正在刷新仓库状态…",
    commitCreated: "提交已创建", commitAndPushUnavailable: (reason) => `当前无法执行提交并推送，因此没有创建提交。${reason}`,
    commitCreatedPushUnavailable: (reason) => `提交已创建，但无法打开推送确认。${reason}`,
    patchTruncated: "补丁已在 4 MiB 处截断", unexpectedError: "出现意外的更改操作错误",
    fileSavedRefreshFailed: "文件已保存，但 Git 状态刷新失败",
  },
  gitOperations: {
    activeOperation: "活动 Git 操作", unresolvedFiles: (count) => `${count} 个未解决文件`, readyToContinue: "可以继续",
    names: { merge: "合并", cherryPick: "拣选", rebase: "变基", squash: "压缩", revert: "还原", bisect: "二分查找" },
    actions: { continue: "继续", skip: "跳过", abort: "中止" },
    prepare: (name) => `准备${name}`, operation: "操作",
    setupOptions: { merge: "合并到当前分支", cherryPick: "拣选提交", rebase: "变基当前分支", squash: "压缩当前分支提交" },
    targetsForCherryPick: "提交（按应用顺序）", targetBeforeSquash: "范围之前的父提交", targetRef: "目标分支、标签或提交",
    targetLinesPlaceholder: "每行一个完整引用或提交", newCommitMessage: "新提交消息", squashMessagePlaceholder: "描述压缩后的更改",
    exactReviewNote: "Asterlyn 会将每个目标解析为准确对象，并把审查绑定到当前分支、HEAD、干净的暂存区和工作树。审查后的更改会使计划失效。",
    preparing: "正在准备…", review: "审查", reviewTitle: "Git 操作审查", planUnavailable: "审查计划不可用。",
    confirm: (name) => `确认${name}`, squashWarning: "压缩会重写当前检出的分支。之后推送时必须明确审查并使用带租约的强制推送。",
    conflictWarning: "发生冲突时操作会安全暂停，并可在重启 Asterlyn 后继续恢复。", currentBranch: "当前分支",
    reviewedOperation: "已审查操作", exactTargets: "准确目标", commitMessage: "提交消息", back: "返回", running: "正在运行…",
    openConflict: "打开冲突", readingConflict: "正在读取基准、当前版本、传入版本和工作树内容…", conflictUnavailable: "冲突不可用。",
    resolve: (path) => `解决 ${path}`, conflictInputs: "冲突输入", base: "基准", ours: "当前版本", theirs: "传入版本",
    resolvedResult: "解决结果", binaryConflict: "二进制冲突无法作为文本编辑。请在外部工具中解决，或选择删除。",
    resolvedFileContent: "已解决的文件内容", resolveSafetyNote: "保存时会验证上方打开的准确暂存区阶段和工作树版本，写入结果、暂存文件并确认暂存对象。",
    resolveAsDeleted: "以删除方式解决", resolving: "正在解决…", saveAndStage: "保存并暂存",
    closeDialog: "关闭 Git 操作对话框", notPresent: "不存在", loadingReview: "正在加载 Git 操作审查…",
    discardConflict: "要丢弃未保存的冲突解决结果吗？请先复制需要的文本。取消将保留当前结果。",
    cancel: "取消",
    unavailableForFolder: "此文件夹无法执行 Git 操作", alreadyInProgress: (name) => `${name}操作已在进行中`,
    saveBeforeReview: "请保存或撤销编辑器更改，然后重新审查 Git 操作", saveBeforeChangingActive: "更改当前 Git 操作前，请保存或撤销编辑器更改",
    inProgress: (name) => `正在执行${name}…`, completed: (name) => `${name}已完成`, actionInProgress: (action) => `正在${action} Git 操作…`,
    aborted: "Git 操作已中止", skippedCommit: "Git 操作已跳过当前提交", continued: "Git 操作已继续",
    resolvingPath: (path) => `正在解决 ${path}…`, resolvedAndStaged: (path) => `已解决并暂存 ${path}`,
    paused: (name) => `${name}已暂停；请在“更改”中检查操作控件`,
    conflictPaused: "Git 因冲突暂停。请在“更改”中解决列出的文件，然后继续、跳过或中止操作。",
    conflictChangedExternally: "此冲突已在 Asterlyn 外部变化。未保存的结果仍会保留；关闭或重新打开冲突前请先复制所需内容。",
    operationFailed: "无法完成 Git 操作。",
  },
  history: {
    noRefs: "没有引用", refsAppearHere: "分支和标签会显示在这里。", branchOrTag: "分支或标签",
    filterBranchesAndTags: "筛选分支和标签", noMatchingRefs: "没有匹配的引用", tryAnotherRef: "请尝试其他分支、远程或标签名称。",
    groups: { local: "本地", remote: "远程", tag: "标签" }, activateAgainForAllRefs: "再次激活可显示所有引用",
    roots: (count) => `${count} 个 Git 根目录`, allRefs: "所有引用", allRefsTitle: "本地分支、远程跟踪分支和标签的历史记录",
    branchCount: (count) => `${count} 个分支`, textOrHash: "文本或哈希", filterCommitHistory: "筛选提交历史",
    useRegularExpression: "使用正则表达式", matchCase: "区分大小写", queryFilters: "历史查询筛选器",
    filterByAuthor: "按提交作者筛选", filterByDate: "按提交日期筛选", filterByPathsOrRoots: "按仓库路径或 Git 根目录筛选",
    graphOptions: "图谱排序和遍历选项", select: "选择…", recent: "最近", favorites: "收藏",
    allUsers: "所有用户", identity: "身份", me: "我", loadedAuthors: "已加载的作者", allDates: "所有日期",
    last24Hours: "过去 24 小时", last7Days: "过去 7 天", selectInTree: "在树中选择…", rootsLabel: "根目录",
    loadingTrackedPaths: "正在加载跟踪路径…", trackedPathsFailed: "无法加载跟踪路径。",
    boundedTree: "树选择使用有界的项目文件集合。", keepOneRoot: "至少必须保留一个模块",
    includeRootHistory: (name) => `包含 ${name} 的历史`, sort: "排序", byCommitDate: "按提交日期",
    topologically: "拓扑顺序", options: "选项", firstParent: "仅第一父提交", noMerges: "排除合并",
    branchActions: "分支操作", expandLinearBranches: "展开线性分支", collapseLinearBranches: "折叠线性分支",
    pathsCount: (count) => `${count} 个路径`, rootsCount: (count) => `${count} 个根目录`, paths: "路径", user: "用户",
    userCount: (count) => `${count} 个用户`, date: "日期", hours24: "24 小时", days7: "7 天",
    loadingFilteredHistory: "正在加载筛选后的历史…", couldNotLoadHistory: "无法加载历史记录",
    queryCouldNotBeRead: "无法读取所选的历史查询。", noCommitsForFilters: "没有符合这些筛选条件的提交",
    clearFilters: "清除一个或多个历史筛选条件以扩大查询范围。",
    invalidExpression: (error, showing) => `表达式无效：${error}${showing ? "。正在显示未筛选的结果。" : ""}`,
    noMatchingCommits: "没有匹配的提交", tryCommitSearch: "请尝试提交消息、作者、引用或完整哈希。",
    expandLinearTitle: (count) => `展开 ${count} 个线性提交`, linearCommitsCollapsed: (count) => `已折叠 ${count} 个线性提交`,
    expand: "展开", gitRoot: (path) => `Git 根目录：${path}`, commitHistory: "提交历史",
    loadingOlderCommits: "正在加载更早的提交…", showingNewestLimit: (count) => `显示最新的 ${count} 个提交（会话上限）`,
    scrollForOlder: "滚动以加载更早的提交", allHistoryLoaded: (count) => `已加载全部历史 · ${count} 个提交`,
    noOlderCommits: "当前筛选条件下没有更早的提交。",
    olderCommitsFailed: (detail) => `无法加载更早的提交：${detail}`,
    historyRefreshFailed: (detail) => `无法刷新提交历史：${detail}`,
    historyRefreshWarning: "无法完成提交历史刷新", filteredHistoryWarning: "无法加载筛选后的提交历史",
    rootCommit: "根提交", oneParent: "一个父提交",
    mergeParents: (count) => `有 ${count} 个父提交的合并提交`,
    collapsedGraphLane: (lane, total) => `提交图第 ${lane}/${total} 轨中的折叠线性延续`,
    graphLane: (lane, total, parent) => `提交图第 ${lane}/${total} 轨，${parent}`,
    state: "状态", upstream: "上游", tracking: "跟踪", updated: "更新于", checkedOut: "已检出", none: "无",
    noDivergence: "没有分歧", operationsUsing: (name) => `使用 ${name} 的操作`, mergeIntoCurrent: "合并到当前分支",
    rebaseCurrentOnto: "将当前分支变基到此处", checkout: "检出", currentBranch: "当前分支",
    checkoutBranch: (name) => `检出 ${name}`, checkoutBlocked: "检出被阻止", localBranchesOnly: "仅限本地分支",
    submoduleHistoryOnly: "仅查看子模块历史", selectLocalBranch: "请选择要检出的本地分支。远程分支和标签检出暂未开放。",
    submoduleReadOnly: "此已初始化子模块仅供查看历史；分支更改仍限定在主仓库。", moreBlockers: (count) => `另有 ${count} 项`,
    changedPathsBlock: (count) => `${count} 个已更改路径阻止分支操作。请先提交、暂存或移除这些更改。`,
    checkingUntrackedForBranch: "正在检查未跟踪文件，然后才能执行分支操作…",
    untrackedCheckFailedForBranch: "未跟踪文件检查失败。请刷新后再更改分支。",
    cleanWorktreeVerified: "暂存区和工作树均干净。切换前 Asterlyn 会立即再次验证。",
    newLocalBranch: "新建本地分支", createFromHead: "从当前 HEAD 创建，并使用相同的干净工作树检查。",
    branchName: "分支名称", createAndCheckout: "创建并检出", details: "详情", nothingSelected: "未选择任何项目",
    selectToInspect: "选择一个项目以查看元数据和可用操作。", changedFiles: "已更改文件", files: "文件",
    flatList: "平铺列表", directoryTree: "目录树", showChangedFilesAs: (view) => `以${view}显示已更改文件`,
    expandChangedFolders: "展开所有已更改文件夹", collapseChangedFolders: "折叠所有已更改文件夹",
    resizeCommitDetails: "调整提交消息和详情大小", loadingChangedFiles: "正在加载已更改文件…",
    couldNotLoadCommit: "无法加载提交", noFirstParentChanges: "相对第一父提交没有变化",
    changedFilesByDirectory: "按目录显示已更改文件", fileCount: (count) => `${count} 个文件`,
    operationsUsingCommit: "使用此提交的操作", cherryPick: "拣选", squashAfterThis: "压缩此提交之后的提交",
    commitMessageAndDetails: "提交消息和详情", authoredOn: "提交于", emptyTree: "空树",
    noNamedRefs: "没有命名引用指向此提交", refsSummary: (count, summary) => `位于 ${count} 个引用中：${summary}…`,
    showAll: "显示全部", firstParentComparison: "第一父提交比较", comparedWith: (value) => `比较基准：${value}`,
    unknownTime: "时间未知", referenceKinds: { head: "HEAD", local: "本地", remote: "远程", tag: "标签", other: "其他" },
    countOfCommits: (filtered, total, scope) => `${scope}中显示 ${filtered}/${total} 个提交`, refreshing: "正在刷新…",
    logicalRefsCount: (visible, total) => `显示 ${visible}/${total} 个逻辑引用`, applyCount: (count) => `应用 ${count}`,
    selectBranchesOrTags: "选择分支或标签", noMatchingBranchesOrTags: "没有匹配的分支或标签。",
    availableBranchesAndTags: "可用分支和标签", addToFavorites: "添加到收藏", removeFromFavorites: "从收藏中移除",
    clear: "清除", apply: "应用", all: "全部", selectPathsToFilter: "选择要筛选的路径",
    pathTextHelp: "每行输入一个准确的已跟踪文件或目录。按 Ctrl/Cmd+Enter 应用选择。",
    trackedRepositoryPaths: "仓库中已跟踪的路径", noTrackedPaths: "没有已跟踪路径。",
    unknownTrackedPath: (path) => `未知的已跟踪路径：${path}`,
    ambiguousTrackedPath: (path) => `路径属于多个 Git 根目录：${path}`,
    expandPath: (path) => `展开 ${path}`, collapsePath: (path) => `折叠 ${path}`,
    checkingOut: (name) => `正在检出 ${name}…`, checkedOutBranch: (name) => `已检出 ${name}`,
    creatingBranch: (name) => `正在创建 ${name}…`, createdBranch: (name) => `已创建并检出 ${name}`,
  },
  recovery: {
    title: "恢复本地更改", close: "关闭", loading: "正在加载恢复副本…",
    noneAvailable: "此项目没有可用的恢复副本。新的恢复和冲突解决操作会自动创建副本。", undoOperation: "撤销此操作",
    confirmUndo: (operation, paths) => `是否撤销 ${operation}？\n\n${paths}\n\n这会恢复之前的文件和暂存状态。如果文件、暂存区或 HEAD 已发生变化，撤销会停止并保留恢复副本。`,
    incomplete: (path) => `此操作尚未完成验证。恢复前请检查保留的原始文件和拟议结果：${path}`,
    waitForOperation: "请等待当前操作完成。", saveBeforeRestore: "恢复这些文件前，请保存或撤销未保存的编辑。",
    restoring: "正在恢复本地更改…", restored: "已恢复本地更改",
  },
  remote: {
    unsupported: "不支持", noRemote: "没有远程仓库", noBranch: "没有分支", noCheckedOutBranch: "没有已检出的分支", noUpstream: "没有上游",
    selectedRemoteScope: (remote) => `已选远程仓库：${remote}。获取会刷新该远程仓库的所有标准分支跟踪引用；更新和推送仅作用于当前检出的分支。`,
    unavailable: (detail) => `不可用：${detail}`,
    cancelOperation: (kind, branch, remote) => `取消使用 ${remote} 对 ${branch} 执行的${kind}。Git 可能已经更改本地或远程状态，因此 Asterlyn 会先刷新再允许其他操作。`,
    cancelRemoteOperation: "取消远程操作", actionNames: { fetch: "获取", pull: "更新", push: "推送" },
    selectionUnavailable: "此项目不是活动 Git 仓库，无法选择远程仓库。",
    fetchUnavailable: "此项目不是活动 Git 仓库，无法获取。获取会刷新所选远程仓库的标准分支跟踪引用，且不会更改工作文件。",
    updateUnavailable: "此项目不是活动 Git 仓库，无法更新。更新只会影响当前检出的分支，并要求确认快进。",
    pushUnavailable: "此项目不是活动 Git 仓库，无法推送。推送会先打开当前分支审查，然后才写入远程仓库。",
    actionStateChanged: (action) => `仓库状态在打开${action}前发生了变化。请检查当前状态后重试。`,
    workbenchBusy: "请等待当前工作台任务完成。",
    fetchDescription: (remote, behind) => `从 ${remote} 获取。刷新此远程仓库的所有标准分支跟踪引用，不更改当前检出分支或工作文件。徽标显示上次获取后已知的 ${behind} 个传入提交。`,
    updateDescription: (source, remote, destination) => `从 ${remote}:${destination} 更新 ${source}。将打开快进、合并或变基确认。合并和变基会先获取，再要求第二次准确对象审查；冲突会暂停，等待明确解决、继续、跳过或中止。`,
    pushDescription: (source, remote, destination, ahead) => `审查从 ${source} 到 ${remote}:${destination} 的推送。徽标显示上次获取后已知的 ${ahead} 个传出提交。审查可明确纳入标签或选择带准确租约的强制推送，并且不会自动重试。`,
    strategies: { ffOnly: "快进", merge: "合并", rebase: "变基" }, cancelling: "正在取消…", updating: "正在更新…", update: "更新",
    fetchAndReview: (strategy) => `获取并审查${strategy}`, currentBranch: "当前分支", updateBranch: (branch) => `更新 ${branch}`,
    cancelUpdateConfirmation: "取消更新确认",
    updateDescriptionText: "选择如何把配置的上游整合到当前检出分支。合并和变基会先获取，然后在更改本地历史前打开准确对象审查。",
    updateRoute: "更新路径", updateMethod: "更新方式", fastForwardOnly: "仅快进",
    fastForwardDetail: "获取配置的上游，仅在无需合并或变基时移动当前分支。", mergeIncoming: "合并传入更改",
    mergeIncomingDetail: "获取并审查准确的跟踪提交，然后合并。冲突会暂停，并提供可编辑的基准、当前版本和传入版本内容。",
    rebaseCurrent: "变基当前分支", rebaseCurrentDetail: "获取并审查准确的跟踪提交，然后重放本地提交。继续、跳过和中止都可在重启后安全恢复。",
    updateSafetyNote: "确认后会执行快进。合并和变基还需一次绑定到已获取对象和当前干净 HEAD 的审查。不会执行重置、暂存、强制操作或自动重试。",
    dontAskAgain: "不再询问",
    cancelUpdate: "取消更新", updateFastForwardAria: (source, remote, destination) => `仅以快进方式从 ${remote}:${destination} 更新 ${source}`,
    updateReviewAria: (remote, strategy, destination, source) => `获取 ${remote}，然后审查将 ${remote}:${destination} ${strategy}到 ${source}`,
    readingPushPreview: "正在从上次获取的引用读取传出提交、标签和文件…", pushPreviewUnavailable: "推送预览不可用。请关闭窗口并刷新后重试。",
    route: (source, remote, destination) => `${source} 到 ${remote}:${destination}`, selectedRoute: "所选当前分支路径",
    forcePushWithLease: "带租约强制推送", publish: "发布", push: "推送", tags: (count) => `${count} 个标签`, noMatchingTags: "没有匹配标签",
    pushCommitsTo: (branch) => `将提交推送到 ${branch}`, currentBranchFallback: "当前分支", cancelPushConfirmation: "取消推送确认",
    pushReviewDescription: "写入所选远程仓库之前，审查准确的当前分支路径、传出提交、汇总文件更改、可选标签和推送模式。",
    forcePushNote: "强制推送使用绑定到上次获取的目标对象的准确 --force-with-lease。如果远程仓库已更改，Git 会拒绝推送。",
    ordinaryPushNote: "普通推送不会重写目标。", tagsAndRetryNote: "仅在启用复选框时发送标签。操作被拒绝后会结束；Asterlyn 不会自动重试。",
    pushTags: "推送标签：", tagScope: "标签范围", all: "全部", refreshingReview: "正在刷新审查…", cancelPush: "取消推送", pushing: "正在推送…",
    checkingAuthentication: "正在检查身份验证…",
    authenticationTitle: (host) => `登录 ${host}`,
    authenticationDescription: (remote) => `Asterlyn 没有找到 ${remote} 可用的非交互式凭据。请先完成配置，再开始推送。`,
    httpsCredentialTitle: "HTTPS 个人访问令牌",
    passwordUnsupported: "GitHub 和许多 Git 托管服务不再接受账号密码执行 Git 操作。请使用具有此仓库写入权限的个人访问令牌。",
    username: "账号名称", usernamePlaceholder: "Git 账号名称",
    personalAccessToken: "个人访问令牌", tokenPlaceholder: "粘贴令牌",
    credentialStorageNotice: "令牌会直接交给 Git，并且只由已配置的系统凭据管理器保留。Asterlyn 不会把它写入偏好设置或仓库文件。",
    credentialHelperMissing: "尚未配置 Git 凭据管理器。保存时 Asterlyn 会配置已安装的安全系统凭据管理器；你也可以改用 SSH。",
    credentialHelperUnavailable: "系统中没有安装受支持的安全 Git 凭据管理器。请安装或配置凭据管理器，或者改用 SSH。",
    saveCredentialAndPush: "保存并推送", savingCredential: "正在保存凭据…",
    sshCredentialTitle: "SSH",
    sshCredentialDescription: "使用现有 SSH 密钥或代理。修改此项只会更新该远程仓库的推送地址，获取地址保持不变。",
    sshUrl: "SSH 推送地址", sshUrlPlaceholder: "git@host:owner/repository.git",
    configureSshAndPush: "使用 SSH 并推送", configuringSsh: "正在配置 SSH…",
    sshIdentityMissing: "SSH 推送地址已配置，但没有检测到本地 SSH 代理或标准私钥。请完成密钥配置后重新检查。",
    recheckAuthentication: "重新检查",
    authenticationFieldsRequired: "请同时填写账号名称和个人访问令牌。",
    credentialNotRetained: "Git 没有返回刚保存的凭据。请检查系统凭据管理器后重试。",
    sshUrlRequired: "请输入 SSH 推送地址。",
    invalidSshUrl: "请输入 ssh:// 地址，或 git@host:owner/repository.git 形式的 SSH 地址。",
    pushConfirmationAria: (action, commits, tags, route) => `${action}：通过${route}发送 ${commits} 个传出提交和 ${tags} 个所选标签`,
    choosePushMode: "选择推送模式", pushMode: "推送模式", ordinaryNonForce: "普通非强制更新",
    forceLeaseDetail: "仅在远程仍与已审查对象一致时重写", pushRouteAria: (branch, destination) => `从本地分支 ${branch} 推送到远程分支 ${destination}`,
    showAllOutgoingFiles: "显示所有传出提交更改的文件", localBranch: "本地分支", outgoingCommitCount: (count) => `${count} 个传出提交`,
    showAllFiles: "显示所有文件", remoteBranch: "远程分支", pushRemote: "推送远程仓库", selectedDestination: "此推送所选的目标",
    noNewCommitObjects: "相对于所选远程仓库上次获取的引用，没有可见的新提交对象。", publishCreatesDestination: "发布仍会创建目标分支。",
    filesInSelectedCommit: "所选提交中的文件", filesInAllCommits: "所有传出提交中的文件", outgoingCommits: "传出提交",
    outgoingListAria: "传出提交；再次激活所选提交可显示所有传出文件", loading: "正在加载…", showMore: "显示更多",
    truncatedCommits: (total) => `显示前 1,000/${total} 个提交。推送会包含全部 ${total} 个提交。`,
    readingSelectedFiles: "正在读取所选提交中的文件…", pushedRangeExceeded: "推送文件范围超过有界审查上限。",
    noSelectedCommitFiles: "所选提交没有报告文件。", noNetFileChanges: "审查范围内没有净文件更改。",
    pushedFileToolbar: "已推送文件的显示和导航", openOutgoingDiff: "打开所选文件最新传出提交的差异",
    showPushedFilesAs: (view) => `以${view}显示推送文件`, flatList: "平铺列表", folderTree: "文件夹树",
    expandPushedFolders: "展开所有推送文件夹", collapsePushedFolders: "折叠所有推送文件夹",
    loadingPushedDiff: "正在加载推送文件差异…", closePushedDiff: "关闭推送文件差异", pushedDiffToolbar: "推送文件差异的导航和显示",
    previousPushedFile: "上一个推送文件", nextPushedFile: "下一个推送文件", imagePreviewAlt: (label) => `${label}图片预览`,
    upstreamChanged: "获取期间当前上游发生变化；请重新打开“更新”", alreadyUpToDate: "所有文件均为最新",
    activeProjectNotGit: "当前项目已不再是 Git 仓库。", endedRefreshRequired: "远程操作已结束；需要刷新",
    operationInProgress: (name) => `正在${name}…`, operationCompleted: (name) => `${name}已完成`, operationNeedsReview: "远程操作需要检查",
    cancellingOperation: (name) => `正在取消${name}…`,
    branchOrRemoteChanged: "分支或远程跟踪状态已变化。请关闭窗口并重新审查推送。",
    noOutgoingCommitForFile: (path) => `传出提交中不再包含 ${path}。`,
    selectedOutgoingFileMissing: "所选传出文件已不存在。请刷新推送审查。",
    unexpectedError: "无法完成远程操作。",
    policy: {
      finishActive: (name) => `请先完成正在进行的${name}操作。`, selectConfigured: "请选择已配置的远程仓库。",
      unsupportedFetch: "此远程仓库使用不支持的获取映射。", refreshRefs: (remote) => `刷新 ${remote} 的所有标准分支跟踪引用。`,
      requireBranch: "需要一个包含提交的已检出分支。",
      publishOrConfigure: "请先发布分支或配置受支持的上游。", selectUpstream: "请选择当前分支的上游远程仓库。",
      selectNamedUpstream: (name) => `请选择此分支配置的上游 ${name}。`, unsupportedUpstream: "上游使用不支持的获取映射。",
      waitForScan: "请等待完整工作树扫描。", refreshAfterScanFailure: "工作树扫描失败后请刷新。", clearLocalChanges: "请先提交、暂存或移除本地更改。",
      reviewDivergence: (ahead, behind) => `审查 ${ahead} 个本地提交和 ${behind} 个传入提交的合并或变基。`,
      fastForward: (count) => `按 ${count} 个上游提交快进。`, checkUpstream: "获取已配置的上游，并判断当前检出分支是最新、落后还是已经分叉。",
      unsupportedPush: "此远程仓库为镜像或使用不支持的映射。", reviewOtherRemote: (remote, upstream) => `审查 ${remote} 上同名分支。推送成功后仍保留 ${upstream} 为配置的上游。`,
      createRemoteBranch: (remote) => `在 ${remote} 上创建同名分支。`, publishBranch: "发布分支",
      behindOrDiverged: "分支落后或已经分叉。普通推送在审查中仍会被阻止；只有明确选择时才可使用带租约的强制推送。",
      sendCommits: (count, remote) => `向 ${remote} 发送 ${count} 个提交。`, noPendingCommits: "没有待推送的分支提交；可打开审查以检查可选标签。",
    },
  },
  errors: {
    remoteCancelledUnknown: "已请求取消推送。远程结果未知；重试前请先获取。",
    remoteCancelledChanged: "远程操作已取消。仓库引用或文件可能已更改；视图已经刷新。",
    remoteCancelled: "远程操作已取消。",
    remoteFailedFallback: "远程操作失败，且没有子进程输出。请检查 Git 配置后重试。",
    authenticationFailed: "身份验证不可用。请配置非交互式 Git 凭据助手或 SSH 代理后重试。",
    networkFailed: "无法连接远程仓库。请检查网络和远程仓库配置。",
    remoteRejected: "远程仓库拒绝了更新。请获取并检查分支状态后重试。",
    fileConflictPreserved: "此文件在 Asterlyn 外部发生变化。本地缓冲区仍保持打开，且未被覆盖。",
    unexpectedOperation: "发生意外的操作错误。",
    watchUnavailable: (detail) => detail ? `原生文件监听不可用：${detail}` : "原生文件监听不可用；窗口聚焦刷新和手动刷新仍然有效。",
    watchStartFailed: (detail) => `原生文件监听无法启动：${detail}`,
    externalReconcileFailed: (detail) => `无法同步外部更改：${detail}`,
    translate: translateKnownError,
  },
  editorPhrases: {
    "Control character": "控制字符",
    "Go to line": "转到行",
    "Selection deleted": "已删除所选内容",
    close: "关闭",
    "current match": "当前匹配",
    "folded code": "已折叠的代码",
    go: "转到",
    "on line": "位于第",
    "replaced $ matches": "已替换 $ 处匹配",
    "replaced match on line $": "已替换第 $ 行的匹配",
    to: "至",
    unfold: "展开",
    Find: "查找",
    Replace: "替换",
    next: "下一个",
    previous: "上一个",
    all: "全部",
    "match case": "区分大小写",
    regexp: "正则表达式",
    "by word": "全字匹配",
    replace: "替换",
    "replace all": "全部替换",
    "Folded lines": "已折叠行",
    "Unfolded lines": "已展开行",
    "Fold line": "折叠行",
    "Unfold line": "展开行",
  },
  documentDescription: "Asterlyn — 以 Git 为中心的轻量开发工作区。",
} satisfies LocaleCatalog;

function translateKnownError(message: string): string {
  const exact: Readonly<Record<string, string>> = {
    "The Git operation could not complete.": "无法完成 Git 操作。",
    "This conflict changed outside Asterlyn. Your unsaved result is preserved; copy it before closing or reopening the conflict.": "此冲突已在 Asterlyn 外部变化。未保存的结果仍会保留；关闭或重新打开冲突前请先复制所需内容。",
    "The branch or remote-tracking state changed. Close and review Push again.": "分支或远程跟踪状态已变化。请关闭窗口并重新审查推送。",
    "The selected outgoing file is no longer present. Refresh the Push review.": "所选传出文件已不存在。请刷新推送审查。",
    "Invalid regular expression": "无效的正则表达式",
  };
  const known = exact[message];
  if (known) return known;
  const missingOutgoing = message.match(/^No outgoing commit contains (.+)\.$/u);
  return missingOutgoing ? `传出提交中不再包含 ${missingOutgoing[1]}。` : message;
}
